@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	armshare
	.type	 armshare,function
	.thumb_func
armshare:
	lsl	r0, r0, #0x1
	add	r0, r0, r1
	lsl	r0, r0, #0x2
	ldr	r1, .L7
	add	r0, r0, r1
	ldrb	r3, [r0, #0x1]
	ldrb	r2, [r0]
	ldr	r0, .L7+0x4
	ldrb	r1, [r0]
	mov	r0, #0x1
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L3	@cond_branch
	cmp	r3, #0x2
	bne	.L4	@cond_branch
	ldr	r1, .L7+0x8
	lsl	r0, r2, #0x3
	b	.L6
.L8:
	.align	2, 0
.L7:
	.word	0x8057acc
	.word	0x3003430
	.word	0x3003440
.L4:
	ldr	r1, .L9
	lsl	r0, r2, #0x4
.L6:
	str	r0, [r1]
.L3:
	bx	lr
.L10:
	.align	2, 0
.L9:
	.word	0x3003444
.Lfe1:
	.size	 armshare,.Lfe1-armshare
