@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	UpdateWorldMapNodeTile
	.type	 UpdateWorldMapNodeTile,function
	.thumb_func
UpdateWorldMapNodeTile:
	push	{r4, r5, r6, lr}
	add	sp, sp, #-0x4
	lsl	r0, r0, #0x18
	lsr	r3, r0, #0x18
	cmp	r3, #0x3
	bhi	.L3	@cond_branch
	ldr	r6, .L6
	ldr	r4, .L6+0x4
	lsl	r5, r3, #0x3
	add	r2, r5, r4
	add	r0, r4, #0x1
	add	r0, r5, r0
	ldrb	r1, [r0]
	lsl	r1, r1, #0x5
	ldrb	r2, [r2]
	add	r1, r1, r2
	lsl	r1, r1, #0x1
	mov	r0, #0x80
	lsl	r0, r0, #0x4
	add	r6, r6, r0
	add	r1, r1, r6
	ldr	r0, .L6+0x8
	add	r0, r3, r0
	ldrb	r3, [r0]
	add	r3, r3, #0x1c
	lsl	r0, r3, #0x6
	add	r0, r0, r6
	ldrh	r0, [r0]
	strh	r0, [r1]
	add	r2, r4, #0x2
	add	r2, r5, r2
	add	r0, r4, #0x3
	add	r0, r5, r0
	ldrb	r1, [r0]
	lsl	r1, r1, #0x5
	ldrb	r2, [r2]
	add	r1, r1, r2
	lsl	r1, r1, #0x1
	add	r1, r1, r6
	lsl	r3, r3, #0x5
	add	r0, r3, #0x1
	lsl	r0, r0, #0x1
	add	r0, r0, r6
	ldrh	r0, [r0]
	strh	r0, [r1]
	add	r2, r4, #0x4
	add	r2, r5, r2
	add	r0, r4, #0x5
	add	r0, r5, r0
	ldrb	r1, [r0]
	lsl	r1, r1, #0x5
	ldrb	r2, [r2]
	add	r1, r1, r2
	lsl	r1, r1, #0x1
	add	r1, r1, r6
	add	r0, r3, #0x2
	lsl	r0, r0, #0x1
	add	r0, r0, r6
	ldrh	r0, [r0]
	strh	r0, [r1]
	add	r1, r4, #0x6
	add	r1, r5, r1
	add	r4, r4, #0x7
	add	r5, r5, r4
	ldrb	r0, [r5]
	lsl	r0, r0, #0x5
	ldrb	r1, [r1]
	add	r0, r0, r1
	lsl	r0, r0, #0x1
	add	r0, r0, r6
	add	r3, r3, #0x3
	b	.L5
.L7:
	.align	2, 0
.L6:
	.word	gBgTilemapBufs
	.word	gUnk_08116748
	.word	gUnk_08116880
.L3:
	ldr	r6, .L8
	ldr	r4, .L8+0x4
	lsl	r5, r3, #0x3
	add	r2, r5, r4
	add	r0, r4, #0x1
	add	r0, r5, r0
	ldrb	r1, [r0]
	lsl	r1, r1, #0x5
	ldrb	r2, [r2]
	add	r1, r1, r2
	lsl	r1, r1, #0x1
	mov	r0, #0x80
	lsl	r0, r0, #0x4
	add	r6, r6, r0
	add	r1, r1, r6
	ldr	r0, .L8+0x8
	add	r0, r3, r0
	ldrb	r3, [r0]
	add	r3, r3, #0x1c
	lsl	r3, r3, #0x5
	add	r0, r3, #0x4
	lsl	r0, r0, #0x1
	add	r0, r0, r6
	ldrh	r0, [r0]
	strh	r0, [r1]
	add	r2, r4, #0x2
	add	r2, r5, r2
	add	r0, r4, #0x3
	add	r0, r5, r0
	ldrb	r1, [r0]
	lsl	r1, r1, #0x5
	ldrb	r2, [r2]
	add	r1, r1, r2
	lsl	r1, r1, #0x1
	add	r1, r1, r6
	add	r0, r3, #0x5
	lsl	r0, r0, #0x1
	add	r0, r0, r6
	ldrh	r0, [r0]
	strh	r0, [r1]
	add	r2, r4, #0x4
	add	r2, r5, r2
	add	r0, r4, #0x5
	add	r0, r5, r0
	ldrb	r1, [r0]
	lsl	r1, r1, #0x5
	ldrb	r2, [r2]
	add	r1, r1, r2
	lsl	r1, r1, #0x1
	add	r1, r1, r6
	add	r0, r3, #0x6
	lsl	r0, r0, #0x1
	add	r0, r0, r6
	ldrh	r0, [r0]
	strh	r0, [r1]
	add	r1, r4, #0x6
	add	r1, r5, r1
	add	r4, r4, #0x7
	add	r5, r5, r4
	ldrb	r0, [r5]
	lsl	r0, r0, #0x5
	ldrb	r1, [r1]
	add	r0, r0, r1
	lsl	r0, r0, #0x1
	add	r0, r0, r6
	add	r3, r3, #0x7
.L5:
	lsl	r3, r3, #0x1
	add	r3, r3, r6
	ldrh	r1, [r3]
	strh	r1, [r0]
	add	sp, sp, #0x4
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.L9:
	.align	2, 0
.L8:
	.word	gBgTilemapBufs
	.word	gUnk_08116748
	.word	gUnk_08116880
.Lfe1:
	.size	 UpdateWorldMapNodeTile,.Lfe1-UpdateWorldMapNodeTile

.text
	.align	2, 0
