@ GENERATED by scripts/regen-switch-spelling-probes.ts — do not hand-edit.
@ source    : packages/core/test/corpus/probe-agbcc-swfrontload.c
@ toolchain : ARMV4T_AGBCC (gcc 2.9-arm, Thumb), binary from $ASMLIFT_AGBCC
@ cc flags  : -mthumb-interwork -Wimplicit -O2 -fhex-asm -fprologue-bugfix
@ read by   : packages/core/test/switch-arms.test.ts
@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	f
	.type	 f,function
	.thumb_func
f:
	mov	r1, #0x0
	cmp	r0, #0x1e
	beq	.L5	@cond_branch
	cmp	r0, #0x64
	bne	.L3	@cond_branch
	mov	r1, #0x1
	b	.L3
.L5:
	mov	r1, #0x2
.L3:
	add	r0, r1, #0
	bx	lr
.Lfe1:
	.size	 f,.Lfe1-f
