@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	extscale
	.type	 extscale,function
	.thumb_func
extscale:
	ldr	r2, .L3
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x16
	ldr	r1, .L3+0x4
	add	r0, r0, r1
	str	r0, [r2]
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	gB
	.word	gT
.Lfe1:
	.size	 extscale,.Lfe1-extscale
