@ GENERATED by scripts/regen-double-arg-probes.ts — do not hand-edit.
@ source    : packages/core/test/corpus/probe-agbcc-double-args.c
@ toolchain : ARMV4T_AGBCC (gcc 2.9-arm, Thumb), binary from $ASMLIFT_AGBCC
@ cc flags  : -Wimplicit -mthumb-interwork -O2 -fhex-asm -fprologue-bugfix
@ read by   : packages/core/test/double-args.test.ts
@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	dreg
	.type	 dreg,function
	.thumb_func
dreg:
	push	{lr}
	ldr	r1, .L3+0x4		@ created by thumb_load_double_from_address
	ldr	r0, .L3		@ created by thumb_load_double_from_address
	bl	g
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.long 0x3ff80000, 0x0	@ double 1.50000000000000000000e0
.Lfe1:
	.size	 dreg,.Lfe1-dreg
	.align	2, 0
	.globl	dsplit
	.type	 dsplit,function
	.thumb_func
dsplit:
	push	{lr}
	add	sp, sp, #-0x4
	mov	r2, #0x0
	str	r2, [sp]
	ldr	r3, .L6
	mov	r2, #0x7
	bl	f4
	add	sp, sp, #0x4
	pop	{r0}
	bx	r0
.L7:
	.align	2, 0
.L6:
	.word	0x3ff80000
.Lfe2:
	.size	 dsplit,.Lfe2-dsplit
	.align	2, 0
	.globl	dstack
	.type	 dstack,function
	.thumb_func
dstack:
	push	{r4, r5, lr}
	add	sp, sp, #-0x8
	add	r2, r0, r1
	sub	r3, r0, r1
	ldr	r5, .L9+0x4		@ created by thumb_load_double_from_address
	ldr	r4, .L9		@ created by thumb_load_double_from_address
	str	r4, [sp]
	str	r5, [sp, #0x4]
	bl	f5
	add	sp, sp, #0x8
	pop	{r4, r5}
	pop	{r0}
	bx	r0
.L10:
	.align	2, 0
.L9:
	.long 0x3ff80000, 0x0	@ double 1.50000000000000000000e0
.Lfe3:
	.size	 dstack,.Lfe3-dstack
	.align	2, 0
	.globl	dgap
	.type	 dgap,function
	.thumb_func
dgap:
	push	{lr}
	add	sp, sp, #-0xc
	mov	r2, #0x3
	str	r2, [sp]
	ldr	r3, .L12+0x4		@ created by thumb_load_double_from_address
	ldr	r2, .L12		@ created by thumb_load_double_from_address
	str	r2, [sp, #0x4]
	str	r3, [sp, #0x8]
	mov	r2, #0x1
	mov	r3, #0x2
	bl	f6
	add	sp, sp, #0xc
	pop	{r0}
	bx	r0
.L13:
	.align	2, 0
.L12:
	.long 0xc0060000, 0x0	@ double -2.75000000000000000000e0
.Lfe4:
	.size	 dgap,.Lfe4-dgap
	.align	2, 0
	.globl	dtiny
	.type	 dtiny,function
	.thumb_func
dtiny:
	push	{lr}
	ldr	r1, .L15+0x4		@ created by thumb_load_double_from_address
	ldr	r0, .L15		@ created by thumb_load_double_from_address
	bl	g
	pop	{r0}
	bx	r0
.L16:
	.align	2, 0
.L15:
	.long 0x0, 0x1	@ double 4.94065645841246544177e-324
.Lfe5:
	.size	 dtiny,.Lfe5-dtiny
	.align	2, 0
	.globl	dtenth
	.type	 dtenth,function
	.thumb_func
dtenth:
	push	{lr}
	ldr	r1, .L18+0x4		@ created by thumb_load_double_from_address
	ldr	r0, .L18		@ created by thumb_load_double_from_address
	bl	g
	pop	{r0}
	bx	r0
.L19:
	.align	2, 0
.L18:
	.long 0x3fb99999, 0x9999999a	@ double 1.00000000000000005551e-1
.Lfe6:
	.size	 dtenth,.Lfe6-dtenth
	.align	2, 0
	.globl	dtwo
	.type	 dtwo,function
	.thumb_func
dtwo:
	push	{lr}
	ldr	r1, .L21+0x4		@ created by thumb_load_double_from_address
	ldr	r0, .L21		@ created by thumb_load_double_from_address
	bl	g
	pop	{r0}
	bx	r0
.L22:
	.align	2, 0
.L21:
	.long 0x40000000, 0x0	@ double 2.00000000000000000000e0
.Lfe7:
	.size	 dtwo,.Lfe7-dtwo
	.align	2, 0
	.globl	dnegzero
	.type	 dnegzero,function
	.thumb_func
dnegzero:
	push	{lr}
	ldr	r1, .L24+0x4		@ created by thumb_load_double_from_address
	ldr	r0, .L24		@ created by thumb_load_double_from_address
	bl	g
	pop	{r0}
	bx	r0
.L25:
	.align	2, 0
.L24:
	.long 0x80000000, 0x0	@ double -0.00000000000000000000e0
.Lfe8:
	.size	 dnegzero,.Lfe8-dnegzero
	.align	2, 0
	.globl	dpass
	.type	 dpass,function
	.thumb_func
dpass:
	push	{lr}
	bl	g
	pop	{r0}
	bx	r0
.Lfe9:
	.size	 dpass,.Lfe9-dpass
	.align	2, 0
	.globl	dmove
	.type	 dmove,function
	.thumb_func
dmove:
	push	{r4, lr}
	add	sp, sp, #-0x4
	add	r4, r0, #0
	str	r2, [sp]
	add	r3, r1, #0
	add	r1, r4, #0
	add	r2, r4, #0
	bl	f4
	add	sp, sp, #0x4
	pop	{r4}
	pop	{r0}
	bx	r0
.Lfe10:
	.size	 dmove,.Lfe10-dmove
	.align	2, 0
	.globl	dsum
	.type	 dsum,function
	.thumb_func
dsum:
	push	{lr}
	bl	__adddf3
	bl	g
	pop	{r0}
	bx	r0
.Lfe11:
	.size	 dsum,.Lfe11-dsum
	.align	2, 0
	.globl	dlit
	.type	 dlit,function
	.thumb_func
dlit:
	push	{lr}
	ldr	r3, .L30+0x4		@ created by thumb_load_double_from_address
	ldr	r2, .L30		@ created by thumb_load_double_from_address
	bl	__adddf3
	pop	{r2}
	bx	r2
.L31:
	.align	2, 0
.L30:
	.long 0x3fb99999, 0x9999999a	@ double 1.00000000000000005551e-1
.Lfe12:
	.size	 dlit,.Lfe12-dlit
	.align	2, 0
	.globl	dmem
	.type	 dmem,function
	.thumb_func
dmem:
	push	{lr}
	ldr	r1, [r0, #0x4]		@ created by thumb_load_double_from_address
	ldr	r0, [r0]		@ created by thumb_load_double_from_address
	bl	g
	pop	{r0}
	bx	r0
.Lfe13:
	.size	 dmem,.Lfe13-dmem
	.align	2, 0
	.globl	dkeep
	.type	 dkeep,function
	.thumb_func
dkeep:
	sub	sp, sp, #0x4
	push	{r4, lr}
	add	sp, sp, #-0x4
	str	r3, [sp, #0xc]
	ldr	r3, [sp, #0xc]		@ created by thumb_load_double_from_address
	ldr	r4, [sp, #0x10]		@ created by thumb_load_double_from_address
	str	r4, [sp]
	bl	f4
	add	sp, sp, #0x4
	pop	{r4}
	pop	{r3}
	add	sp, sp, #0x4
	bx	r3
.Lfe14:
	.size	 dkeep,.Lfe14-dkeep
	.align	2, 0
	.globl	lsplit
	.type	 lsplit,function
	.thumb_func
lsplit:
	push	{r4, lr}
	add	sp, sp, #-0x4
	ldr	r4, .L35+0x4		@ created by thumb_load_double_from_address
	ldr	r3, .L35		@ created by thumb_load_double_from_address
	str	r4, [sp]
	mov	r2, #0x7
	bl	l4
	add	sp, sp, #0x4
	pop	{r4}
	pop	{r0}
	bx	r0
.L36:
	.align	2, 0
.L35:
	.word	0x55667788
	.word	0x11223344
.Lfe15:
	.size	 lsplit,.Lfe15-lsplit
	.align	2, 0
	.globl	lstack
	.type	 lstack,function
	.thumb_func
lstack:
	push	{r4, r5, lr}
	add	sp, sp, #-0x8
	add	r2, r0, r1
	sub	r3, r0, r1
	ldr	r5, .L38+0x4		@ created by thumb_load_double_from_address
	ldr	r4, .L38		@ created by thumb_load_double_from_address
	str	r4, [sp]
	str	r5, [sp, #0x4]
	bl	l5
	add	sp, sp, #0x8
	pop	{r4, r5}
	pop	{r0}
	bx	r0
.L39:
	.align	2, 0
.L38:
	.word	0x55667788
	.word	0x11223344
.Lfe16:
	.size	 lstack,.Lfe16-lstack
	.align	2, 0
	.globl	lgap
	.type	 lgap,function
	.thumb_func
lgap:
	push	{lr}
	add	sp, sp, #-0xc
	mov	r2, #0x3
	str	r2, [sp]
	ldr	r3, .L41+0x4		@ created by thumb_load_double_from_address
	ldr	r2, .L41		@ created by thumb_load_double_from_address
	str	r2, [sp, #0x4]
	str	r3, [sp, #0x8]
	mov	r2, #0x1
	mov	r3, #0x2
	bl	l6
	add	sp, sp, #0xc
	pop	{r0}
	bx	r0
.L42:
	.align	2, 0
.L41:
	.word	0x55667788
	.word	0x11223344
.Lfe17:
	.size	 lgap,.Lfe17-lgap
