@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.type	 t.3,object
t.3:
	.ascii	"ab\000"
	.space	1
	.ascii	"c\b\000"
	.space	1
	.ascii	"de\000"
	.space	1
.text
	.align	2, 0
	.globl	k1
	.type	 k1,function
	.thumb_func
k1:
	lsl	r0, r0, #0x2
	ldr	r1, .L3
	add	r0, r0, r1
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	t.3
.Lfe1:
	.size	 k1,.Lfe1-k1
	.section .rodata
	.align	2, 0
	.type	 t.7,object
t.7:
	.byte	0x1
	.ascii	"\f\000"
	.space	1
	.byte	0x2
	.ascii	"x\000"
	.space	1
.text
	.align	2, 0
	.globl	h5
	.type	 h5,function
	.thumb_func
h5:
	ldr	r0, .L6
	bx	lr
.L7:
	.align	2, 0
.L6:
	.word	t.7
.Lfe2:
	.size	 h5,.Lfe2-h5
	.section .rodata
	.align	2, 0
	.type	 s.11,object
	.size	 s.11,7
s.11:
	.ascii	"hello!\000"
.text
	.align	2, 0
	.globl	g1
	.type	 g1,function
	.thumb_func
g1:
	ldr	r1, .L9
	add	r0, r0, r1
	ldrb	r0, [r0]
	bx	lr
.L10:
	.align	2, 0
.L9:
	.word	s.11
.Lfe3:
	.size	 g1,.Lfe3-g1
