@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:

	.lcomm	n.3,4
	.section .rodata
	.type	 t.7,object
	.size	 t.7,4
t.7:
	.byte	0x9
	.byte	0x8
	.byte	0x7
	.byte	0x6
.text
	.align	2, 0
	.globl	A
	.type	 A,function
	.thumb_func
A:
	add	r2, r0, #0
	ldr	r1, .L7
	ldr	r0, [r1]
	add	r0, r0, #0x1
	str	r0, [r1]
	ldr	r1, .L7+0x4
	add	r2, r2, r1
	ldrb	r1, [r2]
	add	r0, r0, r1
	bx	lr
.L8:
	.align	2, 0
.L7:
	.word	n.3
	.word	t.7
.Lfe1:
	.size	 A,.Lfe1-A
	.align	2, 0
	.globl	B
	.type	 B,function
	.thumb_func
B:
	ldr	r1, .L11
	ldr	r0, [r1]
	add	r0, r0, #0x1
	str	r0, [r1]
	bx	lr
.L12:
	.align	2, 0
.L11:
	.word	n.3
.Lfe2:
	.size	 B,.Lfe2-B
