@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	maplesshalf
	.type	 maplesshalf,function
	.thumb_func
maplesshalf:
	ldr	r1, .L2
	ldrh	r0, [r1]
	bx	lr
.L3:
	.align	2, 0
.L2:
	.word	gHalfCell
.Lfe1:
	.size	 maplesshalf,.Lfe1-maplesshalf
