@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	basecell
	.type	 basecell,function
	.thumb_func
basecell:
	ldr	r1, .L4
	ldrb	r1, [r1, #0x3]
	mov	r2, #0x7
	eor	r2, r2, r1
	neg	r1, r2
	orr	r1, r1, r2
	lsr	r1, r1, #0x1f
	str	r1, [r0]
	bx	lr
.L5:
	.align	2, 0
.L4:
	.word	0x3001100
.Lfe1:
	.size	 basecell,.Lfe1-basecell
