@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	spillorder
	.type	 spillorder,function
	.thumb_func
spillorder:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	add	sp, sp, #-0x8
	mov	r2, #0x0
	mov	sl, r2
	cmp	r0, #0
	bne	.L5	@cond_branch
	ldr	r6, [r1]
	str	r6, [sp]
	ldr	r7, [r1, #0x4]
	mov	r9, r7
	ldr	r0, [r1, #0x8]
	mov	r8, r0
	ldr	r2, [r1, #0xc]
	mov	ip, r2
	ldr	r6, [r1, #0x10]
	str	r6, [sp, #0x4]
	ldr	r5, [r1, #0x14]
	ldr	r4, [r1, #0x18]
	ldr	r2, [r1, #0x1c]
	ldr	r0, [r1, #0x20]
	ldr	r3, [r1, #0x24]
	b	.L3
.L5:
	ldr	r7, [r1, #0x28]
	str	r7, [sp]
	ldr	r0, [r1, #0x2c]
	mov	r9, r0
	ldr	r2, [r1, #0x30]
	mov	r8, r2
	ldr	r6, [r1, #0x34]
	mov	ip, r6
	ldr	r7, [r1, #0x38]
	str	r7, [sp, #0x4]
	ldr	r5, [r1, #0x3c]
	ldr	r4, [r1, #0x40]
	ldr	r2, [r1, #0x44]
	ldr	r0, [r1, #0x48]
	ldr	r3, [r1, #0x4c]
.L3:
	mov	r7, r8
	mov	r6, r9
	mul	r6, r6, r7
	mov	r8, r6
	ldr	r7, [sp, #0x4]
	mov	r6, ip
	mul	r6, r6, r7
	mul	r5, r5, r4
	mov	r4, r2
	mul	r4, r4, r0
	mov	r2, #0x7
.L10:
	ldmia	r1!, {r0}
	ldr	r7, [sp]
	mul	r0, r0, r7
	add	r0, r0, r8
	add	r0, r0, r6
	add	r0, r0, r5
	add	r0, r0, r4
	add	r0, r0, r3
	add	sl, sl, r0
	sub	r2, r2, #0x1
	cmp	r2, #0
	bge	.L10	@cond_branch
	mov	r0, sl
	add	sp, sp, #0x8
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 spillorder,.Lfe1-spillorder
