@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	u8spill
	.type	 u8spill,function
	.thumb_func
u8spill:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	add	sp, sp, #-0x10
	str	r2, [sp]
	lsl	r0, r0, #0x18
	lsr	r3, r0, #0x18
	ldr	r0, [r1]
	str	r0, [sp, #0x4]
	ldr	r0, [r1, #0x4]
	ldr	r2, [r1, #0x8]
	mov	ip, r2
	ldr	r2, [r1, #0xc]
	ldr	r4, [r1, #0x10]
	mov	r8, r4
	ldr	r5, [r1, #0x14]
	ldr	r6, [r1, #0x18]
	mov	r9, r6
	ldr	r6, [r1, #0x1c]
	ldr	r4, [r1, #0x20]
	mov	sl, r4
	ldr	r7, [r1, #0x24]
	ldr	r4, [r1, #0x28]
	str	r4, [sp, #0x8]
	ldr	r1, [r1, #0x2c]
	str	r1, [sp, #0xc]
	mov	r4, #0x0
	ldr	r1, [sp]
	cmp	r4, r1
	bge	.L4	@cond_branch
	ldr	r1, [sp, #0x4]
	mul	r0, r0, r1
	mov	r1, ip
	mul	r1, r1, r2
	add	r0, r0, r1
	mov	r1, r8
	mul	r1, r1, r5
	add	r0, r0, r1
	mov	r1, r9
	mul	r1, r1, r6
	add	r0, r0, r1
	mov	r1, sl
	mul	r1, r1, r7
	add	r0, r0, r1
	ldr	r2, [sp]
	ldr	r5, [sp, #0x8]
	ldr	r6, [sp, #0xc]
	mov	r1, r5
	mul	r1, r1, r6
	add	r1, r0, r1
.L6:
	add	r0, r3, #0x1
	lsl	r0, r0, #0x18
	lsr	r3, r0, #0x18
	asr	r0, r0, #0x18
	add	r0, r0, r3
	add	r4, r4, r0
	add	r4, r4, r1
	sub	r2, r2, #0x1
	cmp	r2, #0
	bne	.L6	@cond_branch
.L4:
	add	r0, r4, r3
	add	sp, sp, #0x10
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 u8spill,.Lfe1-u8spill
