@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	mixpoll
	.type	 mixpoll,function
	.thumb_func
mixpoll:
	push	{r4, r5, r6, r7, lr}
	mov	ip, r0
	ldr	r3, .L12
	mov	r1, #0x0
	ldr	r7, .L12+0x4
	ldr	r6, .L12+0x8
	ldr	r5, .L12+0xc
	mov	r4, #0x80
	lsl	r4, r4, #0x18
.L3:
	ldrh	r0, [r7]
	add	r0, r0, #0x1
	strh	r0, [r7]
	ldrh	r0, [r6]
	add	r0, r0, #0x2
	strh	r0, [r6]
	ldrh	r0, [r5]
	add	r0, r0, #0x3
	strh	r0, [r5]
	ldr	r0, .L12+0x10
	str	r0, [r3]
	mov	r2, #0xc0
	lsl	r2, r2, #0x13
	add	r0, r1, r2
	str	r0, [r3, #0x4]
	lsr	r0, r1, #0x1
	orr	r0, r0, r4
	str	r0, [r3, #0x8]
	ldr	r0, [r3, #0x8]
	and	r0, r0, r4
	add	r2, r1, #0x1
	cmp	r0, #0
	beq	.L7	@cond_branch
	mov	r1, #0x80
	lsl	r1, r1, #0x18
.L6:
	ldr	r0, [r3, #0x8]
	and	r0, r0, r1
	cmp	r0, #0
	bne	.L6	@cond_branch
.L7:
	add	r1, r2, #0
	cmp	r1, ip
	blt	.L3	@cond_branch
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L13:
	.align	2, 0
.L12:
	.word	0x40000d4
	.word	0x3001048
	.word	0x3002048
	.word	0x3003048
	.word	0x3004000
.Lfe1:
	.size	 mixpoll,.Lfe1-mixpoll
