@ agbcc 2.9-arm-000512, -O2 -mthumb-interwork -fhex-asm -fprologue-bugfix, from:
@   void g(void); void use(double);
@   double dadd(double a, double b){ return a + b; }
@   double dsub(double a, double b){ return a - b; }
@   double dmul(double a, double b){ return a * b; }
@   double ddiv(double a, double b){ return a / b; }
@   double dneg(double a){ return -a; }
@   double dchain(double a, double b, double c){ return (a + b) * c; }
@   double dkeep(double a, double b){ double x = a + b; g(); return x; }
@   double dconst(double a){ return a + 1.5; }
@   double dld(double *p){ return *p + p[1]; }
@   int dhalf(double a, double b){ double c = a + b; return *(int *)&c; }
@   void dst1(double *p, double a){ *p = -a; }
@   double dsq(double a){ return a * a; }
@   void dpass(double a, double b){ use(a + b); }
@
@ `dchain`'s third argument is past the registers: agbcc loads it from the caller's stack words.
@ `dconst` stages the literal HIGH word first (thumb.h:335 FLOAT_WORDS_BIG_ENDIAN): r2=0x3ff80000.
@ `dhalf` reads the word at the double's lowest address, which is its high word, out of r0.
@ `dsq` passes one argument twice, so each argument register is read by two pairs.
@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	dadd
	.type	 dadd,function
	.thumb_func
dadd:
	push	{lr}
	bl	__adddf3
	pop	{r2}
	bx	r2
.Lfe1:
	.size	 dadd,.Lfe1-dadd
	.align	2, 0
	.globl	dsub
	.type	 dsub,function
	.thumb_func
dsub:
	push	{lr}
	bl	__subdf3
	pop	{r2}
	bx	r2
.Lfe2:
	.size	 dsub,.Lfe2-dsub
	.align	2, 0
	.globl	dmul
	.type	 dmul,function
	.thumb_func
dmul:
	push	{lr}
	bl	__muldf3
	pop	{r2}
	bx	r2
.Lfe3:
	.size	 dmul,.Lfe3-dmul
	.align	2, 0
	.globl	ddiv
	.type	 ddiv,function
	.thumb_func
ddiv:
	push	{lr}
	bl	__divdf3
	pop	{r2}
	bx	r2
.Lfe4:
	.size	 ddiv,.Lfe4-ddiv
	.align	2, 0
	.globl	dneg
	.type	 dneg,function
	.thumb_func
dneg:
	push	{lr}
	bl	__negdf2
	pop	{r2}
	bx	r2
.Lfe5:
	.size	 dneg,.Lfe5-dneg
	.align	2, 0
	.globl	dchain
	.type	 dchain,function
	.thumb_func
dchain:
	push	{r4, r5, lr}
	ldr	r4, [sp, #0xc]		@ created by thumb_load_double_from_address
	ldr	r5, [sp, #0x10]		@ created by thumb_load_double_from_address
	bl	__adddf3
	add	r3, r5, #0
	add	r2, r4, #0
	bl	__muldf3
	pop	{r4, r5}
	pop	{r2}
	bx	r2
.Lfe6:
	.size	 dchain,.Lfe6-dchain
	.align	2, 0
	.globl	dkeep
	.type	 dkeep,function
	.thumb_func
dkeep:
	push	{r4, r5, lr}
	bl	__adddf3
	add	r5, r1, #0
	add	r4, r0, #0
	bl	g
	add	r1, r5, #0
	add	r0, r4, #0
	pop	{r4, r5}
	pop	{r2}
	bx	r2
.Lfe7:
	.size	 dkeep,.Lfe7-dkeep
	.align	2, 0
	.globl	dconst
	.type	 dconst,function
	.thumb_func
dconst:
	push	{lr}
	ldr	r3, .L10+0x4		@ created by thumb_load_double_from_address
	ldr	r2, .L10		@ created by thumb_load_double_from_address
	bl	__adddf3
	pop	{r2}
	bx	r2
.L11:
	.align	2, 0
.L10:
	.long 0x3ff80000, 0x0	@ double 1.50000000000000000000e0
.Lfe8:
	.size	 dconst,.Lfe8-dconst
	.align	2, 0
	.globl	dld
	.type	 dld,function
	.thumb_func
dld:
	push	{lr}
	add	r2, r0, #0
	ldr	r0, [r2]		@ created by thumb_load_double_from_address
	ldr	r1, [r2, #0x4]		@ created by thumb_load_double_from_address
	ldr	r3, [r2, #0xc]		@ created by thumb_load_double_from_address
	ldr	r2, [r2, #0x8]		@ created by thumb_load_double_from_address
	bl	__adddf3
	pop	{r2}
	bx	r2
.Lfe9:
	.size	 dld,.Lfe9-dld
	.align	2, 0
	.globl	dhalf
	.type	 dhalf,function
	.thumb_func
dhalf:
	push	{lr}
	bl	__adddf3
	pop	{r1}
	bx	r1
.Lfe10:
	.size	 dhalf,.Lfe10-dhalf
	.align	2, 0
	.globl	dst1
	.type	 dst1,function
	.thumb_func
dst1:
	push	{r4, lr}
	add	r4, r0, #0
	add	r0, r1, #0
	add	r1, r2, #0
	bl	__negdf2
	str	r0, [r4]
	str	r1, [r4, #0x4]
	pop	{r4}
	pop	{r0}
	bx	r0
.Lfe11:
	.size	 dst1,.Lfe11-dst1
	.align	2, 0
	.globl	dsq
	.type	 dsq,function
	.thumb_func
dsq:
	push	{lr}
	add	r3, r1, #0
	add	r2, r0, #0
	bl	__muldf3
	pop	{r2}
	bx	r2
.Lfe12:
	.size	 dsq,.Lfe12-dsq
	.align	2, 0
	.globl	dpass
	.type	 dpass,function
	.thumb_func
dpass:
	push	{lr}
	bl	__adddf3
	bl	use
	pop	{r0}
	bx	r0
.Lfe13:
	.size	 dpass,.Lfe13-dpass
