@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	extscale
	.type	 extscale,function
	.thumb_func
extscale:
	push	{r4, r5, r6, r7, lr}
	lsl	r0, r0, #0x18
	lsl	r1, r1, #0x18
	mov	r3, #0x80
	lsl	r3, r3, #0x11
	add	r0, r0, r3
	lsr	r6, r0, #0x18
	mov	r3, #0x0
	ldr	r7, .L8
	ldr	r5, .L8+0x4
	lsr	r4, r1, #0xc
.L6:
	ldrh	r1, [r2]
	add	r0, r5, #0
	and	r0, r0, r1
	orr	r0, r0, r4
	strh	r0, [r2]
	add	r2, r2, #0x2
	add	r3, r3, #0x1
	cmp	r3, #0x4
	bls	.L6	@cond_branch
	str	r6, [r7]
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L9:
	.align	2, 0
.L8:
	.word	gB
	.word	0xfff
.Lfe1:
	.size	 extscale,.Lfe1-extscale
