@ GENERATED by scripts/regen-select-spelling-probes.ts — do not hand-edit.
@ source    : packages/core/test/corpus/probe-agbcc-select-merge.c
@ toolchain : ARMV4T_AGBCC (gcc 2.9-arm, Thumb), binary from $ASMLIFT_AGBCC
@ cc flags  : -mthumb-interwork -Wimplicit -O2 -fhex-asm -fprologue-bugfix
@ read by   : packages/core/test/select-spelling.test.ts
@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	selbtn
	.type	 selbtn,function
	.thumb_func
selbtn:
	add	r1, r0, #0
	mov	r0, #0x40
	and	r0, r0, r1
	neg	r0, r0
	lsr	r0, r0, #0x1f
	bx	lr
.Lfe1:
	.size	 selbtn,.Lfe1-selbtn
	.align	2, 0
	.globl	selk53
	.type	 selk53,function
	.thumb_func
selk53:
	mov	r1, #0x3
	cmp	r0, #0
	beq	.L6	@cond_branch
	mov	r1, #0x5
.L6:
	add	r0, r1, #0
	bx	lr
.Lfe2:
	.size	 selk53,.Lfe2-selk53
	.align	2, 0
	.globl	selpool
	.type	 selpool,function
	.thumb_func
selpool:
	ldr	r1, .L11
	cmp	r0, #0
	beq	.L9	@cond_branch
	ldr	r1, .L11+0x4
.L9:
	add	r0, r1, #0
	bx	lr
.L12:
	.align	2, 0
.L11:
	.word	0x7abcdef0
	.word	0x12345678
.Lfe3:
	.size	 selpool,.Lfe3-selpool
	.align	2, 0
	.globl	selcomp
	.type	 selcomp,function
	.thumb_func
selcomp:
	sub	r3, r1, r2
	cmp	r0, #0
	beq	.L14	@cond_branch
	add	r3, r1, r2
.L14:
	add	r0, r3, #0
	bx	lr
.Lfe4:
	.size	 selcomp,.Lfe4-selcomp
	.align	2, 0
	.globl	selbody
	.type	 selbody,function
	.thumb_func
selbody:
	cmp	r0, #0
	beq	.L17	@cond_branch
	mov	r0, #0x1
	str	r0, [r1]
	mov	r0, #0x5
	b	.L18
.L17:
	mov	r0, #0x2
	str	r0, [r1]
	mov	r0, #0x3
.L18:
	bx	lr
.Lfe5:
	.size	 selbody,.Lfe5-selbody
	.align	2, 0
	.globl	selcomp3
	.type	 selcomp3,function
	.thumb_func
selcomp3:
	cmp	r0, #0
	beq	.L20	@cond_branch
	add	r0, r1, r2
	add	r0, r0, #0x7
	b	.L21
.L20:
	sub	r0, r1, r2
	sub	r0, r0, #0x7
.L21:
	bx	lr
.Lfe6:
	.size	 selcomp3,.Lfe6-selcomp3
	.align	2, 0
	.globl	selload
	.type	 selload,function
	.thumb_func
selload:
	cmp	r0, #0
	beq	.L23	@cond_branch
	ldr	r0, [r1]
	b	.L24
.L23:
	ldr	r0, [r2]
.L24:
	bx	lr
.Lfe7:
	.size	 selload,.Lfe7-selload
