@ GENERATED by scripts/regen-flag-pair-probes.ts — do not hand-edit.
@ source    : packages/core/test/corpus/probe-agbcc-hoist.c
@ toolchain : ARMV4T_AGBCC (gcc 2.9-arm, Thumb), binary from $ASMLIFT_AGBCC
@ cc flags  : -Wimplicit -mthumb-interwork -O2 -fhex-asm -fprologue-bugfix
@ read by   : packages/core/test/hoist-level-probes.test.ts
@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	f
	.type	 f,function
	.thumb_func
f:
	push	{lr}
	cmp	r0, #0
	beq	.L3	@cond_branch
	ldr	r0, .L5
	ldr	r0, [r0]
	ldrb	r0, [r0]
	bl	A
	b	.L4
.L6:
	.align	2, 0
.L5:
	.word	gp
.L3:
	ldr	r0, .L7
	ldr	r0, [r0]
	ldrb	r0, [r0]
	bl	B
.L4:
	pop	{r0}
	bx	r0
.L8:
	.align	2, 0
.L7:
	.word	gp
.Lfe1:
	.size	 f,.Lfe1-f
