@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	AdvanceSprites
	.type	 AdvanceSprites,function
	.thumb_func
AdvanceSprites:
	push	{r4, r5, r6, lr}
	add	r5, r2, #0
	mov	r6, #0x0
	cmp	r1, #0
	beq	.L3	@cond_branch
	add	r4, r1, #0
	add	r3, r0, #0
.L4:
	ldrb	r0, [r3, #0xc]
	ldrb	r1, [r3, #0xe]
	cmp	r0, #0
	beq	.L7	@cond_branch
	cmp	r1, #0x1
	bhi	.L7	@cond_branch
	ldr	r0, [r3]
	add	r0, r0, r5
	str	r0, [r3]
	add	r0, r5, #0
	cmp	r0, #0
	bge	.L8	@cond_branch
	add	r0, r0, #0x7
.L8:
	asr	r0, r0, #0x3
	ldr	r1, [r3, #0x4]
	add	r1, r1, r0
	str	r1, [r3, #0x4]
	ldrb	r1, [r3, #0xd]
	add	r0, r1, #0x1
	mov	r2, #0x0
	strb	r0, [r3, #0xd]
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	cmp	r0, #0xb
	bls	.L9	@cond_branch
	add	r0, r1, #0
	sub	r0, r0, #0xb
	strb	r0, [r3, #0xd]
	ldrb	r0, [r3, #0xf]
	mov	r1, #0x2
	orr	r0, r0, r1
	strb	r0, [r3, #0xf]
.L9:
	add	r6, r6, #0x1
	b	.L10
.L7:
	sub	r0, r1, #0x1
	strb	r0, [r3, #0xe]
.L10:
	add	r3, r3, #0x10
	sub	r4, r4, #0x1
	cmp	r4, #0
	bne	.L4	@cond_branch
.L3:
	add	r0, r6, #0
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 AdvanceSprites,.Lfe1-AdvanceSprites
