@ agbcc 2.9-arm-000512, -O2 -mthumb-interwork -fhex-asm -fprologue-bugfix, from:
@   void fuse(float);
@   float fadd(float a, float b){ return a + b; }
@   float fchain(float a, float b, float c){ return (a + b) * c; }
@   float fneg(float a){ return -a; }
@   void fpass(float a, float b){ fuse(a + b); }
@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	fadd
	.type	 fadd,function
	.thumb_func
fadd:
	push	{lr}
	bl	__addsf3
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 fadd,.Lfe1-fadd
	.align	2, 0
	.globl	fchain
	.type	 fchain,function
	.thumb_func
fchain:
	push	{r4, lr}
	add	r4, r2, #0
	bl	__addsf3
	add	r1, r4, #0
	bl	__mulsf3
	pop	{r4}
	pop	{r1}
	bx	r1
.Lfe2:
	.size	 fchain,.Lfe2-fchain
	.align	2, 0
	.globl	fneg
	.type	 fneg,function
	.thumb_func
fneg:
	push	{lr}
	bl	__negsf2
	pop	{r1}
	bx	r1
.Lfe3:
	.size	 fneg,.Lfe3-fneg
	.align	2, 0
	.globl	fpass
	.type	 fpass,function
	.thumb_func
fpass:
	push	{lr}
	bl	__addsf3
	bl	fuse
	pop	{r0}
	bx	r0
.Lfe4:
	.size	 fpass,.Lfe4-fpass
