@ GENERATED by scripts/regen-switch-spelling-probes.ts — do not hand-edit.
@ source    : packages/core/test/corpus/probe-agbcc-swnested.c
@ toolchain : ARMV4T_AGBCC (gcc 2.9-arm, Thumb), binary from $ASMLIFT_AGBCC
@ cc flags  : -mthumb-interwork -Wimplicit -O2 -fhex-asm -fprologue-bugfix
@ read by   : packages/core/test/switch-arms.test.ts
@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	f
	.type	 f,function
	.thumb_func
f:
	cmp	r0, #0x63
	beq	.L8	@cond_branch
	cmp	r0, #0x62
	bne	.L5	@cond_branch
	mov	r0, #0x9
	str	r0, [r1, #0x14]
	b	.L4
.L5:
	cmp	r0, #0x7
	beq	.L9	@cond_branch
	cmp	r0, #0x7
	bgt	.L14	@cond_branch
	cmp	r0, #0x6
	beq	.L8	@cond_branch
	b	.L4
.L14:
	cmp	r0, #0x8
	beq	.L10	@cond_branch
	cmp	r0, #0x9
	beq	.L11	@cond_branch
	b	.L4
.L8:
	mov	r0, #0x1
	str	r0, [r1]
	mov	r0, #0x2
	str	r0, [r1, #0x4]
	mov	r0, #0x3
	str	r0, [r1, #0x8]
	mov	r0, #0x4
	str	r0, [r1, #0xc]
	b	.L4
.L9:
	mov	r0, #0x5
	b	.L15
.L10:
	mov	r0, #0x6
	b	.L15
.L11:
	mov	r0, #0x7
.L15:
	str	r0, [r1, #0x4]
.L4:
	bx	lr
.Lfe1:
	.size	 f,.Lfe1-f
