@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	scopecoalesce
	.type	 scopecoalesce,function
	.thumb_func
scopecoalesce:
	push	{r4, r5, r6, lr}
	add	r3, r1, #0
	cmp	r0, #0
	beq	.L3	@cond_branch
	ldr	r1, .L14
	ldr	r2, .L14+0x4
	add	r0, r1, r2
	strh	r3, [r0]
	ldr	r0, .L14+0x8
	add	r2, r1, r0
	add	r0, r3, #0x1
	strh	r0, [r2]
	ldr	r2, .L14+0xc
	add	r1, r1, r2
	add	r0, r3, #0x2
	strh	r0, [r1]
.L3:
	mov	r2, #0x0
	ldr	r4, .L14+0x10
	ldrh	r0, [r4]
	cmp	r2, r0
	bcs	.L5	@cond_branch
	ldr	r6, .L14+0x14
	ldr	r5, .L14+0x18
.L7:
	add	r0, r2, r6
	add	r1, r2, r5
	ldrb	r1, [r1]
	strb	r1, [r0]
	add	r2, r2, #0x1
	ldrh	r0, [r4]
	cmp	r2, r0
	bcc	.L7	@cond_branch
.L5:
	ldr	r0, .L14+0x10
	ldrh	r2, [r0]
	mov	r0, #0x10
	lsl	r0, r0, r3
	cmp	r2, r0
	bcs	.L10	@cond_branch
	ldr	r4, .L14+0x14
	mov	r3, #0x0
	add	r1, r0, #0
.L12:
	add	r0, r2, r4
	strb	r3, [r0]
	add	r2, r2, #0x1
	cmp	r2, r1
	bcc	.L12	@cond_branch
.L10:
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.L15:
	.align	2, 0
.L14:
	.word	gBgTilemapBufs
	.word	0x4a4
	.word	0x4e4
	.word	0x524
	.word	0x3001048
	.word	0x3002000
	.word	0x3003000
.Lfe1:
	.size	 scopecoalesce,.Lfe1-scopecoalesce
