@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	entrylookup
	.type	 entrylookup,function
	.thumb_func
entrylookup:
	lsl	r0, r0, #0x18
	ldr	r2, .L3
	ldr	r1, .L3+0x4
	lsr	r0, r0, #0x15
	add	r0, r0, r1
	ldrb	r1, [r0, #0x5]
	strb	r1, [r2, #0x11]
	ldrb	r0, [r0, #0x6]
	strb	r0, [r2, #0x12]
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	gFlags
	.word	gTable
.Lfe1:
	.size	 entrylookup,.Lfe1-entrylookup
