@ GENERATED by scripts/regen-select-spelling-probes.ts — do not hand-edit.
@ source    : packages/core/test/corpus/probe-agbcc-select-merge.c
@ toolchain : ARMV4T_AGBCC (gcc 2.9-arm, Thumb), binary from $ASMLIFT_AGBCC
@ cc flags  : -mthumb-interwork -Wimplicit -O2 -fhex-asm -fprologue-bugfix
@ read by   : packages/core/test/select-spelling.test.ts
@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	selbtn
	.type	 selbtn,function
	.thumb_func
selbtn:
	add	r1, r0, #0
	mov	r0, #0x40
	and	r0, r0, r1
	neg	r0, r0
	lsr	r0, r0, #0x1f
	bx	lr
.Lfe1:
	.size	 selbtn,.Lfe1-selbtn
	.align	2, 0
	.globl	selk53
	.type	 selk53,function
	.thumb_func
selk53:
	mov	r1, #0x3
	cmp	r0, #0
	beq	.L6	@cond_branch
	mov	r1, #0x5
.L6:
	add	r0, r1, #0
	bx	lr
.Lfe2:
	.size	 selk53,.Lfe2-selk53
	.align	2, 0
	.globl	selpool
	.type	 selpool,function
	.thumb_func
selpool:
	ldr	r1, .L11
	cmp	r0, #0
	beq	.L9	@cond_branch
	ldr	r1, .L11+0x4
.L9:
	add	r0, r1, #0
	bx	lr
.L12:
	.align	2, 0
.L11:
	.word	0x7abcdef0
	.word	0x12345678
.Lfe3:
	.size	 selpool,.Lfe3-selpool
	.align	2, 0
	.globl	selbody
	.type	 selbody,function
	.thumb_func
selbody:
	cmp	r0, #0
	beq	.L14	@cond_branch
	mov	r0, #0x1
	str	r0, [r1]
	mov	r0, #0x5
	b	.L15
.L14:
	mov	r0, #0x2
	str	r0, [r1]
	mov	r0, #0x3
.L15:
	bx	lr
.Lfe4:
	.size	 selbody,.Lfe4-selbody
