@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	dmascope
	.type	 dmascope,function
	.thumb_func
dmascope:
	push	{r4, r5, lr}
	add	r4, r0, #0
	mov	r3, #0x0
	cmp	r3, r4
	bge	.L4	@cond_branch
	ldr	r2, .L11
.L6:
	lsl	r1, r3, #0x2
	ldr	r5, .L11+0x4
	add	r0, r1, r5
	ldr	r0, [r0]
	cmp	r0, #0
	beq	.L7	@cond_branch
	str	r0, [r2]
	add	r5, r5, #0x4
	add	r0, r1, r5
	ldr	r0, [r0]
	str	r0, [r2, #0x4]
	ldr	r0, .L11+0x8
	b	.L10
.L12:
	.align	2, 0
.L11:
	.word	0x40000d4
	.word	0x3001000
	.word	-0x7fffffe0
.L7:
	ldr	r5, .L13
	add	r0, r1, r5
	ldr	r0, [r0]
	str	r0, [r2]
	add	r5, r5, #0x4
	add	r0, r1, r5
	ldr	r0, [r0]
	str	r0, [r2, #0x4]
	ldr	r0, .L13+0x4
.L10:
	str	r0, [r2, #0x8]
	add	r3, r3, #0x1
	cmp	r3, r4
	blt	.L6	@cond_branch
.L4:
	ldr	r1, .L13+0x8
	ldr	r0, .L13+0xc
	ldr	r0, [r0]
	str	r0, [r1]
	ldr	r0, .L13+0x10
	ldr	r0, [r0]
	str	r0, [r1, #0x4]
	ldr	r0, .L13+0x14
	str	r0, [r1, #0x8]
	pop	{r4, r5}
	pop	{r0}
	bx	r0
.L14:
	.align	2, 0
.L13:
	.word	0x3001008
	.word	-0x7fffffc0
	.word	0x40000d4
	.word	0x3001000
	.word	0x3001004
	.word	-0x7fffff80
.Lfe1:
	.size	 dmascope,.Lfe1-dmascope
.text
	.align	2, 0
