@ GENERATED by scripts/regen-outgoing-area-probes.ts — do not hand-edit.
@ source    : packages/core/test/corpus/probe-agbcc-restage.c
@ toolchain : ARMV4T_AGBCC (gcc 2.9-arm, Thumb), binary from $ASMLIFT_AGBCC
@ cc flags  : -Wimplicit -mthumb-interwork -O2 -fhex-asm -fprologue-bugfix
@ read by   : packages/core/test/outgoing-area-probes.test.ts
@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	twice
	.type	 twice,function
	.thumb_func
twice:
	push	{r4, r5, lr}
	add	sp, sp, #-0x4
	mov	r5, r0
	mul	r5, r5, r1
	str	r5, [sp]
	mov	r0, #0x1
	mov	r1, #0x2
	mov	r2, #0x3
	mov	r3, #0x4
	bl	five
	add	r4, r0, #0
	str	r5, [sp]
	mov	r0, #0x1
	mov	r1, #0x2
	mov	r2, #0x3
	mov	r3, #0x4
	bl	five
	add	r4, r4, r0
	add	r0, r4, #0
	add	sp, sp, #0x4
	pop	{r4, r5}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 twice,.Lfe1-twice
	.align	2, 0
	.globl	owns
	.type	 owns,function
	.thumb_func
owns:
	push	{lr}
	ldr	r1, [sp, #0x4]
	add	r1, r1, r0
	str	r1, [sp, #0x4]
	add	r0, sp, #0x4
	bl	use
	ldr	r0, [sp, #0x4]
	pop	{r1}
	bx	r1
.Lfe2:
	.size	 owns,.Lfe2-owns
