@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	deref
	.type	 deref,function
	.thumb_func
deref:
	ldr	r0, [r0]
	bx	lr
.Lfe1:
	.size	 deref,.Lfe1-deref
