@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	foldsink
	.type	 foldsink,function
	.thumb_func
foldsink:
	mov	r3, r0
	mul	r3, r3, r1
	str	r3, [r2]
	add	r0, r0, r1
	str	r0, [r2, #0x4]
	ldr	r0, .L4
	ldrb	r0, [r0, #0x3]
	mov	r1, #0x7
	eor	r1, r1, r0
	neg	r0, r1
	orr	r0, r0, r1
	lsr	r0, r0, #0x1f
	str	r0, [r2, #0x8]
	bx	lr
.L5:
	.align	2, 0
.L4:
	.word	0x3001100
.Lfe1:
	.size	 foldsink,.Lfe1-foldsink
