@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	uninit_spill
	.type	 uninit_spill,function
	.thumb_func
uninit_spill:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	add	sp, sp, #-0xc
	mov	r6, #0x0
	mov	sl, r6
	cmp	r0, #0
	beq	.L4	@cond_branch
	cmp	r0, #0x1
	beq	.L5	@cond_branch
	b	.L3
.L4:
	ldr	r7, [r1]
	mov	ip, r7
	ldr	r0, [r1, #0x4]
	str	r0, [sp]
	ldr	r6, [r1, #0x8]
	str	r6, [sp, #0x4]
	ldr	r7, [r1, #0xc]
	mov	r9, r7
	ldr	r0, [r1, #0x10]
	str	r0, [sp, #0x8]
	ldr	r6, [r1, #0x14]
	mov	r8, r6
	ldr	r5, [r1, #0x18]
	ldr	r4, [r1, #0x1c]
	ldr	r2, [r1, #0x20]
	ldr	r3, [r1, #0x24]
	b	.L3
.L5:
	ldr	r7, [r1, #0x28]
	mov	ip, r7
	ldr	r0, [r1, #0x2c]
	str	r0, [sp]
	ldr	r6, [r1, #0x30]
	str	r6, [sp, #0x4]
	ldr	r7, [r1, #0x34]
	mov	r9, r7
	ldr	r0, [r1, #0x38]
	str	r0, [sp, #0x8]
	ldr	r6, [r1, #0x3c]
	mov	r8, r6
	ldr	r5, [r1, #0x40]
	ldr	r4, [r1, #0x44]
	ldr	r2, [r1, #0x48]
	ldr	r3, [r1, #0x4c]
.L3:
	ldr	r0, [sp]
	ldr	r6, [sp, #0x4]
	mov	r7, r0
	mul	r7, r7, r6
	str	r7, [sp, #0x4]
	ldr	r7, [sp, #0x8]
	mov	r6, r9
	mul	r6, r6, r7
	mov	r0, r8
	mul	r0, r0, r5
	add	r5, r0, #0
	mul	r4, r4, r2
	mov	r2, #0x7
.L11:
	ldmia	r1!, {r0}
	mov	r7, ip
	mul	r7, r7, r0
	add	r0, r7, #0
	ldr	r7, [sp, #0x4]
	add	r0, r0, r7
	add	r0, r0, r6
	add	r0, r0, r5
	add	r0, r0, r4
	add	r0, r0, r3
	add	sl, sl, r0
	sub	r2, r2, #0x1
	cmp	r2, #0
	bge	.L11	@cond_branch
	mov	r0, sl
	add	sp, sp, #0xc
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 uninit_spill,.Lfe1-uninit_spill
