@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	sizebound
	.type	 sizebound,function
	.thumb_func
sizebound:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	mov	sl, r1
	ldr	r5, .L23
	mov	r6, #0x10
	lsl	r6, r6, r0
	mov	r0, #0x0
	cmp	r0, sl
	bge	.L4	@cond_branch
	ldr	r1, .L23+0x4
	mov	ip, r1
	lsr	r2, r6, #0x1
	mov	r1, #0x80
	lsl	r1, r1, #0x18
	orr	r2, r2, r1
	mov	r8, r2
.L6:
	mov	r2, #0x0
	mov	r7, r6
	mul	r7, r7, r0
	add	r0, r0, #0x1
	mov	r9, r0
	mov	r0, ip
	ldrh	r0, [r0]
	cmp	r2, r0
	bcs	.L8	@cond_branch
	ldr	r4, .L23+0x8
	ldr	r3, .L23+0xc
.L10:
	add	r0, r2, r4
	add	r1, r2, r3
	ldrb	r1, [r1]
	strb	r1, [r0]
	add	r2, r2, #0x1
	mov	r1, ip
	ldrh	r1, [r1]
	cmp	r2, r1
	bcc	.L10	@cond_branch
.L8:
	mov	r0, ip
	ldrh	r2, [r0]
	cmp	r2, r6
	bcs	.L13	@cond_branch
	ldr	r3, .L23+0x8
	mov	r1, #0x0
.L15:
	add	r0, r2, r3
	strb	r1, [r0]
	add	r2, r2, #0x1
	cmp	r2, r6
	bcc	.L15	@cond_branch
.L13:
	ldr	r0, .L23+0x8
	str	r0, [r5]
	ldr	r1, .L23+0x10
	ldr	r0, [r1]
	add	r0, r0, r7
	str	r0, [r5, #0x4]
	mov	r2, r8
	str	r2, [r5, #0x8]
	ldr	r0, [r5, #0x8]
	mov	r1, #0x80
	lsl	r1, r1, #0x18
	b	.L22
.L24:
	.align	2, 0
.L23:
	.word	0x40000d4
	.word	0x3001048
	.word	0x3002000
	.word	0x3003000
	.word	0x3001070
.L17:
	ldr	r0, [r5, #0x8]
.L22:
	and	r0, r0, r1
	cmp	r0, #0
	bne	.L17	@cond_branch
	mov	r0, r9
	cmp	r0, sl
	blt	.L6	@cond_branch
.L4:
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 sizebound,.Lfe1-sizebound
