@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	retflat
	.type	 retflat,function
	.thumb_func
retflat:
	ldr	r0, .L3
	mov	r1, #0x3
	str	r1, [r0]
.L2:
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	0x3003440
.Lfe1:
	.size	 retflat,.Lfe1-retflat
	.align	2, 0
	.globl	retearly
	.type	 retearly,function
	.thumb_func
retearly:
	ldr	r0, .L7
	ldrb	r1, [r0]
	mov	r2, #0x1
	add	r0, r1, #0
	and	r0, r0, r2
	add	r2, r0, #0
	lsl	r1, r2, #0x18
	lsr	r0, r1, #0x18
	cmp	r0, #0
	beq	.L6	@cond_branch
	b	.L5
.L8:
	.align	2, 0
.L7:
	.word	0x3003430
.L6:
	ldr	r0, .L9
	mov	r1, #0x3
	str	r1, [r0]
.L5:
	bx	lr
.L10:
	.align	2, 0
.L9:
	.word	0x3003440
.Lfe2:
	.size	 retearly,.Lfe2-retearly
	.align	2, 0
	.globl	retjoin
	.type	 retjoin,function
	.thumb_func
retjoin:
	ldr	r0, .L25
	ldrb	r1, [r0]
	cmp	r1, #0
	beq	.L23	@cond_branch
	ldr	r0, .L25+0x4
	mov	r1, #0x3
	str	r1, [r0]
	b	.L24
.L26:
	.align	2, 0
.L25:
	.word	0x3003430
	.word	0x3003440
.L23:
	ldr	r0, .L27
	mov	r1, #0x4
	str	r1, [r0]
.L24:
.L22:
	bx	lr
.L28:
	.align	2, 0
.L27:
	.word	0x3003444
.Lfe3:
	.size	 retjoin,.Lfe3-retjoin
