@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	f
	.type	 f,function
	.thumb_func
f:
	push	{r4, r5, lr}
	add	r4, r0, #0
	mov	r2, #0x0
	mov	r3, #0x0
	ldr	r5, .L9
	cmp	r2, r4
	bcs	.L4	@cond_branch
	ldr	r0, .L9+0x4
	add	r1, r1, r0
.L6:
	ldrb	r0, [r1]
	add	r2, r2, r0
	add	r1, r1, #0x1
	add	r3, r3, #0x1
	cmp	r3, r4
	bcc	.L6	@cond_branch
.L4:
	add	r1, r5, #0
	lsl	r0, r2, #0x1
	add	r0, r0, r2
	str	r0, [r1]
	mov	r0, #0x1
	and	r0, r0, r2
	cmp	r0, #0
	beq	.L8	@cond_branch
	add	r0, r2, #0x5
	str	r0, [r1]
.L8:
	ldr	r0, [r5]
	add	r0, r0, r2
	pop	{r4, r5}
	pop	{r1}
	bx	r1
.L10:
	.align	2, 0
.L9:
	.word	gCounter
	.word	gTab
.Lfe1:
	.size	 f,.Lfe1-f
