@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	gcd
	.type	 gcd,function
	.thumb_func
gcd:
	push	{r4, lr}
	add	r2, r0, #0
	add	r0, r1, #0
	cmp	r0, #0
	beq	.L4	@cond_branch
.L5:
	add	r4, r0, #0
	add	r0, r2, #0
	add	r1, r4, #0
	bl	__modsi3
	add	r2, r4, #0
	cmp	r0, #0
	bne	.L5	@cond_branch
.L4:
	add	r0, r2, #0
	pop	{r4}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 gcd,.Lfe1-gcd
