@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	extscale
	.type	 extscale,function
	.thumb_func
extscale:
	push	{r4, lr}
	lsl	r1, r1, #0x18
	lsr	r1, r1, #0x18
	ldr	r4, .L3
	ldr	r2, [r4]
	mov	r3, #0x4
	orr	r2, r2, r3
	str	r2, [r4]
	ldr	r3, .L3+0x4
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x16
	ldr	r2, .L3+0x8
	add	r0, r0, r2
	str	r0, [r3]
	ldr	r0, .L3+0xc
	str	r1, [r0]
	pop	{r4}
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	gA
	.word	gB
	.word	gT
	.word	gC
.Lfe1:
	.size	 extscale,.Lfe1-extscale
