@ GENERATED by scripts/regen-switch-spelling-probes.ts — do not hand-edit.
@ source    : packages/core/test/corpus/probe-agbcc-swpathbound.c
@ toolchain : ARMV4T_AGBCC (gcc 2.9-arm, Thumb), binary from $ASMLIFT_AGBCC
@ cc flags  : -Wimplicit -mthumb-interwork -O2 -fhex-asm -fprologue-bugfix
@ read by   : packages/core/test/switch-arms.test.ts
@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	h
	.type	 h,function
	.thumb_func
h:
	add	r1, r0, #0
	cmp	r1, #0x4
	beq	.L7	@cond_branch
	cmp	r1, #0x4
	bgt	.L13	@cond_branch
	cmp	r1, #0x2
	beq	.L5	@cond_branch
	cmp	r1, #0x2
	bgt	.L6	@cond_branch
	cmp	r1, #0x1
	beq	.L4	@cond_branch
	b	.L11
.L13:
	mov	r0, #0xfa
	lsl	r0, r0, #0x2
	cmp	r1, r0
	beq	.L9	@cond_branch
	cmp	r1, r0
	bgt	.L14	@cond_branch
	cmp	r1, #0x5
	beq	.L8	@cond_branch
	b	.L11
.L14:
	mov	r0, #0xfa
	lsl	r0, r0, #0x3
	cmp	r1, r0
	beq	.L10	@cond_branch
	b	.L11
.L4:
	mov	r0, #0xa
	b	.L15
.L5:
	mov	r0, #0x14
	b	.L15
.L6:
	mov	r0, #0x1e
	b	.L15
.L7:
	mov	r0, #0x28
	b	.L15
.L8:
	mov	r0, #0x32
	b	.L15
.L9:
	mov	r0, #0x3c
	b	.L15
.L10:
	mov	r0, #0x46
	b	.L15
.L11:
	mov	r0, #0x1
	neg	r0, r0
.L15:
	bx	lr
.Lfe1:
	.size	 h,.Lfe1-h
