@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	sub_803213C
	.type	 sub_803213C,function
	.thumb_func
sub_803213C:
	push	{r4, r5, r6, lr}
	add	r4, r2, #0
	lsl	r0, r0, #0x18
	lsr	r2, r0, #0x18
	lsl	r1, r1, #0x18
	lsr	r1, r1, #0x18
	mov	r6, #0x1
	and	r1, r1, r6
	neg	r0, r1
	orr	r0, r0, r1
	asr	r5, r0, #0x1f
	mov	r0, #0x80
	lsl	r0, r0, #0x3
	and	r5, r5, r0
	ldr	r0, .L9
	ldrb	r0, [r0, #0x3]
	cmp	r0, #0x7
	beq	.L5	@cond_branch
	cmp	r2, #0
	beq	.L6	@cond_branch
	mov	r0, #0x14
	bl	VramMalloc
	str	r0, [r4]
	mov	r1, #0x0
	ldr	r0, .L9+0x4
	strh	r0, [r4, #0xc]
	strb	r1, [r4, #0x1a]
	b	.L8
.L10:
	.align	2, 0
.L9:
	.word	gStageData
	.word	0x366
.L6:
	mov	r0, #0xf
	bl	VramMalloc
	str	r0, [r4]
	ldr	r0, .L11
	strh	r0, [r4, #0xc]
	strb	r6, [r4, #0x1a]
	b	.L8
.L12:
	.align	2, 0
.L11:
	.word	0x366
.L5:
	mov	r0, #0xf
	bl	VramMalloc
	str	r0, [r4]
	ldr	r0, .L13
	strh	r0, [r4, #0xc]
	strb	r6, [r4, #0x1a]
	mov	r0, #0x80
	lsl	r0, r0, #0x2
	orr	r5, r5, r0
.L8:
	mov	r2, #0x0
	mov	r1, #0x0
	mov	r0, #0xc0
	lsl	r0, r0, #0x3
	strh	r0, [r4, #0x14]
	strh	r1, [r4, #0xe]
	strh	r1, [r4, #0x16]
	mov	r0, #0xff
	strb	r0, [r4, #0x1b]
	mov	r0, #0x10
	strb	r0, [r4, #0x1c]
	strb	r2, [r4, #0x1f]
	sub	r0, r0, #0x11
	str	r0, [r4, #0x20]
	mov	r0, #0x80
	lsl	r0, r0, #0x5
	orr	r5, r5, r0
	str	r5, [r4, #0x8]
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
.L14:
	.align	2, 0
.L13:
	.word	0x366
.Lfe1:
	.size	 sub_803213C,.Lfe1-sub_803213C
	.comm	gUnknown_03001150, 1136	@ 1136

.text
	.align	2, 0
