@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	dmapoll
	.type	 dmapoll,function
	.thumb_func
dmapoll:
	push	{r4, r5, r6, r7, lr}
	add	r7, r0, #0
	ldr	r2, .L10
	mov	r3, #0x0
	ldr	r6, .L10+0x4
	ldr	r5, .L10+0x8
	ldr	r1, .L10+0xc
	ldr	r4, .L10+0x10
.L3:
	ldrh	r0, [r6]
	add	r0, r0, #0x1
	strh	r0, [r6]
	ldrh	r0, [r5]
	add	r0, r0, #0x2
	strh	r0, [r5]
	ldr	r0, [r2]
	cmp	r0, #0
	beq	.L6	@cond_branch
	ldr	r0, [r2, #0x4]
	str	r0, [r1]
	ldr	r0, [r2, #0x8]
	str	r0, [r1, #0x4]
	ldr	r0, .L10+0x14
	str	r0, [r1, #0x8]
	b	.L7
.L11:
	.align	2, 0
.L10:
	.word	0x3004000
	.word	0x3001048
	.word	0x3002048
	.word	0x40000d4
	.word	0x3003048
	.word	-0x7fffffe0
.L6:
	ldr	r0, [r2, #0x8]
	str	r0, [r1]
	ldr	r0, [r2, #0xc]
	str	r0, [r1, #0x4]
	ldr	r0, .L12
	str	r0, [r1, #0x8]
	ldrh	r0, [r4]
	add	r0, r0, #0x3
	strh	r0, [r4]
.L7:
	add	r3, r3, #0x1
	cmp	r3, r7
	blt	.L3	@cond_branch
	ldr	r1, .L12+0x4
	ldr	r0, [r2, #0x10]
	str	r0, [r1]
	ldr	r0, [r2, #0x14]
	str	r0, [r1, #0x4]
	ldr	r0, .L12+0x8
	str	r0, [r1, #0x8]
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L13:
	.align	2, 0
.L12:
	.word	-0x7fffffc0
	.word	0x40000d4
	.word	-0x7fffff80
.Lfe1:
	.size	 dmapoll,.Lfe1-dmapoll
