@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	clamp0
	.type	 clamp0,function
	.thumb_func
clamp0:
	cmp	r0, #0
	bge	.L4	@cond_branch
	mov	r0, #0x0
.L4:
	bx	lr
.Lfe1:
	.size	 clamp0,.Lfe1-clamp0
