@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.type	 tide.3,object
tide.3:
	.byte	0x1
	.byte	0x2
	.byte	0x3
.text
	.align	2, 0
	.globl	fa
	.type	 fa,function
	.thumb_func
fa:
	ldr	r1, .L3
	add	r0, r0, r1
	ldrb	r0, [r0]
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	tide.3
.Lfe1:
	.size	 fa,.Lfe1-fa
	.section .rodata
	.align	1, 0
	.type	 cs.7,object
	.size	 cs.7,6
cs.7:
	.short	-0x1
	.short	0x2
	.short	0x3
.text
	.align	2, 0
	.globl	fb
	.type	 fb,function
	.thumb_func
fb:
	ldr	r1, .L6
	lsl	r0, r0, #0x1
	add	r0, r0, r1
	mov	r1, #0x0
	ldrsh	r0, [r0, r1]
	bx	lr
.L7:
	.align	2, 0
.L6:
	.word	cs.7
.Lfe2:
	.size	 fb,.Lfe2-fb

	.lcomm	z.11,3
	.align	2, 0
	.globl	fc
	.type	 fc,function
	.thumb_func
fc:
	ldr	r2, .L9
	add	r0, r0, r2
	mov	r1, #0x1
	strb	r1, [r0]
	ldrb	r0, [r2]
	bx	lr
.L10:
	.align	2, 0
.L9:
	.word	z.11
.Lfe3:
	.size	 fc,.Lfe3-fc
.data
	.align	2, 0
	.type	 q.15,object
	.size	 q.15,4
q.15:
	.word	0x0
.text
	.align	2, 0
	.globl	fd
	.type	 fd,function
	.thumb_func
fd:
	ldr	r1, .L12
	ldr	r2, [r1]
	add	r0, r2, #0
	add	r2, r2, #0x1
	str	r2, [r1]
	bx	lr
.L13:
	.align	2, 0
.L12:
	.word	q.15
.Lfe4:
	.size	 fd,.Lfe4-fd
	.section .rodata
	.align	2, 0
	.type	 w.19,object
	.size	 w.19,8
w.19:
	.word	-0x80000000
	.word	0x5
.text
	.align	2, 0
	.globl	fe
	.type	 fe,function
	.thumb_func
fe:
	ldr	r1, .L15
	lsl	r0, r0, #0x2
	add	r0, r0, r1
	ldr	r0, [r0]
	bx	lr
.L16:
	.align	2, 0
.L15:
	.word	w.19
.Lfe5:
	.size	 fe,.Lfe5-fe
.data
	.align	2, 0
	.type	 s.23,object
	.size	 s.23,8
s.23:
	.word	.LC5
	.word	.LC6
	.section .rodata
	.align	2, 0
.LC6:
	.ascii	"cd\000"
	.align	2, 0
.LC5:
	.ascii	"ab\000"
.text
	.align	2, 0
	.globl	ff
	.type	 ff,function
	.thumb_func
ff:
	ldr	r1, .L18
	lsl	r0, r0, #0x2
	add	r0, r0, r1
	ldr	r0, [r0]
	ldrb	r0, [r0]
	bx	lr
.L19:
	.align	2, 0
.L18:
	.word	s.23
.Lfe6:
	.size	 ff,.Lfe6-ff
.data
	.align	2, 0
	.type	 p.27,object
	.size	 p.27,4
p.27:
	.word	g
.text
	.align	2, 0
	.globl	fg
	.type	 fg,function
	.thumb_func
fg:
	ldr	r1, .L21
	ldr	r1, [r1]
	lsl	r0, r0, #0x2
	add	r0, r0, r1
	ldr	r0, [r0]
	bx	lr
.L22:
	.align	2, 0
.L21:
	.word	p.27
.Lfe7:
	.size	 fg,.Lfe7-fg
	.section .rodata
	.align	2, 0
	.type	 str.31,object
	.size	 str.31,6
str.31:
	.ascii	"hello\000"
.text
	.align	2, 0
	.globl	fh
	.type	 fh,function
	.thumb_func
fh:
	ldr	r1, .L24
	add	r0, r0, r1
	ldrb	r0, [r0]
	bx	lr
.L25:
	.align	2, 0
.L24:
	.word	str.31
.Lfe8:
	.size	 fh,.Lfe8-fh
.data
	.align	2, 0
	.type	 st.35,object
	.size	 st.35,8
st.35:
	.byte	0x1
	.space	3
	.word	0x2
.text
	.align	2, 0
	.globl	fi
	.type	 fi,function
	.thumb_func
fi:
	ldr	r1, .L27
	ldr	r1, [r1, #0x4]
	add	r1, r1, r0
	add	r0, r1, #0
	bx	lr
.L28:
	.align	2, 0
.L27:
	.word	st.35
.Lfe9:
	.size	 fi,.Lfe9-fi
	.section .rodata
	.align	1, 0
	.type	 big.39,object
	.size	 big.39,80
big.39:
	.short	0x1
	.short	0x2
	.space	76
.text
	.align	2, 0
	.globl	fj
	.type	 fj,function
	.thumb_func
fj:
	ldr	r1, .L30
	lsl	r0, r0, #0x1
	add	r0, r0, r1
	ldrh	r0, [r0]
	bx	lr
.L31:
	.align	2, 0
.L30:
	.word	big.39
.Lfe10:
	.size	 fj,.Lfe10-fj
	.section .rodata
	.align	2, 0
	.type	 fl.43,object
	.size	 fl.43,8
fl.43:
	.word 0x3f800000	@ float 1.00000000000000000000e0
	.word 0x40200000	@ float 2.50000000000000000000e0
.text
	.align	2, 0
	.globl	fk
	.type	 fk,function
	.thumb_func
fk:
	lsl	r0, r0, #0x2
	ldr	r1, .L33
	add	r0, r0, r1
	ldr	r0, [r0]
	bx	lr
.L34:
	.align	2, 0
.L33:
	.word	fl.43
.Lfe11:
	.size	 fk,.Lfe11-fk
