@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	unfoldpark
	.type	 unfoldpark,function
	.thumb_func
unfoldpark:
	push	{r4, r5, r6, r7, lr}
	add	r2, r0, #0
	add	r6, r1, #0
	mov	r1, #0x0
	ldr	r5, .L9
	ldr	r3, .L9+0x4
	ldr	r4, .L9+0x8
	mov	r7, #0x20
.L3:
	ldr	r0, [r4]
	add	r0, r0, #0x1
	str	r0, [r4]
	ldr	r0, [r5, #0x3c]
	str	r0, [r6]
	ldr	r0, [r5, #0x3c]
	cmp	r0, #0
	ble	.L6	@cond_branch
	str	r0, [r3]
	str	r2, [r3, #0x4]
	str	r7, [r3, #0x8]
.L6:
	add	r1, r1, #0x1
	cmp	r1, r2
	blt	.L3	@cond_branch
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L10:
	.align	2, 0
.L9:
	.word	0x3003400
	.word	0x40000d4
	.word	0x3002040
.Lfe1:
	.size	 unfoldpark,.Lfe1-unfoldpark
