@ GENERATED by scripts/regen-flag-pair-probes.ts — do not hand-edit.
@ source    : packages/core/test/corpus/probe-agbcc-debug.c
@ toolchain : ARMV4T_AGBCC (gcc 2.9-arm, Thumb), binary from $ASMLIFT_AGBCC
@ cc flags  : -Wimplicit -mthumb-interwork -O2 -fhex-asm -fprologue-bugfix
@ read by   : packages/core/test/debug-sections.test.ts
@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	gcd
	.type	 gcd,function
	.thumb_func
gcd:
	push	{r4, lr}
	add	r2, r0, #0
	add	r0, r1, #0
	cmp	r0, #0
	beq	.L4	@cond_branch
.L5:
	add	r4, r0, #0
	add	r0, r2, #0
	add	r1, r4, #0
	bl	__modsi3
	add	r2, r4, #0
	cmp	r0, #0
	bne	.L5	@cond_branch
.L4:
	add	r0, r2, #0
	pop	{r4}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 gcd,.Lfe1-gcd
	.align	2, 0
	.globl	pick
	.type	 pick,function
	.thumb_func
pick:
	cmp	r0, #0x1
	beq	.L10	@cond_branch
	cmp	r0, #0x1
	bgt	.L15	@cond_branch
	cmp	r0, #0
	beq	.L9	@cond_branch
	b	.L13
.L15:
	cmp	r0, #0x2
	beq	.L11	@cond_branch
	cmp	r0, #0x3
	beq	.L12	@cond_branch
	b	.L13
.L9:
	ldr	r0, .L17
	ldrh	r0, [r0, #0x2]
	b	.L16
.L18:
	.align	2, 0
.L17:
	.word	gTable
.L10:
	ldr	r0, .L19
	ldrh	r0, [r0, #0x4]
	b	.L16
.L20:
	.align	2, 0
.L19:
	.word	gTable
.L11:
	mov	r0, #0x7
	b	.L16
.L12:
	mov	r0, #0x9
	b	.L16
.L13:
	mov	r0, #0x1
	neg	r0, r0
.L16:
	bx	lr
.Lfe2:
	.size	 pick,.Lfe2-pick
