@ GENERATED by scripts/regen-select-spelling-probes.ts — do not hand-edit.
@ source    : packages/core/test/corpus/probe-agbcc-select-early.c
@ toolchain : ARMV4T_AGBCC (gcc 2.9-arm, Thumb), binary from $ASMLIFT_AGBCC
@ cc flags  : -mthumb-interwork -Wimplicit -O2 -fhex-asm -fprologue-bugfix
@ read by   : packages/core/test/select-spelling.test.ts
@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	selbtn
	.type	 selbtn,function
	.thumb_func
selbtn:
	mov	r1, #0x40
	and	r1, r1, r0
	cmp	r1, #0
	bne	.L3	@cond_branch
	mov	r0, #0x0
	b	.L4
.L3:
	mov	r0, #0x1
.L4:
	bx	lr
.Lfe1:
	.size	 selbtn,.Lfe1-selbtn
	.align	2, 0
	.globl	selk53
	.type	 selk53,function
	.thumb_func
selk53:
	cmp	r0, #0
	bne	.L6	@cond_branch
	mov	r0, #0x3
	b	.L7
.L6:
	mov	r0, #0x5
.L7:
	bx	lr
.Lfe2:
	.size	 selk53,.Lfe2-selk53
	.align	2, 0
	.globl	selpool
	.type	 selpool,function
	.thumb_func
selpool:
	cmp	r0, #0
	bne	.L9	@cond_branch
	ldr	r0, .L11
	b	.L10
.L12:
	.align	2, 0
.L11:
	.word	0x7abcdef0
.L9:
	ldr	r0, .L13
.L10:
	bx	lr
.L14:
	.align	2, 0
.L13:
	.word	0x12345678
.Lfe3:
	.size	 selpool,.Lfe3-selpool
	.align	2, 0
	.globl	selcomp
	.type	 selcomp,function
	.thumb_func
selcomp:
	cmp	r0, #0
	bne	.L16	@cond_branch
	sub	r0, r1, r2
	b	.L18
.L16:
	add	r0, r1, r2
.L18:
	bx	lr
.Lfe4:
	.size	 selcomp,.Lfe4-selcomp
	.align	2, 0
	.globl	selbody
	.type	 selbody,function
	.thumb_func
selbody:
	cmp	r0, #0
	bne	.L20	@cond_branch
	mov	r0, #0x2
	str	r0, [r1]
	mov	r0, #0x3
	b	.L21
.L20:
	mov	r0, #0x1
	str	r0, [r1]
	mov	r0, #0x5
.L21:
	bx	lr
.Lfe5:
	.size	 selbody,.Lfe5-selbody
	.align	2, 0
	.globl	selcomp3
	.type	 selcomp3,function
	.thumb_func
selcomp3:
	cmp	r0, #0
	bne	.L23	@cond_branch
	sub	r0, r1, r2
	sub	r0, r0, #0x7
	b	.L25
.L23:
	add	r0, r1, r2
	add	r0, r0, #0x7
.L25:
	bx	lr
.Lfe6:
	.size	 selcomp3,.Lfe6-selcomp3
	.align	2, 0
	.globl	selload
	.type	 selload,function
	.thumb_func
selload:
	cmp	r0, #0
	bne	.L27	@cond_branch
	ldr	r0, [r2]
	b	.L29
.L27:
	ldr	r0, [r1]
.L29:
	bx	lr
.Lfe7:
	.size	 selload,.Lfe7-selload
