@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	onepoll
	.type	 onepoll,function
	.thumb_func
onepoll:
	push	{r4, r5, r6, r7, lr}
	add	r5, r0, #0
	ldr	r3, .L12
	mov	r1, #0x0
	ldr	r7, .L12+0x4
	mov	r6, #0xc0
	lsl	r6, r6, #0x13
	mov	r4, #0x80
	lsl	r4, r4, #0x18
.L3:
	str	r7, [r3]
	add	r0, r1, r6
	str	r0, [r3, #0x4]
	lsr	r0, r1, #0x1
	orr	r0, r0, r4
	str	r0, [r3, #0x8]
	ldr	r0, [r3, #0x8]
	and	r0, r0, r4
	add	r2, r1, #0x1
	cmp	r0, #0
	beq	.L7	@cond_branch
	mov	r1, #0x80
	lsl	r1, r1, #0x18
.L6:
	ldr	r0, [r3, #0x8]
	and	r0, r0, r1
	cmp	r0, #0
	bne	.L6	@cond_branch
.L7:
	add	r1, r2, #0
	cmp	r1, r5
	blt	.L3	@cond_branch
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L13:
	.align	2, 0
.L12:
	.word	0x40000d4
	.word	0x3004000
.Lfe1:
	.size	 onepoll,.Lfe1-onepoll
