@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	X
	.type	 X,function
	.thumb_func
X:
	add	r0, r0, #0x1
	bx	lr
.Lfe1:
	.size	 X,.Lfe1-X
	.section .rodata
	.type	 tide.6,object
	.size	 tide.6,2
tide.6:
	.byte	0x1
	.byte	0x2
	.align	2, 0
	.type	 ptr.7,object
	.size	 ptr.7,4
ptr.7:
	.word	tide.6
.text
	.align	2, 0
	.globl	T
	.type	 T,function
	.thumb_func
T:
	ldr	r1, .L4
	add	r0, r0, r1
	ldrb	r0, [r0]
	ldrb	r1, [r1]
	add	r0, r0, r1
	bx	lr
.L5:
	.align	2, 0
.L4:
	.word	tide.6
.Lfe2:
	.size	 T,.Lfe2-T
