# GENERATED by scripts/regen-switch-spelling-probes.ts — do not hand-edit.
# source    : packages/core/test/corpus/probe-swladder.c
# toolchain : MIPS_GCC (gcc2.7.2kmc — Snowboard Kids 2's Kyoto build, -O2), binary from $ASMLIFT_KMC_DIR
# cc flags  : -mabi=32 -mgp32 -mfp32 -mno-abicalls -nostdinc -fno-PIC -G 0 -funsigned-char -w -mips3 -EB -O2 -fno-builtin -fno-asm
# objdump   : mips-linux-gnu-objdump -d --no-show-raw-insn
# read by   : packages/core/test/switch-arms.test.ts

corpus.o:     file format elf32-tradbigmips


Disassembly of section .text:

00000000 <swpick>:
   0:	li	v0,6
   4:	bne	a0,v0,18 <swpick+0x18>
   8:	li	v0,7
   c:	li	v0,1
  10:	j	24 <swpick+0x24>
  14:	sw	v0,0(a1)
  18:	bne	a0,v0,24 <swpick+0x24>
  1c:	li	v0,2
  20:	sw	v0,4(a1)
  24:	jr	ra
  28:	nop
  2c:	nop
