# GENERATED by scripts/regen-switch-spelling-probes.ts — do not hand-edit.
# source    : packages/core/test/corpus/probe-swfrontload.c
# toolchain : MIPS_GCC (gcc2.7.2 — Mario Party 3's build, -O1), binary from $ASMLIFT_GCC272_DIR
# cc flags  : -G0 -mips3 -mgp32 -mfp32 -O1 -Wa,--vr4300mul-off -nostdinc
# objdump   : mips-linux-gnu-objdump -d --no-show-raw-insn
# read by   : packages/core/test/switch-arms.test.ts

corpus.o:     file format elf32-tradbigmips


Disassembly of section .text:

00000000 <swpick>:
   0:	li	v0,6
   4:	beq	a0,v0,1c <swpick+0x1c>
   8:	li	v0,7
   c:	beq	a0,v0,28 <swpick+0x28>
  10:	li	v0,2
  14:	j	2c <swpick+0x2c>
  18:	nop
  1c:	li	v0,1
  20:	j	2c <swpick+0x2c>
  24:	sw	v0,0(a1)
  28:	sw	v0,4(a1)
  2c:	jr	ra
  30:	nop
	...
