# GENERATED by scripts/regen-switch-spelling-probes.ts — do not hand-edit.
# source    : packages/core/test/corpus/probe-mwcc-swrelnest.c
# toolchain : PPC_MWCC (mwcc_242_81), binary from $ASMLIFT_MWCC_ROOT
# cc flags  : -pragma msg_show_realref off -c -nostdinc -stderr -proc gekko -O4,p -enum int -inline auto -fp hard -Cpp_exceptions off
# objdump   : powerpc-eabi-objdump -d -r -M gekko --no-show-raw-insn
# read by   : packages/core/test/switch-arms.test.ts

corpus.o:     file format elf32-powerpc


Disassembly of section .text:

00000000 <swpath>:
   0:	cmpwi   r3,4
   4:	blt-    18 <swpath+0x18>
   8:	cmpwi   r3,5
   c:	bge-    28 <swpath+0x28>
  10:	lwz     r3,16(r4)
  14:	blr
  18:	cmpwi   r3,3
  1c:	blt-    28 <swpath+0x28>
  20:	lwz     r3,12(r4)
  24:	blr
  28:	li      r3,0
  2c:	blr
