# GENERATED by scripts/regen-switch-spelling-probes.ts — do not hand-edit.
# source    : packages/core/test/corpus/probe-mwcc-swladder.c
# toolchain : PPC_MWCC (mwcc_242_81), binary from $ASMLIFT_MWCC_ROOT
# cc flags  : -pragma msg_show_realref off -c -nostdinc -stderr -proc gekko -O4,p -enum int -inline auto -fp hard -Cpp_exceptions off
# objdump   : powerpc-eabi-objdump -d -r -M gekko --no-show-raw-insn
# read by   : packages/core/test/switch-arms.test.ts

corpus.o:     file format elf32-powerpc


Disassembly of section .text:

00000000 <swpath>:
   0:	cmpwi   r3,0
   4:	bne-    10 <swpath+0x10>
   8:	lwz     r3,0(r4)
   c:	blr
  10:	cmpwi   r3,1
  14:	bne-    20 <swpath+0x20>
  18:	lwz     r3,4(r4)
  1c:	blr
  20:	lwz     r3,8(r4)
  24:	blr
