# GENERATED by scripts/regen-switch-spelling-probes.ts — do not hand-edit.
# source    : packages/core/test/corpus/probe-mwcc-swdispatch.c
# toolchain : PPC_MWCC (mwcc_242_81), binary from $ASMLIFT_MWCC_ROOT
# cc flags  : -pragma msg_show_realref off -c -nostdinc -stderr -proc gekko -O4,p -enum int -inline auto -fp hard -Cpp_exceptions off
# objdump   : powerpc-eabi-objdump -d -r -M gekko --no-show-raw-insn
# read by   : packages/core/test/switch-arms.test.ts

corpus.o:     file format elf32-powerpc


Disassembly of section .text:

00000000 <swpath>:
   0:	cmpwi   r3,1
   4:	beq-    20 <swpath+0x20>
   8:	bge-    28 <swpath+0x28>
   c:	cmpwi   r3,0
  10:	bge-    18 <swpath+0x18>
  14:	b       28 <swpath+0x28>
  18:	lwz     r3,0(r4)
  1c:	blr
  20:	lwz     r3,4(r4)
  24:	blr
  28:	lwz     r3,8(r4)
  2c:	blr
