/* The MERGE-VARIABLE spelling of seven selects, read by packages/core/test/select-spelling.test.ts
   and regenerated by scripts/regen-select-spelling-probes.ts. Its twin is probe-agbcc-select-early.c
   — the SAME seven functions written with early returns.

   Together they are the truth-table for `raise/narrowlocal.ts`'s `armIsOneSet` read in
   raise/retsink.ts's direction. The first four have arms that are ONE speculatable SET, and their
   merge spelling LOSES the diamond (agbcc hoists one arm above the compare), so a target holding one
   was written with early returns. The last three are not one SET — a BODY, three ops, a memory read
   — and there both spellings emit a diamond, differing only in ARM ORDER, which is the whole point
   of the pair: `arms-are-one-set` must refuse them.

   selk3 is the named divergence and is deliberately NOT here: `v = a + 3` is two ops in asmlift's IR
   and one `adds` on this target, so agbcc hoists it and `armIsOneSet` refuses it anyway. See the
   retsink.ts header. */
int selbtn(int x) {
    int v;
    if (x & 0x40) { v = 1; } else { v = 0; }
    return v;
}
int selk53(int x) {
    int v;
    if (x) { v = 5; } else { v = 3; }
    return v;
}
int selpool(int x) {
    int v;
    if (x) { v = 0x12345678; } else { v = 0x7ABCDEF0; }
    return v;
}
int selcomp(int x, int a, int b) {
    int v;
    if (x) { v = a + b; } else { v = a - b; }
    return v;
}
int selbody(int x, int *p) {
    int v;
    if (x) { *p = 1; v = 5; } else { *p = 2; v = 3; }
    return v;
}
int selcomp3(int x, int a, int b) {
    int v;
    if (x) { v = a + b + 7; } else { v = a - b - 7; }
    return v;
}
int selload(int x, int *p, int *q) {
    int v;
    if (x) { v = *p; } else { v = *q; }
    return v;
}
