/* The MERGE-VARIABLE spelling of four constant-arm selects. Read by
   packages/core/test/select-spelling.test.ts; regenerated by scripts/regen-select-spelling-probes.ts.
   Its twin is probe-agbcc-select-early.c — the SAME four functions written with early returns.

   The first three have BARE arms (nothing but the constant). The fourth has a BODY in each arm,
   which is the whole point of the pair: raise/retsink.ts's `bare-arms` clause. */
int selbtn(int x) {
    int v;
    if (x & 0x40) { v = 1; } else { v = 0; }
    return v;
}
int selk53(int x) {
    int v;
    if (x) { v = 5; } else { v = 3; }
    return v;
}
int selpool(int x) {
    int v;
    if (x) { v = 0x12345678; } else { v = 0x7ABCDEF0; }
    return v;
}
int selbody(int x, int *p) {
    int v;
    if (x) { *p = 1; v = 5; } else { *p = 2; v = 3; }
    return v;
}
