// THE COMPILER FACT `raise/retsink.ts`'s `SELECT_GATES` RESTS ON, compiled rather than described.
//
// The pass admits a two-armed return diamond whose arms are ONE SPECULATABLE SET each, on the
// grounds that gcc 2.x's `jump_optimize` collapses exactly that shape — so agbcc cannot re-emit the
// diamond from a merge-variable source, and where the target holds one, the merge variable is the
// spelling of some other function. The predicate is `raise/narrowlocal.ts`'s `armIsOneSet`, shared
// between the two passes that read this one optimizer backwards. Two source spellings of one
// function is a COMPILER claim, and this repo's rule for those is to compile both and commit the
// objects: `packages/core/test/corpus/agbcc-select-{merge,early}.s`, regenerated by
// `scripts/regen-select-spelling-probes.ts` from the two `probe-agbcc-select-*.c` beside them.
// Same seven functions, written each way, on the flags `@asmlift/toolchains` actually uses.
//
// WHAT THE PAIR SHOWS — a truth-table for `armIsOneSet` in retsink's direction:
//
//   ONE SET     merge spelling keeps NO unconditional branch — the arm is hoisted above the compare
//               (`selk53`, `selpool`, and `selcomp`, whose arm COMPUTES `a + b` and is hoisted all
//               the same) or the whole select folds branchless (`selbtn`) — while the early-return
//               spelling emits the diamond. The two are different objects, and only one of them can
//               be the target. → sink.
//   NOT ONE SET both spellings emit the diamond: a BODY (`selbody`), THREE ops (`selcomp3`) or a
//               memory READ (`selload`) all pin the arm below the compare, so the hoist is gone and
//               the merge variable can spell the target after all. The two objects differ only in
//               ARM ORDER. → do not sink (`arms-are-one-set`).
//
// `selcomp` is the case the deleted bespoke `constant-arms` clause refused and this one admits, and
// `selload` is the one `REEVAL_UNSAFE_OPS` earns its place on — a load is ONE op and is NOT one
// speculatable SET (`gcc/rtlanal.c:1770-1771`).
//
// Offline: reads committed text, runs no compiler.
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, test } from 'vitest';

const CORPUS = join(import.meta.dirname, 'corpus');

const read = (f: string) => readFileSync(join(CORPUS, f), 'utf8');

/** The body of one function in an agbcc `.s`, as its instruction lines — directives, labels and
 *  the generator's `@` comments dropped. */
const bodyOf = (asm: string, sym: string): string[] => {
  const start = asm.indexOf(`\n${sym}:\n`);
  expect(start, `${sym} is in the fixture`).toBeGreaterThan(0);
  const rest = asm.slice(start + sym.length + 3);
  const end = rest.search(/^\t\.(align|size)/m);
  return (end === -1 ? rest : rest.slice(0, end))
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith('.') && !l.startsWith('@'));
};

/** An UNCONDITIONAL branch — the edge into a shared return block, and the thing a diamond has that
 *  a hoisted select does not. `@cond_branch`-annotated lines are the conditional ones. */
const uncond = (body: string[]) => body.filter((l) => /^b\s/.test(l)).length;

const MERGE = read('agbcc-select-merge.s');
const EARLY = read('agbcc-select-early.s');

describe('agbcc: a ONE-SET-arm select cannot be spelled with a merge variable', () => {
  test.each(['selbtn', 'selk53', 'selpool', 'selcomp'])('%s: the merge spelling has no diamond', (sym) => {
    expect(uncond(bodyOf(MERGE, sym)), 'hoisted or folded — no branch to a shared return').toBe(0);
    expect(uncond(bodyOf(EARLY, sym)), 'the early-return spelling keeps the diamond').toBe(1);
    expect(bodyOf(MERGE, sym)).not.toEqual(bodyOf(EARLY, sym));
  });

  test('selbtn folds branchless entirely — no compare survives either', () => {
    const body = bodyOf(MERGE, 'selbtn');
    expect(body.some((l) => l.startsWith('cmp'))).toBe(false);
    expect(body.join(' ')).toContain('neg');
    expect(body.join(' ')).toContain('lsr');
  });
});

describe('agbcc: an arm that is NOT one SET CAN be — the two spellings differ only in arm order', () => {
  // The three refusals `arms-are-one-set` is committed FOR, one per reason `armIsOneSet` gives:
  // a body, more than one result-producing op, and an op `REEVAL_UNSAFE_OPS` calls unsafe.
  test.each(['selbody', 'selcomp3', 'selload'])('%s keeps its diamond in BOTH spellings', (sym) => {
    expect(uncond(bodyOf(MERGE, sym)), 'the merge spelling keeps it').toBe(1);
    expect(uncond(bodyOf(EARLY, sym)), 'and so does the early-return spelling').toBe(1);
  });

  test('selcomp3 and selload: the same instructions, the opposite branch sense', () => {
    for (const sym of ['selcomp3', 'selload']) {
      const [m, e] = [bodyOf(MERGE, sym), bodyOf(EARLY, sym)];
      expect(m.length, `${sym} instruction count`).toBe(e.length);
      expect(
        m.some((l) => l.startsWith('beq')),
        `${sym} merge spelling branches on equal`,
      ).toBe(true);
      expect(
        e.some((l) => l.startsWith('bne')),
        `${sym} early spelling branches on not-equal`,
      ).toBe(true);
    }
  });

  test('selbody: the same work in the opposite arm order, under the opposite branch sense', () => {
    const [m, e] = [bodyOf(MERGE, 'selbody'), bodyOf(EARLY, 'selbody')];
    const count = (b: string[], op: string) => b.filter((l) => l.startsWith(op)).length;
    for (const op of ['mov', 'str', 'cmp', 'bx']) {
      expect(count(m, op), `${op} count`).toBe(count(e, op));
    }
    // THE WHOLE DIFFERENCE. The merge spelling puts the TAKEN arm first under a `beq`; the
    // early-return spelling puts the fall-through arm first under a `bne`. That is the sense
    // `/flip-branch` supplies in the ranked fan and the unranked primary does not, and it is why
    // sinking a BODIED arm trades a byte-exact match rather than winning one.
    expect(m.some((l) => l.startsWith('beq'))).toBe(true);
    expect(e.some((l) => l.startsWith('bne'))).toBe(true);
    const consts = (b: string[]) => b.filter((l) => l.startsWith('mov')).map((l) => l.split(', ')[1]);
    expect(consts(m)).toEqual(['#0x1', '#0x5', '#0x2', '#0x3']);
    expect(consts(e)).toEqual(['#0x2', '#0x3', '#0x1', '#0x5']);
  });
});
