@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	LoadBGTilemapData
	.type	 LoadBGTilemapData,function
	.thumb_func
LoadBGTilemapData:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	add	sp, sp, #-0x34
	ldr	r2, .L100
	mov	r9, r2
	lsl	r1, r1, #0x1
	lsl	r0, r0, #0x2
	add	r1, r1, r0
	ldr	r3, .L100+0x4
	add	r0, r1, r3
	ldrb	r0, [r0]
	mov	r8, r0
	ldr	r7, .L100+0x8
	add	r1, r1, r7
	ldrb	r2, [r1]
	ldr	r0, .L100+0xc
	ldr	r1, [r0]
	mov	r3, r8
	add	r0, r1, r3
	ldrb	r0, [r0, #0x1]
	str	r0, [sp, #0xc]
	ldrb	r0, [r1, #0x1]
	lsl	r0, r0, #0x1f
	cmp	r0, #0
	bne	.LCB32
	b	.L3	@long jump
.LCB32:
	cmp	r3, #0x2
	beq	.LCB34
	b	.L3	@long jump
.LCB34:
	mov	r5, #0x10
	ldr	r7, [sp, #0xc]
	lsl	r5, r5, r7
	lsl	r0, r2, #0x3
	ldr	r1, .L100+0x10
	add	r0, r0, r1
	ldr	r0, [r0]
	bl	DecompressAlloc
	add	r0, r0, #0x4
	mov	sl, r0
	ldr	r0, .L100+0x14
	ldrh	r0, [r0]
	cmp	r0, #0
	beq	.L4	@cond_branch
	mov	r0, #0x80
	lsl	r0, r0, #0x18
	mov	r7, #0x0
	lsr	r2, r5, #0x1
	ldr	r3, .L100+0x18
	mov	ip, r3
	orr	r2, r2, r0
	mov	r8, r2
.L5:
	mov	r2, #0x0
	mov	r6, r5
	mul	r6, r6, r7
	add	r0, r7, #0x1
	str	r0, [sp, #0x2c]
	mov	r1, ip
	ldrh	r1, [r1]
	cmp	r2, r1
	bge	.L9	@cond_branch
	ldr	r4, .L100+0x1c
	ldr	r3, .L100+0x18
.L11:
	add	r1, r2, r4
	ldrh	r0, [r3]
	mul	r0, r0, r7
	add	r0, r2, r0
	add	r0, r0, sl
	ldrb	r0, [r0]
	strb	r0, [r1]
	add	r2, r2, #0x1
	ldrh	r0, [r3]
	cmp	r2, r0
	blt	.L11	@cond_branch
.L9:
	mov	r2, ip
	ldrh	r1, [r2]
	cmp	r1, r5
	bcs	.L14	@cond_branch
	ldr	r3, .L100+0x1c
	mov	r2, #0x0
.L16:
	add	r0, r1, r3
	strb	r2, [r0]
	add	r1, r1, #0x1
	cmp	r1, r5
	bcc	.L16	@cond_branch
.L14:
	ldr	r0, .L100+0x1c
	mov	r3, r9
	str	r0, [r3]
	ldr	r7, .L100+0x20
	ldr	r0, [r7]
	add	r0, r0, r6
	str	r0, [r3, #0x4]
	mov	r0, r8
	str	r0, [r3, #0x8]
	ldr	r0, [r3, #0x8]
	mov	r1, #0x80
	lsl	r1, r1, #0x18
	cmp	r0, #0
	bge	.L19	@cond_branch
.L18:
	mov	r2, r9
	ldr	r0, [r2, #0x8]
	and	r0, r0, r1
	cmp	r0, #0
	bne	.L18	@cond_branch
.L19:
	ldr	r7, [sp, #0x2c]
	ldr	r0, .L100+0x14
	ldrh	r0, [r0]
	cmp	r7, r0
	blt	.L5	@cond_branch
.L4:
	ldr	r0, .L100+0x14
	ldrh	r2, [r0]
	mov	r1, r5
	mul	r1, r1, r2
	sub	r0, r0, #0xe
	ldr	r0, [r0]
	add	r1, r1, r0
	mov	r3, #0x4
	neg	r3, r3
	add	r3, r3, sl
	mov	r8, r3
	cmp	r2, r5
	bcs	.L25	@cond_branch
	mov	r4, sp
	mov	r6, #0x0
	lsr	r3, r5, #0x1
	mov	r0, #0x81
	lsl	r0, r0, #0x18
	orr	r3, r3, r0
.L26:
	strh	r6, [r4]
	mov	r7, sp
	mov	r0, r9
	str	r7, [r0]
	str	r1, [r0, #0x4]
	str	r3, [r0, #0x8]
	add	r1, r1, r5
	add	r2, r2, #0x1
	cmp	r2, r5
	bcc	.L26	@cond_branch
.L25:
	mov	r0, r8
	bl	thunk_HeapFree
	b	.L2
.L101:
	.align	2, 0
.L100:
	.word	0x40000d4
	.word	0x8057acd
	.word	0x8057acc
	.word	0x30034a0
	.word	0x8189ccc
	.word	0x300347a
	.word	0x3003478
	.word	0x3004db0
	.word	0x300346c
.L3:
	mov	r0, r8
	sub	r0, r0, #0x2
	lsl	r0, r0, #0x2
	lsl	r1, r2, #0x3
	add	r0, r0, r1
	ldr	r1, .L102
	add	r0, r0, r1
	ldr	r0, [r0]
	bl	DecompressAlloc
	add	r0, r0, #0x4
	str	r0, [sp, #0x8]
	ldr	r2, [sp, #0xc]
	cmp	r2, #0
	beq	.L29	@cond_branch
	mov	r3, #0x2
	str	r3, [sp, #0x4]
	cmp	r2, #0x3
	bne	.L31	@cond_branch
	mov	r7, #0x4
	str	r7, [sp, #0x4]
	b	.L31
.L103:
	.align	2, 0
.L102:
	.word	0x8189ccc
.L29:
	mov	r0, #0x1
	str	r0, [sp, #0x4]
.L31:
	mov	r7, #0x0
	ldr	r1, [sp, #0x8]
	sub	r1, r1, #0x4
	str	r1, [sp, #0x28]
	ldr	r2, [sp, #0x4]
	cmp	r7, r2
	blt	.LCB256
	b	.L32	@long jump
.LCB256:
	mov	r3, r8
	lsl	r0, r3, #0x3
	sub	r0, r0, r3
	lsl	r0, r0, #0x2
	str	r0, [sp, #0x1c]
	str	r0, [sp, #0x20]
.L33:
	ldr	r0, [sp, #0xc]
	cmp	r0, #0x1
	beq	.L44	@cond_branch
	cmp	r0, #0x1
	bgt	.L79	@cond_branch
	cmp	r0, #0
	beq	.L37	@cond_branch
	b	.L36
.L79:
	ldr	r1, [sp, #0xc]
	cmp	r1, #0x2
	beq	.L55	@cond_branch
	cmp	r1, #0x3
	bne	.LCB285
	b	.L64	@long jump
.LCB285:
	b	.L36
.L37:
	ldr	r2, [sp, #0x1c]
	ldr	r3, .L104
	add	r1, r2, r3
	ldrh	r0, [r1, #0x10]
	mov	r2, #0x20
	mov	sl, r2
	mov	r3, r8
	lsl	r2, r3, #0x3
	cmp	r0, #0x1f
	bhi	.L38	@cond_branch
	add	r1, r0, #0
	mov	sl, r1
.L38:
	mov	r0, #0x20
	mov	r1, sl
	sub	r6, r0, r1
	cmp	r6, #0x20
	bls	.L40	@cond_branch
	mov	r6, #0x20
.L40:
	mov	r3, r8
	sub	r0, r2, r3
	lsl	r0, r0, #0x2
	ldr	r1, .L104
	add	r2, r0, r1
	ldrh	r0, [r2, #0x12]
	mov	r3, #0x20
	str	r3, [sp, #0x10]
	cmp	r0, #0x1f
	bhi	.L42	@cond_branch
	ldrh	r2, [r2, #0x12]
	str	r2, [sp, #0x10]
.L42:
	mov	r0, #0x0
	str	r0, [sp, #0x14]
	mov	r1, #0x0
	str	r1, [sp, #0x18]
	b	.L36
.L105:
	.align	2, 0
.L104:
	.word	0x3003430
.L44:
	cmp	r7, #0
	beq	.L45	@cond_branch
	ldr	r2, [sp, #0x1c]
	ldr	r3, .L106
	add	r1, r2, r3
	ldrh	r0, [r1, #0x10]
	mov	r2, #0x20
	mov	sl, r2
	mov	r3, r8
	lsl	r2, r3, #0x3
	cmp	r0, #0x1f
	bhi	.L48	@cond_branch
	add	r1, r0, #0
	mov	sl, r1
	b	.L48
.L107:
	.align	2, 0
.L106:
	.word	0x3003430
.L45:
	mov	r0, #0x20
	mov	sl, r0
	mov	r1, r8
	lsl	r2, r1, #0x3
.L48:
	add	r0, r2, #0
	cmp	r7, #0
	beq	.L49	@cond_branch
	mov	r2, #0x20
	mov	r3, sl
	sub	r6, r2, r3
	cmp	r6, #0x20
	bls	.L52	@cond_branch
	mov	r6, #0x20
	b	.L52
.L49:
	mov	r6, #0x0
.L52:
	mov	r1, r8
	sub	r0, r0, r1
	lsl	r0, r0, #0x2
	ldr	r3, .L108
	add	r2, r0, r3
	ldrh	r0, [r2, #0x12]
	mov	r1, #0x20
	str	r1, [sp, #0x10]
	cmp	r0, #0x1f
	bhi	.L53	@cond_branch
	ldrh	r2, [r2, #0x12]
	str	r2, [sp, #0x10]
.L53:
	lsl	r2, r7, #0x5
	str	r2, [sp, #0x14]
	mov	r3, #0x0
	str	r3, [sp, #0x18]
	b	.L36
.L109:
	.align	2, 0
.L108:
	.word	0x3003430
.L55:
	ldr	r0, [sp, #0x1c]
	ldr	r2, .L110
	add	r1, r0, r2
	ldrh	r0, [r1, #0x10]
	mov	r3, #0x20
	mov	sl, r3
	mov	r3, r8
	lsl	r2, r3, #0x3
	cmp	r0, #0x1f
	bhi	.L56	@cond_branch
	add	r1, r0, #0
	mov	sl, r1
.L56:
	mov	r0, #0x20
	mov	r1, sl
	sub	r6, r0, r1
	cmp	r6, #0x20
	bls	.L58	@cond_branch
	mov	r6, #0x20
.L58:
	cmp	r7, #0
	beq	.L60	@cond_branch
	mov	r3, r8
	sub	r0, r2, r3
	lsl	r0, r0, #0x2
	ldr	r3, .L110
	add	r1, r0, r3
	ldrh	r0, [r1, #0x12]
	mov	r3, #0x20
	str	r3, [sp, #0x10]
	cmp	r0, #0x1f
	bhi	.L63	@cond_branch
	ldrh	r1, [r1, #0x12]
	str	r1, [sp, #0x10]
	b	.L63
.L111:
	.align	2, 0
.L110:
	.word	0x3003430
.L60:
	mov	r0, #0x20
	str	r0, [sp, #0x10]
.L63:
	mov	r1, #0x0
	str	r1, [sp, #0x14]
	mov	r3, r8
	sub	r0, r2, r3
	lsl	r0, r0, #0x2
	ldr	r1, .L112
	add	r0, r0, r1
	ldrh	r0, [r0, #0x12]
	mov	r2, r7
	mul	r2, r2, r0
	str	r2, [sp, #0x18]
	b	.L36
.L113:
	.align	2, 0
.L112:
	.word	0x3003430
.L64:
	cmp	r7, #0
	beq	.L65	@cond_branch
	ldr	r3, [sp, #0x1c]
	ldr	r0, .L114
	add	r1, r3, r0
	ldrh	r0, [r1, #0x10]
	mov	r2, #0x20
	mov	sl, r2
	cmp	r0, #0x1f
	bhi	.L68	@cond_branch
	add	r1, r0, #0
	mov	sl, r1
	b	.L68
.L115:
	.align	2, 0
.L114:
	.word	0x3003430
.L65:
	mov	r3, #0x20
	mov	sl, r3
.L68:
	cmp	r7, #0
	beq	.L69	@cond_branch
	mov	r0, #0x20
	mov	r1, sl
	sub	r6, r0, r1
	cmp	r6, #0x20
	bls	.L72	@cond_branch
.L69:
	mov	r6, #0x20
.L72:
	cmp	r7, #0
	beq	.L73	@cond_branch
	ldr	r2, [sp, #0x1c]
	ldr	r3, .L116
	add	r1, r2, r3
	ldrh	r0, [r1, #0x12]
	mov	r2, #0x20
	str	r2, [sp, #0x10]
	cmp	r0, #0x1f
	bhi	.L76	@cond_branch
	ldrh	r1, [r1, #0x12]
	str	r1, [sp, #0x10]
	b	.L76
.L117:
	.align	2, 0
.L116:
	.word	0x3003430
.L73:
	mov	r3, #0x20
	str	r3, [sp, #0x10]
.L76:
	mov	r0, #0x2
	and	r0, r0, r7
	neg	r0, r0
	asr	r0, r0, #0x1f
	mov	r1, #0x20
	and	r0, r0, r1
	str	r0, [sp, #0x14]
	mov	r1, #0x1
	and	r1, r1, r7
	neg	r0, r1
	orr	r0, r0, r1
	asr	r0, r0, #0x1f
	mov	r2, #0x20
	and	r0, r0, r2
	str	r0, [sp, #0x18]
.L36:
	mov	r5, #0x0
	add	r3, r7, #0x1
	str	r3, [sp, #0x2c]
	ldr	r0, [sp, #0x10]
	cmp	r5, r0
	bcs	.L80	@cond_branch
	ldr	r1, [sp, #0x20]
	ldr	r2, .L118
	add	r1, r1, r2
	str	r1, [sp, #0x24]
	mov	r3, #0x81
	lsl	r3, r3, #0x18
	mov	ip, r3
	mov	r0, ip
	orr	r0, r0, r6
	mov	ip, r0
.L81:
	mov	r1, r8
	lsl	r2, r1, #0x3
	lsl	r4, r5, #0x6
	lsl	r3, r7, #0xb
	cmp	r6, #0
	beq	.L84	@cond_branch
	mov	r1, sp
	mov	r0, #0x0
	strh	r0, [r1]
	mov	r0, r9
	str	r1, [r0]
	ldr	r1, [sp, #0x24]
	ldr	r0, [r1]
	add	r0, r0, r4
	add	r0, r0, r3
	mov	r1, sl
	lsl	r1, r1, #0x1
	add	r0, r0, r1
	mov	r1, r9
	str	r0, [r1, #0x4]
	mov	r0, ip
	str	r0, [r1, #0x8]
.L84:
	mov	r1, r8
	sub	r2, r2, r1
	lsl	r2, r2, #0x2
	ldr	r1, .L118+0x4
	add	r0, r2, r1
	ldrh	r0, [r0, #0x10]
	str	r0, [sp, #0x30]
	ldr	r1, [sp, #0x18]
	add	r0, r5, r1
	ldr	r1, [sp, #0x30]
	mul	r0, r0, r1
	lsl	r0, r0, #0x1
	ldr	r1, [sp, #0x8]
	add	r0, r1, r0
	ldr	r1, [sp, #0x14]
	lsl	r1, r1, #0x1
	str	r1, [sp, #0x30]
	add	r0, r0, r1
	mov	r1, r9
	str	r0, [r1]
	ldr	r0, .L118
	add	r2, r2, r0
	ldr	r0, [r2]
	add	r0, r0, r4
	add	r0, r0, r3
	str	r0, [r1, #0x4]
	mov	r1, #0x80
	lsl	r1, r1, #0x18
	mov	r0, sl
	orr	r0, r0, r1
	mov	r2, r9
	str	r0, [r2, #0x8]
	ldr	r0, [r2, #0x8]
	and	r0, r0, r1
	add	r2, r5, #0x1
	cmp	r0, #0
	beq	.L85	@cond_branch
.L88:
	mov	r3, r9
	ldr	r0, [r3, #0x8]
	and	r0, r0, r1
	cmp	r0, #0
	bne	.L88	@cond_branch
.L85:
	add	r5, r2, #0
	ldr	r0, [sp, #0x10]
	cmp	r5, r0
	bcc	.L81	@cond_branch
.L80:
	ldr	r2, [sp, #0x10]
	cmp	r2, #0x1f
	bgt	.L94	@cond_branch
	mov	r5, sp
	mov	r1, #0x0
	mov	ip, r1
	ldr	r3, [sp, #0x20]
	ldr	r0, .L118
	add	r4, r3, r0
	lsl	r3, r7, #0xb
	ldr	r7, .L118+0x8
.L96:
	mov	r1, ip
	strh	r1, [r5]
	mov	r0, sp
	mov	r1, r9
	str	r0, [r1]
	ldr	r0, [r4]
	add	r0, r0, r3
	lsl	r1, r2, #0x6
	add	r0, r0, r1
	mov	r1, r9
	str	r0, [r1, #0x4]
	str	r7, [r1, #0x8]
	add	r2, r2, #0x1
	cmp	r2, #0x1f
	ble	.L96	@cond_branch
.L94:
	ldr	r7, [sp, #0x2c]
	ldr	r2, [sp, #0x4]
	cmp	r7, r2
	bge	.LCB757
	b	.L33	@long jump
.LCB757:
.L32:
	ldr	r0, [sp, #0x28]
	bl	thunk_HeapFree
.L2:
	add	sp, sp, #0x34
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L119:
	.align	2, 0
.L118:
	.word	0x3003434
	.word	0x3003430
	.word	-0x7effffe0
.Lfe1:
	.size	 LoadBGTilemapData,.Lfe1-LoadBGTilemapData
.text
	.align	2, 0
