// asmlift — the candidate-compile seam.
//
// A candidate compile is ONE contract: candidate source in, relocatable object out. A project
// fills it with its OWN compiler via a `decomp.yaml` `compiler` command template — different
// version, different flags, no asmlift Docker image anywhere. (asmlift's pinned toolchains
// implement the same contract in the private @asmlift/toolchains package, for the benchmark
// and the matching suite.)
//
// This module is deliberately free of score.ts/objdiff imports so the CLI can build a compiler
// from config without loading the objdiff wasm, and so its tests stay offline.
import { C_TYPEDEFS } from '@asmlift/core/target';
import { spawn, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { homedir, tmpdir } from 'node:os';
import { basename, dirname, isAbsolute, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  COMPILE_ENV,
  NOT_CACHEABLE,
  OFF as OFF_CACHE,
  STAMP_PROBE,
  candCache,
  candidateCacheRefusal,
  isChainMeasurement,
  noteKeyRefused,
  toolchainFileChain,
} from './candcache';
import { macroDefinesOf, renderDeclarations, selfDeclaredContext } from './declare';

// The world probe's representative declaration block is GENERATED by the real declaration
// renderer over a FIXED synthetic ref set exercising its full vocabulary — a padded struct
// with a signed narrow member, a volatile member, and a pointer member; a volatile scalar
// (MMIO); a const unsized array (ROM table); a value-referenced code prototype. Because the
// probe text IS declare.ts output, the probe cannot drift from what synthesis actually emits:
// any vocabulary change in the renderer flows into the probe by construction.
const PROBE_DECLS = renderDeclarations([
  { name: 'AsmliftProbeFn', info: { name: 'AsmliftProbeFn', kind: 'code' } },
  {
    name: 'gAsmliftProbeMmio',
    info: { name: 'gAsmliftProbeMmio', kind: 'data', shape: 'scalar', size: 2, signed: false, volatile: true },
  },
  {
    name: 'gAsmliftProbeShape',
    info: {
      name: 'gAsmliftProbeShape',
      kind: 'data',
      shape: 'struct',
      structName: 'AsmliftProbeShape',
      size: 12, // > the members' 8-byte extent, so the tail-pad spelling is probed too
      volatile: true,
      layout: [
        { name: 'lvl', offset: 0, size: 1, signed: true }, // s8 — the narrow signed spelling
        { name: 'gain', offset: 2, size: 2, signed: false, volatile: true }, // interior pad before it
        { name: 'next', offset: 4, size: 4, pointer: true }, // void *
      ],
    },
  },
  {
    name: 'gAsmliftProbeTable',
    info: { name: 'gAsmliftProbeTable', kind: 'data', shape: 'array', elemSize: 2, const: true },
  },
]);

/** Compile one candidate translation unit into a relocatable object; returns the object path.
 *  Throws on any failure — a candidate that cannot be compiled must never score.
 *
 *  `declarations` (optional) is the candidate's SYNTHESIZED declaration block (declare.ts —
 *  self-declaring candidates): joined to the typedef prelude in the self-declared world,
 *  dropped with it in the headers world (the probe below arbitrates). Compilers that inject
 *  their own context (the benchmark's vendored-ctx real-tier compile, @asmlift/toolchains)
 *  simply ignore the argument — their context IS the headers world. */
export type CandidateCompiler = (source: string, symbol: string, backendId: string, declarations?: string) => string;

/** The same contract, run without blocking the event loop, so several candidates can compile at
 *  once. Each worker owns its own scratch slot, so one worker's object survives exactly until
 *  that worker compiles its next candidate — the caller must consume it before asking for
 *  another (`rank.ts`'s pool scores each object the moment it lands). */
export type AsyncCandidateCompiler = (
  source: string,
  symbol: string,
  backendId: string,
  declarations?: string,
) => Promise<string>;

/** One compiler instance in both flavours. `compile` is the synchronous contract every existing
 *  caller uses; `worker()` mints an INDEPENDENT async compiler with its own scratch slot — call
 *  it once per pool worker. Both share the one cached world probe below. */
export interface CommandCompilers {
  compile: CandidateCompiler;
  worker: () => AsyncCandidateCompiler;
  /** Which WORLD the probe found, or undefined before the first candidate compiled: `true` =
   *  SELF-DECLARED (this template compiles bare candidates, so asmlift's synthesized declaration
   *  block is part of every score), `false` = HEADERS (the block is dropped, the project owns the
   *  declarations). Exposed because the caller publishing a score has to say whether that score
   *  rests on declarations asmlift invented — and only the probe knows. */
  selfDeclared: () => boolean | undefined;
}

export interface CompileCommandOptions {
  /** Working directory for the command — the decomp.yaml's directory, so project-relative
   *  paths (`./tools/agbcc/bin/agbcc`) resolve regardless of where asmlift was invoked. */
  cwd?: string;
  /** `tools.asmlift.candidateCache` — `'off'` is a project's own REFUSAL of the candidate-object
   *  cache for this command, and the only value there is. It is the opposite shape from the
   *  deleted `cacheInputs`: that key was a soundness CONTRACT whose incompleteness served a stale
   *  object, this one only ever turns the cache off, so getting it wrong costs a cold start.
   *  It is the general escape for the shapes no scan can reach — a wrapper that reads a config
   *  directory, a compiler behind a runtime `OPAQUE_RUNTIMES` does not name, a `cd` into a
   *  computed path — and it is per PROJECT, where `ASMLIFT_CANDCACHE` is per process. */
  candidateCache?: 'off';
}

// Substituted values are injected RAW so the template owns its quoting (a natural template
// writes `PRE="{out}.i"` — a pre-quoted substitution would put literal quotes in the
// filename). The guarantee instead: every substituted value is shell-inert, or the compile
// throws. Paths come from mkdtemp (always safe); the symbol can come from UNVALIDATED
// pasted-asm labels, so this check is load-bearing against shell injection.
const SHELL_SAFE = /^[A-Za-z0-9_./+-]+$/;
const safe = (value: string, what: string): string => {
  if (!SHELL_SAFE.test(value)) {
    throw new Error(`${what} contains shell-unsafe characters, refusing to substitute: ${JSON.stringify(value)}`);
  }
  return value;
};

/** Longest a token may be before the scan drops it. A 430-character absolute operand is an
 *  ordinary deep checkout, and dropping it was a silent hole — this bound exists only to stop a
 *  template that embeds a whole here-doc from being stat'ed line by line. */
const TOKEN_MAX = 4096;

/**
 * A DE-GLUER, and the key to `INJECTED_FILE_FLAGS` and `FLAG_FILE_FLAGS`. Three jobs, all of them
 * lookups by a flag NAME: un-glue an operand from its flag; say which flag injects a header whose
 * own directory must be measured; say which flag names a file holding more flags. Naming all
 * three because "a de-gluer and nothing more" makes a reader mis-read the loop.
 *
 * THE MECHANISM IS `hashPath`, not this table. The stamp tries EVERY token as a path and lets
 * `statSync` answer whether it is one; the asymmetry licenses that — OVER-hashing costs a cold
 * start, UNDER-hashing serves a stale object. What the filesystem cannot answer is a token whose
 * operand is GLUED to a flag: `-Iinc` is not a path, `inc` is, and no amount of stat'ing `-Iinc`
 * will find it.
 *
 * WHAT EACH HALF EARNS, ablated separately against `candcache-dirflags.test.ts` (62 tests):
 * with the operand scan replaced by `[]`, 43 passed / 19 failed — the table earns every ATTACHED
 * spelling, the flag-file bodies and the glob directory. With the `/[/.]/.test(tok)` guard put
 * back in front of the token scan, 58 passed / 4 failed — and those four are the shapes no list
 * reaches: an operand two tokens from its flag (`-Xpreprocessor -I -Xpreprocessor inc`), a flag
 * that does not exist yet, an operand in a variable the template assigns, and a quoted operand
 * with a space in it. Neither half is the mechanism; the table's failure mode is the dangerous
 * one, because a list that is the mechanism has an INVISIBLE incompleteness — which is what got
 * `tools.asmlift.cacheInputs` deleted — while a list that only un-glues has a visible one.
 *
 * Every entry has a legal GLUED or `=` spelling on the compilers this repo drives, which is the
 * only thing that earns a row — checked rather than assumed, because a row that can never fire is
 * a branch that cannot be taken: `gcc-14 -imultilibzz -fsyntax-only x.c` and `arm-none-eabi-gcc
 * -imultilibzz …` both accept it (Apple clang rejects `-imultilib` in EVERY spelling, since it
 * does not know the flag at all).
 *
 * Longest match first, so `-isystem` is not read as `-I` with the operand `system`.
 */
const PATH_FLAGS: readonly string[] = [
  '--include-directory-after',
  '--include-with-prefix-before',
  '--include-with-prefix-after',
  '--include-with-prefix',
  '--include-directory',
  '--include-prefix',
  '--sysroot',
  '-iwithprefixbefore',
  '-iwithprefix',
  '-iframeworkwithsysroot',
  '-iframework',
  '-imultilib',
  '-idirafter',
  '-isystem-after',
  '-cxx-isystem',
  '-isysroot',
  '-isystem',
  '-include',
  '-imacros',
  '-iprefix',
  '-iquote',
  '-specs',
  '-I',
  '-B',
  '-L',
  '-F',
].sort((a, b) => b.length - a.length);

/** Flags whose operand is a FILE the compile injects, not a directory. gcc resolves that file's
 *  own `#include "…"` from the DIRECTORY THE FILE IS IN, which is never an operand and never a
 *  token — so the directory joins the measurement too. (`-include pre.h` where `pre.h` says
 *  `#include "sub/x.h"` served a stale object; the injected file was measured and its closure
 *  was not.) */
const INJECTED_FILE_FLAGS = new Set(['-include', '-imacros']);

/** Flags whose operand is a file holding MORE FLAGS. Measuring the file's bytes is not measuring
 *  what it names: `@opts` containing `-iquote inc` was hashed as a file while `inc/` was not,
 *  which made a response file look SAFER than writing the flag inline. Its contents get BOTH
 *  halves of the outer mechanism — the de-gluer table, and every token tried as a path — because
 *  half of it is the half that leaks. */
const FLAG_FILE_FLAGS = new Set(['-specs']);

/** Runtimes that put the compiler's real inputs where this namespace cannot read them. TWO
 *  classes, and they refuse for different reasons:
 *
 *  (1) AN OPAQUE ROOT — a container IMAGE named by a mutable TAG (`i386/ubuntu:bionic` rebuilt
 *      tomorrow is a different compiler under the same name, invisible to every token, every
 *      environment variable and the stamp probe alike, since the probe compiles THROUGH the
 *      container), ANOTHER HOST over `ssh`, or a sandbox root the template never spells. Naming
 *      the image would take its DIGEST — `docker image inspect --format '{{.Id}}'` — which this
 *      stamp does not do, so the answer is a refusal. That is precisely the guard the deleted
 *      `tools.asmlift.cacheInputs` opt-in was providing by omission for the benchmark's
 *      `gcc2.7.2` row, and it must not fall out silently with it.
 *
 *  (2) AN EMULATOR OR BINARY TRANSLATOR — `wine`, `box64`, `qemu-*`. Here the compiler IS named
 *      on the command line and IS hashed by content; what is not named is the runtime it executes
 *      against, which is part of the compiler for these purposes: wine's prefix and DLL overrides,
 *      the guest libraries a qemu/box64 run resolves. Neither is a token, and a `WINEPREFIX`
 *      rebuilt in place moves neither the template nor any file this stamp reaches.
 *      SAY THE REACH COST, because it lands on the projects this cache is for: a GC/Wii or PS1 decomp
 *      running mwcc or psyq under wine gets no candidate cache and one `REFUSED` line per run.
 *      The native shim this repo uses for the same job — `wibo` — is measured, cached, and not on
 *      this list.
 *
 *  SAID PLAINLY, because it is the one place this file uses a list where it should use a
 *  measurement: this is a DENY-LIST, and a deny-list's miss is on the STALE-OBJECT side of the
 *  asymmetry, not the cold-start side. It has been widened twice from the six names that shipped
 *  — first over twelve measured misses (`docker-compose`, `podman-remote`, `distrobox-enter`,
 *  `toolbox`, `limactl`, `chroot`, `ssh`, `wine`, `qemu-*`, `proot`, `bwrap`, `box64`), then over
 *  nine more that returned `undefined` and are current elsewhere, two of them installed on the
 *  box this was written on (`orb`, `kubectl`; also `container`, `colima`, `udocker`, `crun`,
 *  `runc`, `nix-shell`, `multipass`) — and the next one is always constructible. The GENERAL escape is not another name
 *  here: it is `tools.asmlift.candidateCache: off` in the project's own decomp.yaml — a refusal a
 *  project can spell for itself, whose worst case is a cold start.
 *
 *  THE FALSE-POSITIVE COST, kept on purpose: the check reads EVERY token, not only the word in
 *  command position, because `env X=1 docker run` and `xargs docker run` are ordinary and a
 *  command-position rule would miss them silently. So a runtime word inside a QUOTED string
 *  (`echo "no ssh here"`) refuses the project. That is loud and costs a cold start, which is the
 *  side of the asymmetry this file always takes. A runtime word in a COMMENT is not one, because
 *  `stripShellComments` runs first. */
const OPAQUE_RUNTIMES = new Set([
  'docker',
  'docker-compose',
  'podman',
  'podman-compose',
  'podman-remote',
  'nerdctl',
  'ctr',
  'apptainer',
  'singularity',
  'distrobox',
  'distrobox-enter',
  'toolbox',
  'toolbx',
  'lima',
  'limactl',
  'incus',
  'lxc',
  'lxc-execute',
  'machinectl',
  'systemd-nspawn',
  'chroot',
  'ssh',
  'proot',
  'bwrap',
  'firejail',
  'wine',
  'wine64',
  'box64',
  'box86',
  'orb',
  'container',
  'colima',
  'udocker',
  'crun',
  'runc',
  'nix-shell',
  'multipass',
  'kubectl',
]);
const OPAQUE_RUNTIME_RE = /^qemu-/;
const isOpaqueRuntime = (name: string): boolean => OPAQUE_RUNTIMES.has(name) || OPAQUE_RUNTIME_RE.test(name);

/** The opaque runtime a template runs, if it runs one — checked on the BASENAME, so
 *  `tools/dockerize` is not `docker`, and through a variable, whether the value comes from the
 *  ENVIRONMENT (`"$ASMLIFT_DOCKER"`, how every dockerized template in this repo spells it) or
 *  from an assignment IN THE TEMPLATE (`DOCKER=docker; $DOCKER run …`, which defeated the first
 *  spelling of this check and is the idiom every template in this repo uses for other values). */
export function containerRuntimeNamedBy(template: string, env: NodeJS.ProcessEnv = process.env): string | undefined {
  const assigned = new Map<string, string>();
  for (const m of stripShellComments(template).matchAll(/(?:^|[\s;&|(])([A-Za-z_]\w*)=("[^"]*"|'[^']*'|[^\s;&|)]*)/g)) {
    assigned.set(m[1], m[2].replace(/^["']|["']$/g, ''));
  }
  const word = (w: string): string | undefined => (isOpaqueRuntime(basename(w.trim())) ? w.trim() : undefined);
  for (const tok of scanTokens(template)) {
    const m = /^\$\{?([A-Za-z_]\w*)\}?$/.exec(tok);
    const hit = m ? word(assigned.get(m[1]) ?? env[m[1]] ?? '') : word(tok);
    if (hit !== undefined) {
      return hit;
    }
  }
  return undefined;
}

/** A shell COMMENT is not argv. `sh` drops from an unquoted `#` that begins a word to the end of
 *  the line, so nothing in there is read, executed or resolved — and a decomp `compiler:` template
 *  is multi-line shell where a `#` line is ordinary.
 *
 *  MEASURED, and it is why every scan in this file starts here. `# remember to clean build` put the
 *  project's OWN OUTPUT TREE in the namespace, so every rebuild was a cold start — the payoff of
 *  this whole file, spent by a word in a comment. `# see [1] and *.o notes` promoted prose to the
 *  glob rule. `# our CI also builds this in docker` and `# copy with scp/ssh` each REFUSED the
 *  project's cache outright, with a message asserting the compile runs through a container that
 *  it does not.
 *
 *  Dropping the text loses no measurement: `stamp()` hashes the template's RAW bytes
 *  unconditionally, so editing a comment still moves the namespace. Quotes are tracked because
 *  `-DTAG='#1'` is a `#` that is not a comment, and an UNTERMINATED quote keeps the rest of the
 *  text — the over-scanning side, which costs a cold start. */
function stripShellComments(template: string): string {
  let out = '';
  let quote: string | undefined;
  let prev = '';
  for (let i = 0; i < template.length; i++) {
    const c = template[i];
    if (quote !== undefined) {
      out += c;
      if (c === quote) {
        quote = undefined;
      }
      prev = c;
      continue;
    }
    if (c === '"' || c === "'") {
      quote = c;
      out += c;
      prev = c;
      continue;
    }
    if (c === '#' && (prev === '' || /[\s;&|(]/.test(prev))) {
      while (i < template.length && template[i] !== '\n') {
        i++;
      }
      out += '\n';
      prev = '\n';
      continue;
    }
    out += c;
    prev = c;
  }
  return out;
}

/** Every token of a compile template that a path flag could be attached to, IN ARGV ORDER — the
 *  list `templatePathOperands` walks positionally, so nothing derived may be interleaved into it.
 *  A comma list (`-Wa,-Iinc`, `-Wp,-I,inc`) is a nested argv the driver forwards, so its pieces
 *  are tokens too; a token is kept as well as split, because `--sysroot=a,b` is one path. */
function flagScanTokens(template: string): string[] {
  const out: string[] = [];
  for (const tok of stripShellComments(template).split(/[\s"'<>|;()]+/)) {
    if (!tok || tok.startsWith('{{') || tok.length > TOKEN_MAX) {
      continue;
    }
    out.push(tok);
    if (tok.includes(',')) {
      for (const piece of tok.split(',')) {
        if (piece && piece.length <= TOKEN_MAX) {
          out.push(piece);
        }
      }
    }
  }
  return out;
}

/** THE tokenizer — every string in a template that could name a path, argv order first and the
 *  derived spellings after. One function, because three call sites tokenizing the same template
 *  three slightly different ways is three chances to disagree about what a token is.
 *
 *  Derived, and each one was a measured stale object:
 *  - the right-hand side of an ASSIGNMENT (`INC=inc; … -I $INC`) — the operand the compile reads
 *    never appears as a bare token, and klonoa's own template already assigns four variables, so
 *    this shape is one edit away from the corpus rather than hypothetical;
 *  - the contents of a QUOTED SPAN (`-iquote "my inc"`) — the splitter treats a quote as a
 *    separator, so a path with a space in it arrives as two tokens that name nothing. */
function scanTokens(template: string): string[] {
  const text = stripShellComments(template);
  const out = flagScanTokens(text);
  const push = (s: string | undefined): void => {
    if (s && !s.includes('{{') && s.length <= TOKEN_MAX) {
      out.push(s);
    }
  };
  for (const m of text.matchAll(/(?:^|[\s;&|(])[A-Za-z_]\w*=("[^"]*"|'[^']*'|[^\s;&|)]*)/g)) {
    push(m[1].replace(/^["']|["']$/g, ''));
  }
  for (const m of text.matchAll(/"([^"\n]*)"|'([^'\n]*)'/g)) {
    push(m[1] ?? m[2]);
  }
  return out;
}

/** THE PROJECT ROOT IS NOT A DIRECTORY OPERAND, and synthesizing `.` as one is not the
 *  over-hashing side of the asymmetry — it is the side that has no cache at all.
 *
 *  Two rules could mint it and neither does: a glob with no directory part (`rm -f *.o` -> `.`)
 *  and an injected header at the top level (`-include global.h` -> `dirname` -> `.`). Neither
 *  operand is a word anyone wrote; `.` is the whole checkout, and `hashPath` walks it
 *  recursively.
 *  MEASURED on this box, against a 20 000-entry / 512 MiB stamp budget:
 *
 *    pokeemerald 29 126 entries · af 25 901 · a real klonoa dev checkout 47 211  -> over budget,
 *      so the stamp THROWS and `candCache` refuses the project outright, naming the checkout
 *      root rather than the flag that put it there;
 *    marioparty3 19 735 -> 98.7% of the budget, cached today and refused by one `git gc`;
 *    the depth-0 FILES of a project root are the baserom: pokeemerald 26 files / 131 114 078
 *      bytes, klonoa 24 / 34 124 942 — a quarter of the byte budget hashed per process, for a
 *      file no compile reads;
 *    and where it fits (the bench klonoa checkout, 6 775), the namespace then tracks `build/`
 *      and `.git/`, so every rebuild is a cold start and the cache never warms.
 *
 *  So this is a published RESIDUAL, not a measurement: a glob with no `/` in it, and the quoted
 *  includes of an injected header that lives at the top level, are read by the compile and not
 *  seen here. `docs/ranked-repro.md` lists both, and the answers are the same as for every other
 *  residual — `ASMLIFT_CANDCACHE=verify`, or `tools.asmlift.candidateCache: off`. A subdirectory
 *  operand (`-include inc/pre.h`, `cat inc/*.h`) is bounded and is still measured. */

/** The paths a compile template names, in token order and de-duplicated by spelling: every path
 *  flag's operand, `@response` files and `-specs` files (they hold compile flags, so their
 *  CONTENTS are scanned too), the directory an injected `-include` file resolves its own quoted
 *  includes from, and the DIRECTORY PART of a glob. A glob is path-LIKE and is not a path —
 *  `inc/*.h` has both a `/` and a `.`, and `statSync` says no — yet what it expands to is read
 *  by the compile as surely as an `-I` operand is. A glob or an injected header with NO directory
 *  part names the project root, which is a published residual and not an operand.
 *
 *  `readDir` turns on the flag-FILE expansion: with it, a response or specs file that exists
 *  under it is read and scanned as a template in its own right. Without it the function stays
 *  pure, which is what the operand-parser unit tests want. */
export function templatePathOperands(template: string, readDir?: string, depth = 0): string[] {
  const toks = flagScanTokens(template);
  const out: string[] = [];
  const seen = new Set<string>();
  const take = (operand: string | undefined): void => {
    if (!operand || operand.startsWith('{{') || operand.startsWith('-') || seen.has(operand)) {
      return;
    }
    seen.add(operand);
    out.push(operand);
  };
  /** A file that holds more flags: measure what IT names, not only its bytes. Bounded in depth
   *  (a response file may name another) and in size, and every failure is silent-and-inert here
   *  because the file itself is still hashed by `hashPath`, which refuses out loud if it is
   *  there and unreadable. */
  const expandFlagFile = (operand: string): void => {
    if (readDir === undefined || depth >= 4) {
      return;
    }
    const p = isAbsolute(operand) ? operand : resolve(readDir, operand);
    let body: string;
    try {
      if (statSync(p).size > 1024 * 1024) {
        return;
      }
      body = readFileSync(p, 'utf8');
    } catch {
      return;
    }
    for (const nested of templatePathOperands(body, readDir, depth + 1)) {
      take(nested);
    }
    // AND every token of the body as a path in its own right, which is the same thing `stamp()`
    // does to the outer template and the reason the `/[/.]/` guard could go. Scanning the body
    // with the flag table ALONE re-imported "the list is the mechanism" one level down, on the
    // stale-object side: `@opts` holding `--fake-include-dir inc`, `-Xpreprocessor -I
    // -Xpreprocessor inc`, or the bare word `inc` served a stored object after `inc/` moved,
    // while the SAME TEXT written inline was covered. A response file must not be the safer
    // place to hide an input.
    for (const tok of scanTokens(body)) {
      take(tok);
    }
  };
  for (let i = 0; i < toks.length; i++) {
    const tok = toks[i];
    if (/[*?[]/.test(tok)) {
      // Only the directory: the pattern itself cannot be stat'ed, and hashing the whole directory
      // is the over-hashing side of the asymmetry, which costs a cold start.
      const dir = tok.slice(0, tok.lastIndexOf('/') + 1);
      take(dir === '' ? undefined : dir.replace(/\/+$/, '') || '/');
      continue;
    }
    if (tok.startsWith('@') && tok.length > 1) {
      take(tok.slice(1));
      expandFlagFile(tok.slice(1));
      continue;
    }
    const flag = PATH_FLAGS.find((f) => tok.startsWith(f));
    if (flag === undefined) {
      continue;
    }
    const rest = tok.slice(flag.length);
    // Exactly the flag: the operand is the next token (`-iquote inc`). Otherwise it is attached,
    // with or without the `=` the long spellings use (`-Iinc`, `--sysroot=inc`, `-specs=x.specs`).
    const operand = rest === '' ? toks[i + 1] : rest.startsWith('=') ? rest.slice(1) : rest;
    take(operand);
    if (operand === undefined || operand.startsWith('-') || operand.startsWith('{{')) {
      continue;
    }
    if (INJECTED_FILE_FLAGS.has(flag)) {
      const dir = dirname(operand);
      take(dir === '.' ? undefined : dir);
    }
    if (FLAG_FILE_FLAGS.has(flag)) {
      expandFlagFile(operand);
    }
  }
  return out;
}

/** Every directory a template `cd`s into that names a real one, as an EXTRA base a relative
 *  operand is resolved against. `cd sub; … -I inc` reads `sub/inc`, and resolving `inc` against
 *  the decomp.yaml's directory alone measured nothing at all. Over-hashing on purpose: both
 *  bases are tried, and a base that holds no such path costs one failed `statSync`. A `cd` whose
 *  target this cannot resolve (`cd "$(dirname …)"`) contributes no base — the residual, and it
 *  is why `tools.asmlift.candidateCache: off` exists. */
function cdBases(template: string, cwd: string): string[] {
  const out: string[] = [];
  for (const m of stripShellComments(template).matchAll(/(?:^|[\s;&|(])cd\s+("[^"]*"|'[^']*'|[^\s;&|)]+)/g)) {
    const arg = m[1].replace(/^["']|["']$/g, '');
    if (!arg || arg.includes('$') || arg.includes('{{')) {
      continue;
    }
    const p = isAbsolute(arg) ? arg : resolve(cwd, arg);
    try {
      if (statSync(p).isDirectory()) {
        out.push(p);
      }
    } catch {
      /* not a directory here — no base */
    }
  }
  return out;
}

/** Build a CandidateCompiler from a `decomp.yaml` command template. `{{inputPath}}` and
 *  `{{outputPath}}` are REQUIRED placeholders (substituted with absolute paths);
 *  `{{symbol}}` is optional. The placeholder style matches other decomp tools' `compiler`
 *  templates, so a project's tool blocks read uniformly. The command runs via `sh -ec` — EVERY
 *  step must succeed, not just the last one: gcc-2.9-family compilers exit nonzero on a hard
 *  error (an undeclared identifier, even an invalid flag) yet still write a PARTIAL .s with the
 *  erroring statements deleted, so without `-e` a later assemble step "succeeds" and a silently
 *  TRUNCATED object gets scored (found scoring real 22/28/38 phantoms in the klonoa dogfood).
 *  A non-zero exit or a missing output object throws with the full command + its stderr —
 *  configured means configured, there is no fallback. */
export function compilersFromCommand(template: string, opts: CompileCommandOptions = {}): CommandCompilers {
  if (!template.includes('{{inputPath}}') || !template.includes('{{outputPath}}')) {
    throw new Error(`compiler command must contain {{inputPath}} and {{outputPath}} placeholders — got: ${template}`);
  }
  // An unrecognized {{...}} placeholder is a config mistake (e.g. another tool's
  // {{functionName}} pasted verbatim) — name it now instead of a baffling shell failure.
  const unknown = template.replaceAll(/\{\{(inputPath|outputPath|symbol)\}\}/g, '').match(/\{\{\w+\}\}/);
  if (unknown) {
    throw new Error(
      `compiler command has an unknown placeholder ${unknown[0]} — supported: {{inputPath}}, {{outputPath}}, {{symbol}}`,
    );
  }
  // ONE scratch directory per WORKER, emptied before each compile — not one per candidate.
  // mkdtemp never removes anything, so a per-candidate directory leaked one per compile: a
  // ranked run over 20k candidates left 20k of them behind, and the temp dir had accumulated
  // 1.5M. Emptied rather than reused: a step that exits 0 without writing its output must still
  // fail LOUD, and a surviving sibling from the previous candidate is exactly what would let it
  // pass (the same class of silent truncation the `sh -ec` note above is about).
  //
  // Reuse is safe HERE because the template runs a fresh process per compile against the host
  // filesystem. It is NOT safe for a template that keeps a long-lived container with this
  // directory's parent bind-mounted: the benchmark's dockerized toolchains measured ~30% of
  // compiles failing on a reused path (apps/benchmark/src/compile/util.ts `scratchSlot`), which
  // is why they still mkdtemp per candidate.
  const slot = (): (() => string) => {
    let dir: string | undefined;
    return () => {
      if (dir === undefined) {
        dir = mkdtempSync(join(tmpdir(), 'asmlift-usercc-'));
        return dir;
      }
      rmSync(dir, { recursive: true, force: true });
      mkdirSync(dir);
      return dir;
    };
  };

  // One template execution, in two halves: `stage` writes the input and builds the command,
  // `verdict` reads the exit status — shared verbatim by the sync and async runners so the two
  // can never diverge on what counts as a failed compile or on how it is reported.
  //
  // `transient` is the half a MESSAGE cannot carry: this machine had a bad minute, the compiler
  // never gave a verdict, and nothing about the outcome may be stored.
  type Verdict = { ok: boolean; transient: boolean; cmd: string; err: string };
  const stage = (dir: string, content: string, symbol: string, ext: 'c' | 'p') => {
    const inPath = join(dir, `cand.${ext}`);
    const outPath = join(dir, 'cand.o');
    writeFileSync(inPath, content);
    const cmd = template
      .replaceAll('{{inputPath}}', safe(inPath, '{{inputPath}}'))
      .replaceAll('{{outputPath}}', safe(outPath, '{{outputPath}}'))
      .replaceAll('{{symbol}}', safe(symbol, 'the symbol name'));
    return { outPath, cmd };
  };
  // The scratch DIRECTORY is collapsed out of every failure message. It is an mkdtemp accident:
  // two runs of the identical failure print different text, so a rejection replayed from the cache
  // (which stores the message from the run that produced it) would not be equal in RESULT to a
  // fresh one — and the ranked path publishes that first line as `dropped[].error`. Collapsing it
  // makes the cached and uncached spellings identical, and takes a machine path out of published
  // output at the same time.
  const verdict = (status: number | null, output: string, cmd: string, outPath: string): Verdict => {
    const scrub = (t: string): string => t.split(dirname(outPath)).join('<scratch>');
    // A KILLED compile is not a rejection, and `sh` is what hides that here. The template always
    // runs through `sh -ec`, and a shell reports a killed child as exit 128+signal — a SIGKILLed
    // compiler arrives as a perfectly ordinary `exit 137`, which the negative-entry guard matched
    // and stored FOREVER (`sh: line 1: 15022 Killed: 9` in the stored body). Reach is not
    // hypothetical: candidate compiles have no timeout, `docker run` exits 137 on an OOM-killed
    // container, and a bench run forks 8–16 shards. `status === null` is the same thing when the
    // shell ITSELF is killed. Both are transient and neither may be stored.
    if (status === null || status >= 128) {
      return {
        ok: false,
        transient: true,
        cmd,
        err: scrub(
          `compile command did not run to completion (${status === null ? 'killed by a signal' : `exit ${status} — killed by signal ${status - 128}`}): ` +
            `${cmd}\n${output.trim()}`,
        ),
      };
    }
    if (status !== 0) {
      return {
        ok: false,
        transient: false,
        cmd,
        err: scrub(`compile command failed (exit ${status}): ${cmd}\n${output.trim()}`),
      };
    }
    if (!existsSync(outPath)) {
      return {
        ok: false,
        transient: false,
        cmd,
        err: scrub(`compile command exited 0 but produced no object at {{outputPath}}: ${cmd}`),
      };
    }
    return { ok: true, transient: false, cmd: outPath, err: '' };
  };

  const mainSlot = slot();
  const execute = (content: string, symbol: string, ext: 'c' | 'p'): Verdict => {
    const { outPath, cmd } = stage(mainSlot(), content, symbol, ext);
    const r = spawnSync('sh', ['-ec', cmd], { encoding: 'utf8', cwd: opts.cwd });
    return verdict(r.status, r.stderr || r.stdout, cmd, outPath);
  };
  // Two DEDICATED slots for the namespace stamp probe. Never `mainSlot`: the stamp is reached
  // from `warm()` and, compiled into the slot a candidate has just written, it overwrites that
  // candidate's object — measured once as 8 poisoned keys, 26 moved report fields and 2 rows
  // flipped nonmatch to noncompile, with every other gate green.
  const stampSlot = slot();
  const stampSlot2 = slot();
  const executeInSlot = (dir: string, content: string, symbol: string, ext: 'c' | 'p'): Verdict => {
    const { outPath, cmd } = stage(dir, content, symbol, ext);
    const r = spawnSync('sh', ['-ec', cmd], { encoding: 'utf8', cwd: opts.cwd });
    return verdict(r.status, r.stderr || r.stdout, cmd, outPath);
  };
  const executeIn = (dir: string, content: string, symbol: string, ext: 'c' | 'p') =>
    new Promise<Verdict>((res) => {
      const { outPath, cmd } = stage(dir, content, symbol, ext);
      const p = spawn('sh', ['-ec', cmd], { cwd: opts.cwd });
      let out = '',
        err = '';
      // DECODED as it arrives, not concatenated as Buffers: `'' + buf` decodes each chunk on its
      // own, so a multi-byte character straddling a chunk boundary would come out as replacement
      // characters here and not in the sync runner (spawnSync decodes the whole buffer at once).
      // The two must report a failed compile with the same text.
      p.stdout.setEncoding('utf8');
      p.stderr.setEncoding('utf8');
      p.stdout.on('data', (d: string) => (out += d));
      p.stderr.on('data', (d: string) => (err += d));
      // A shell that never starts is reported like any other failed compile, not as a rejected
      // promise: the ranked driver reads a THROWN compile the same way whichever runner produced
      // it, and a second `res` after `close` is a no-op.
      p.on('error', (e) =>
        res({ ok: false, transient: true, cmd, err: `compile command failed to start: ${cmd}\n${e.message}` }),
      );
      p.on('close', (code) => res(verdict(code, err || out, cmd, outPath)));
    });

  // Which WORLD candidates compile in — PROBED, never configured. Two worlds exist:
  //   • SELF-DECLARED: a bare template compiles the candidate alone, so it needs asmlift's
  //     typedef prelude plus the candidate's synthesized declaration block (declare.ts);
  //   • HEADERS: the template injects project headers, which already own u8/u16/… AND every
  //     global/struct declaration — C89 hard-errors on a duplicate typedef and on a duplicate
  //     struct definition, so prelude and synthesized decls must BOTH be dropped.
  // The compiler itself is the only authority, so ask it once: compile the prelude + a
  // REPRESENTATIVE declaration block (one exemplar of every construct synthesis emits) + one
  // harmless decl. The block is representative rather than per-candidate because decls vary
  // per candidate while the verdict is per COMPILER INSTANCE (cached) — and real blocks use
  // exactly this vocabulary, so accepting the exemplar accepts them all.
  // Success ⇒ self-declared world. Failure ⇒ try the bare decl alone: success confirms the
  // headers collision (drop prelude + decls); failure means the TEMPLATE is broken — keep
  // everything so the first real candidate fails with the template's own loud diagnostics.
  // Exit-code-only: no error-message parsing (gcc-2.9/IDO/mwcc all format differently).
  // The cross-run candidate-object cache on the project-template path (candcache.ts). ON unless
  // ASMLIFT_CANDCACHE says otherwise, and ON for any project's own command, because everything the
  // command reads is now MEASURED rather than declared.
  //
  // The NAMESPACE is a measurement, not a version constant: the template text, the cwd, the
  // content hash of every directory a path FLAG names (`-iquote include`, recursively), of every
  // existing file the template names
  // (`./tools/agbcc/bin/agbcc`, `tools/preproc/preproc`, `charmap.txt`), of every command it
  // resolves on $PATH, the value of every environment variable it reads, and, decisively, the
  // OBJECT BYTES this very template produces for one fixed probe TU, compiled twice in two
  // different directories so the compiler itself answers whether its output is a pure function
  // of its input.
  const sha256 = (b: Buffer | string): string => createHash('sha256').update(b).digest('hex');
  /** A file the shell would RUN, as opposed to one a compile merely reads. Only those have a
   *  delegate chain worth following. */
  const isExecutableFile = (p: string): boolean => {
    try {
      const st = statSync(p);
      return st.isFile() && (st.mode & 0o111) !== 0;
    } catch {
      return false;
    }
  };
  /** A directory measurement is unbounded by nature: `--sysroot /` names a filesystem, and a
   *  namespace that walks it is a hang rather than a cold start. The budget makes running out
   *  LOUD — it throws, `candCache` turns the throw into a refusal, and the run compiles uncached.
   *  Truncating the walk instead would be the other thing, and the other thing is a stale
   *  object.
   *
   *  The budget is one running total for the whole STAMP, not per input — so the entry the walk
   *  dies on is an accident of walk order and is not what a reader can act on. The message names
   *  the OPERAND the walk started from as well, which is the half that says what to change. */
  class MeasurementTooLarge extends Error {}
  /** `statSync` said this IS a path, and then the READ of it failed. That is NOT "the token was
   *  not a path": the compile reads it and the namespace cannot, so the namespace is incomplete,
   *  and an incomplete namespace is a stale object.
   *
   *  MEASURED, and it is why this class exists: an include directory at mode 0311 — searchable,
   *  not listable, which is exactly what a compile needs and a walk does not — served a stale
   *  object with no stderr line, because every non-budget error was swallowed into "contributes
   *  nothing". Worse in the transient case: one `EIO` on one `readdirSync` mints a PERMANENT
   *  incomplete namespace, which is the same silent-wrong-answer shape `storableRejection`
   *  refuses to store transient rejections for. Loud refusal instead. */
  class MeasurementUnreadable extends Error {}
  const budget = { entries: 20000, bytes: 512 * 1024 * 1024 };
  /** `root` is the operand this walk began at — carried down the recursion for the diagnostics
   *  only. `inDir` says the entry was NAMED by a `readdirSync` we already succeeded at, which
   *  changes what a failed `statSync` means. */
  const hashPath = (
    h: ReturnType<typeof createHash>,
    tag: string,
    p: string,
    root: string = p,
    inDir = false,
  ): boolean => {
    let st;
    try {
      st = statSync(p);
    } catch {
      if (inDir) {
        // A directory entry the listing named and a stat cannot see: a dangling symlink, or a
        // file deleted under the walk. Refusing over a dangling symlink would refuse half the
        // toolchains on earth, so the NAME still joins the digest — strictly more than the old
        // spelling contributed — and the walk goes on.
        h.update('unstattable:' + tag);
        return false;
      }
      // Not a path HERE: a flag word, a shell builtin, an operand that is simply absent. It
      // contributes nothing, and needs no MISSING marker — the template TEXT is hashed
      // unconditionally, so absent -> present still moves the namespace.
      return false;
    }
    if (--budget.entries < 0) {
      throw new MeasurementTooLarge(
        `refusing to measure ${root}: over 20000 files in one namespace stamp (the walk reached ` +
          `${p}). A namespace that stops walking is an incomplete namespace, which is a stale ` +
          `object — so nothing is cached`,
      );
    }
    if (st.isDirectory()) {
      let entries;
      try {
        entries = readdirSync(p, { withFileTypes: true });
      } catch (e) {
        throw new MeasurementUnreadable(
          `refusing to measure ${root}: cannot list the directory ${p} ` +
            `(${e instanceof Error ? e.message : String(e)}). The compile can read what is in ` +
            `there and this namespace cannot, so nothing is cached`,
        );
      }
      // A directory is hashed by its whole contents, recursively and in sorted order: that is
      // the entire point of measuring it (`-I ./inc` reaches `inc/k.h`, which no token set and
      // no probe TU can see).
      h.update('dir:' + tag);
      for (const e of entries.sort((a, b) => (a.name < b.name ? -1 : 1))) {
        hashPath(h, tag + '/' + e.name, join(p, e.name), root, true);
      }
      return true;
    }
    if (!st.isFile()) {
      return false;
    }
    if ((budget.bytes -= st.size) < 0) {
      throw new MeasurementTooLarge(
        `refusing to measure ${root}: over 512MiB in one namespace stamp (the walk reached ${p}). ` +
          `An incomplete namespace is a stale object, so nothing is cached`,
      );
    }
    let bytes;
    try {
      bytes = readFileSync(p);
    } catch (e) {
      throw new MeasurementUnreadable(
        `refusing to measure ${root}: cannot read the file ${p} ` +
          `(${e instanceof Error ? e.message : String(e)}). The compile can read it and this ` +
          `namespace cannot, so nothing is cached`,
      );
    }
    // Both updates run only after the read SUCCEEDED. A file this walk cannot read contributes
    // nothing here because it never gets here — `MeasurementUnreadable` throws on a failed read.
    // That is not a general claim about the digest: a directory entry `statSync` cannot see joins
    // it as `unstattable:`, deliberately, because refusing over a dangling symlink would refuse
    // half the toolchains on earth.
    h.update(tag);
    h.update(sha256(bytes));
    return true;
  };
  /** One entry of a delegate chain. A measurement entry (`UNRESOLVED:`, `ENV:`) is hashed as the
   *  STRING it is — it is an answer, not a file, and skipping it drops the answer. A file is
   *  hashed by CONTENT under its BASENAME, never its absolute path, so that a toolchain MOVED but
   *  not changed keeps its digest.
   *
   *  It does NOT follow that two worktrees holding byte-identical toolchains share a namespace:
   *  `h.update(cwd)` in `stamp()` keys the whole namespace on the absolute working directory, so
   *  two byte-identical worktrees with an identical template and an identical `inc/` measured as
   *  two namespaces. A tag is not a key; content is what decides. */
  const hashChain = (h: ReturnType<typeof createHash>, tok: string, entry: string): void => {
    if (isChainMeasurement(entry)) {
      h.update(tok + '>' + entry);
      return;
    }
    hashPath(h, tok + '>' + basename(entry), entry);
  };
  const stamp = (): string => {
    const h = createHash('sha256');
    const cwd = resolve(opts.cwd ?? process.cwd());
    // Checked FIRST: a refusal here saves two probe compiles, and through a container those are
    // two `docker run`s.
    const runtime = containerRuntimeNamedBy(template);
    if (runtime !== undefined) {
      throw new Error(
        `the compile command runs the compiler through ${runtime}, which puts it somewhere this ` +
          `namespace cannot read it — inside an image named by a mutable TAG, on another host, or ` +
          `under a sandbox root the template never spells. An image rebuilt under the same tag is ` +
          `a new compiler serving old objects. Refusing rather than hashing a stand-in. Declare ` +
          `tools.asmlift.candidateCache: off in decomp.yaml to make this refusal the project's own ` +
          `and silence this line`,
      );
    }
    h.update('command/v1');
    h.update(template);
    h.update(cwd);
    // THIS MODULE'S OWN BYTES. The bench pipeline hashes its harness code (`compile/agbcc.ts`,
    // `compile/util.ts`) because that code shapes what the compiler is handed; this one shapes it
    // too, and it shapes something the probe object structurally cannot see — 77% of what a warm
    // store SERVES is a stored REJECTION, and `verdict()` above builds the text that is stored and
    // then published as `ranked.dropped[].error`. The probe only ever exercises the success path,
    // so perturbing that text left the namespace unmoved and the store replayed the old spelling.
    // Cheap, too: this file has moved 3 times in the repo's whole history, against 4 for
    // `compile/util.ts`, which has been in a namespace all along.
    h.update('self:');
    h.update(sha256(readFileSync(fileURLToPath(import.meta.url))));
    // (1) every template token that names an existing FILE: the project's own
    //     `./tools/agbcc/bin/agbcc`, `tools/preproc/preproc`, `charmap.txt`, hashed by content.
    // (2) every remaining token that RESOLVES ON $PATH: `arm-none-eabi-cpp`, `arm-none-eabi-as`,
    //     `cc`, hashed by content too. MEASURED WHY: the probe object below did NOT move between
    //     two different pinned agbcc revisions (they agree on the probe TU), so a namespace
    //     resting on the probe alone would have served one compiler's objects for the other.
    // (3) every shell variable the template READS but does not itself assign: that is an
    //     external input choosing the compiler, so its value (and its content, if it names a
    //     file) joins the stamp.
    const assigned = new Set<string>();
    for (const m of stripShellComments(template).matchAll(/^\s*([A-Za-z_]\w*)=/gm)) {
      assigned.add(m[1]);
    }
    // ONE hashPath per resolved path, whichever scan reaches it first. The token scan and the
    // operand scan share ONE running budget, so a directory both reach would be walked twice on
    // an effective budget of 10000 rather than 20000, and `-I big` and `-I ./big` — the same
    // directory — would have different fates (one cached, the other refused).
    const pathSeen = new Map<string, boolean>();
    const hashOnce = (tag: string, p: string): boolean => {
      const prev = pathSeen.get(p);
      if (prev !== undefined) {
        return prev;
      }
      const r = hashPath(h, tag, p);
      pathSeen.set(p, r);
      return r;
    };
    // Where a relative token could name a path FROM. `cd sub; … -I inc` moves the base, and a
    // template that `cd`s is not exotic; both bases are tried, which is the cold-start side.
    const bases = [cwd, ...cdBases(template, cwd)];
    /** Every absolute path a token could be. `~/inc` is expanded here because the SHELL expands
     *  it before the compiler ever sees it, and `resolve(cwd, '~/inc')` is a directory that does
     *  not exist — measured: a `-I ~/inc` template served a stale object. */
    const candidatePaths = (tok: string): string[] => {
      if (tok === '~' || tok.startsWith('~/')) {
        return [join(homedir(), tok.slice(1))];
      }
      return isAbsolute(tok) ? [tok] : bases.map((b) => resolve(b, tok));
    };
    const seen = new Set<string>();
    const seenEnv = new Set<string>();
    for (const tok of scanTokens(template)) {
      if (seen.has(tok)) {
        continue;
      }
      seen.add(tok);
      // EVERY token is tried as a path — `statSync` is what answers "is this one", and that IS
      // the measurement. A path-SHAPE guard in front of it (`/[/.]/.test(tok)`) is a heuristic in
      // front of a measurement: it drops every bare-word operand, which is the `-iquote include`
      // hole itself and, with no list to fall back on, `-fsome-future-flag inc` too.
      let onDisk = false;
      let execPath: string | undefined;
      for (const p of candidatePaths(tok)) {
        if (hashOnce(tok, p)) {
          onDisk = true;
          if (execPath === undefined && isExecutableFile(p)) {
            execPath = p;
          }
        }
      }
      if (execPath !== undefined) {
        // A token that names an EXECUTABLE file (`./tools/agbcc/bin/agbcc`) can be a wrapper too,
        // so follow it as well; a plain data file (`charmap.txt`) has no chain and costs one stat.
        for (const f of toolchainFileChain(execPath)) {
          hashChain(h, tok, f);
        }
      }
      if (onDisk && /[/.]/.test(tok)) {
        // A token spelled as a path means the same thing to `sh` as it does here, so there is no
        // second reading to chase. A BARE word has one — the delegate chain — and falls through.
        continue;
      }
      if (/^[A-Za-z][\w.+-]*$/.test(tok)) {
        // Not "the file this name resolves to" — the whole CHAIN that actually runs. A `cpp` that
        // is a `#!/bin/sh` shim exec'ing `cpp-14`, or a gcc driver exec'ing `cc1`, has its
        // compiler one level past the file a namespace would otherwise hash; repointing the
        // delegate served a stale object with the outer file byte-identical. `toolchainFileChain`
        // THROWS where it cannot follow, and `candCache` turns that into a loud refusal.
        for (const f of toolchainFileChain(tok)) {
          hashChain(h, tok, f);
        }
      }
    }
    // (2b) the paths only a FLAG names, because the operand is glued to it (`-Iinc`), lives in a
    // file (`@opts`, `-specs=x.specs`), or is a pattern rather than a path (`inc/*.h`). The
    // separated spellings are already covered by the token scan; these are what `statSync`
    // structurally cannot be asked about.
    //
    // Tagged by BASENAME, never by absolute path, for the same reason the delegate chain is: a
    // toolchain MOVED but not changed should keep its digest. (It does not follow that two
    // worktrees share a namespace — `h.update(cwd)` settles that, and they do not.)
    for (const operand of templatePathOperands(template, cwd)) {
      for (const p of candidatePaths(operand)) {
        // An operand that is not there contributes nothing and needs no MISSING marker: the
        // template TEXT is hashed unconditionally, so absent -> present still moves the namespace
        // and two different absent operands cannot collide.
        hashOnce('flag:' + basename(operand), p);
      }
    }
    // (3b) the compile ENVIRONMENT gcc/cpp read whether or not the template mentions it — the one
    // list, shared with the bench's agbcc pipeline (candcache.ts `COMPILE_ENV`). The VALUE is the
    // answer for `SOURCE_DATE_EPOCH`; for the search-path variables it is only half of one —
    // `CPATH=inc` reaches `inc/k.h` exactly as `-I inc` does, and gcc honours it even under
    // `-nostdinc`. So each `:`-separated segment is hashed as a path too.
    for (const v of COMPILE_ENV) {
      const val = process.env[v] ?? '';
      h.update(`compileenv:${v}=${val}`);
      for (const seg of val.split(':')) {
        if (seg) {
          hashOnce(`compileenv:${v}:` + basename(seg), isAbsolute(seg) ? seg : resolve(cwd, seg));
        }
      }
    }
    for (const m of stripShellComments(template).matchAll(/\$\{?([A-Za-z_]\w*)\}?/g)) {
      const v = m[1];
      if (assigned.has(v) || seenEnv.has(v)) {
        continue;
      }
      seenEnv.add(v);
      const val = process.env[v] ?? '';
      h.update('env:' + v + '=' + val);
      if (val) {
        for (const q of candidatePaths(val)) {
          hashOnce('env:' + v, q);
        }
      }
    }
    // (4) BACKSTOP + DETERMINISM SELF-TEST, in one measurement. The object bytes this template
    // produces for one fixed probe TU, compiled TWICE in two different directories. Identical
    // means the object is a pure function of its input and the bytes join the namespace;
    // different means NOT_CACHEABLE, refused out loud. MEASURED: `ido7.1` writes the absolute
    // path of its input .c into the object (1108 vs 1124 bytes at two scratch paths); agbcc does
    // not.
    const d1 = stampSlot();
    const d2 = stampSlot2();
    const p1 = executeInSlot(d1, STAMP_PROBE, 'asmlift_candcache_stamp', 'c');
    const p2 = executeInSlot(d2, STAMP_PROBE, 'asmlift_candcache_stamp', 'c');
    const answer = ((): string => {
      if (!p1.ok || !p2.ok) {
        return NOT_CACHEABLE;
      }
      const b1 = sha256(readFileSync(p1.cmd));
      if (b1 !== sha256(readFileSync(p2.cmd))) {
        return NOT_CACHEABLE;
      }
      h.update(b1);
      return h.digest('hex');
    })();
    // mkdtemp removes nothing: two probe directories per process, forever, is the leak
    // `scratchSlot` was written to stop.
    rmSync(d1, { recursive: true, force: true });
    rmSync(d2, { recursive: true, force: true });
    return answer;
  };
  // ON, for any project's own command, unless ASMLIFT_CANDCACHE says otherwise — there is no
  // second, per-project opt-IN. A project DECLARING what its command reads is wrong in the stale-object
  // direction the moment the declaration is incomplete, and nothing verifies it; the namespace
  // measures those inputs instead (`stamp()`).
  //
  // `tools.asmlift.candidateCache: off` is the only per-project key, and it is the other shape: a
  // REFUSAL, never an assertion, so getting it wrong costs a cold start. It answers what the
  // process-global `ASMLIFT_CANDCACHE` cannot: a user with two projects, one of them computing a
  // compiler path in a wrapper, would otherwise have to disable the cache for BOTH.
  const cache = opts.candidateCache === 'off' ? OFF_CACHE : candCache('command', stamp);
  // A negative entry is only sound for a DETERMINISTIC rejection: the template RAN and exited
  // nonzero. `compile command failed to start` (a missing shell, a fork failure) and a killed
  // process must never be stored: a transient would then drop that candidate on every future
  // run, which is the silent-wrong-answer shape this repo bans.
  const DETERMINISTIC_REJECTION = /^compile command (failed \(exit \d+\)|exited 0 but produced no object)/;
  /** A rejection is storable only when the SPAWN RESULT says the compiler gave a verdict, and only
   *  when the message has the shape one has. Two guards, because each has been the one that held:
   *  the message shape alone stored a SIGKILL laundered by `sh` into `exit 137`. */
  const storableRejection = (r: Verdict): boolean => !r.transient && DETERMINISTIC_REJECTION.test(r.err);
  // A candidate TU whose object is not a function of its own bytes is refused PER KEY, keeping the
  // cache on for every other candidate. Two shapes, both in `candidateCacheRefusal` (shared with
  // the bench pipeline, because a predicate copied into two files is a predicate fixed in one):
  // a TU that READS A FILE — the path lives in the TU, not in the template's tokens, and no probe
  // exercises it — and a TU that bakes its own path or the clock in via `__FILE__` / `__DATE__`.
  const cacheable = (content: string): boolean => {
    if (cache.mode === 'off') {
      return false;
    }
    const reason = candidateCacheRefusal(content);
    if (reason === undefined) {
      return true;
    }
    noteKeyRefused('command', reason);
    return false;
  };
  const viaCache = (content: string, symbol: string, ext: 'c' | 'p', raw: () => Verdict): Verdict => {
    if (!cacheable(content)) {
      return raw();
    }
    const key = ext + ' ' + content;
    if (cache.mode === 'on') {
      const hit = cache.get(key, symbol);
      if (typeof hit === 'string') {
        return { ok: true, transient: false, cmd: hit, err: '' };
      }
      if (hit instanceof Error) {
        return { ok: false, transient: false, cmd: '', err: hit.message };
      }
    }
    const r = raw();
    if (r.ok) {
      cache.verify(key, symbol, r.cmd);
      return { ok: true, transient: false, cmd: cache.put(key, symbol, r.cmd), err: '' };
    }
    if (cache.mode !== 'off' && storableRejection(r)) {
      // verifyFail FIRST: a STORED OBJECT for a TU that no longer compiles is a mismatch, and it
      // is the direction that nothing audited — 77% of a warm store's served answers are
      // rejections and verify mode never looked at one.
      cache.verifyFail(key, symbol, r.err);
      cache.putFail(key, symbol, r.err);
    }
    return r;
  };
  const executeCached = (content: string, symbol: string, ext: 'c' | 'p'): Verdict =>
    viaCache(content, symbol, ext, () => execute(content, symbol, ext));
  // NOTE the slot is a THUNK: on a cache hit the worker's scratch dir is never emptied and
  // recreated, which is the whole point of not spawning.
  const executeInCached = async (
    dir: () => string,
    content: string,
    symbol: string,
    ext: 'c' | 'p',
  ): Promise<Verdict> => {
    if (!cacheable(content)) {
      return executeIn(dir(), content, symbol, ext);
    }
    const key = ext + ' ' + content;
    if (cache.mode === 'on') {
      const hit = cache.get(key, symbol);
      if (typeof hit === 'string') {
        return { ok: true, transient: false, cmd: hit, err: '' };
      }
      if (hit instanceof Error) {
        return { ok: false, transient: false, cmd: '', err: hit.message };
      }
    }
    const r = await executeIn(dir(), content, symbol, ext);
    if (r.ok) {
      cache.verify(key, symbol, r.cmd);
      return { ok: true, transient: false, cmd: cache.put(key, symbol, r.cmd), err: '' };
    }
    if (cache.mode !== 'off' && storableRejection(r)) {
      cache.verifyFail(key, symbol, r.err);
      cache.putFail(key, symbol, r.err);
    }
    return r;
  };
  /** Resolve the namespace EAGERLY, before any candidate compiles. */
  const warmCache = (): void => cache.warm();

  const PROBE = 'int asmlift_prelude_probe;\n';
  let preludeOk: boolean | undefined;
  const probePrelude = (symbol: string): boolean => {
    if (execute(C_TYPEDEFS + PROBE_DECLS + PROBE, symbol, 'c').ok) {
      return true;
    }
    return !execute(PROBE, symbol, 'c').ok;
  };
  // The async twin, memoized as a PROMISE: N workers starting together would otherwise each see
  // an unset `preludeOk` and probe the world N times.
  let probing: Promise<boolean> | undefined;
  const probeAsync = (symbol: string): Promise<boolean> =>
    (probing ??= (async () => {
      const probeSlot = slot();
      if ((await executeIn(probeSlot(), C_TYPEDEFS + PROBE_DECLS + PROBE, symbol, 'c')).ok) {
        return true;
      }
      return !(await executeIn(probeSlot(), PROBE, symbol, 'c')).ok;
    })());

  // headers world ⇒ BOTH the prelude and the synthesized declarations drop — the injected
  // headers own the types and every declaration (a second copy is a C89 collision).
  // EXCEPT the address-cast macro defines: a duplicate `#define` with an identical body is
  // legal C (unlike a duplicate typedef or struct), and the headers world does NOT
  // necessarily supply them — a PREPROCESSED context has no macros left at all, so dropping
  // these turns a macro-named candidate into `undeclared identifier`. They are emitted in
  // both worlds for that reason.
  // The self-declared half is CORE's composition (declare.ts selfDeclaredContext), not a second
  // copy of `C_TYPEDEFS + decls` — the webapp's scorer calls the same function, so the two
  // scoring worlds cannot drift on what a candidate was compiled in.
  const preludeFor = (world: boolean, declarations?: string): string =>
    world ? selfDeclaredContext(declarations) : macroDefinesOf(declarations);
  const unwrap = (r: Verdict): string => {
    if (!r.ok) {
      throw new Error(r.err);
    }
    return r.cmd;
  };

  return {
    compile: (source, symbol, backendId, declarations) => {
      let prelude = '';
      if (backendId !== 'pascal') {
        preludeOk ??= probePrelude(symbol);
        prelude = preludeFor(preludeOk, declarations);
      }
      warmCache();
      return unwrap(executeCached(prelude + source, symbol, backendId === 'pascal' ? 'p' : 'c'));
    },
    selfDeclared: () => preludeOk,
    worker: () => {
      const mine = slot();
      return async (source, symbol, backendId, declarations) => {
        let prelude = '';
        if (backendId !== 'pascal') {
          preludeOk ??= await probeAsync(symbol);
          prelude = preludeFor(preludeOk, declarations);
        }
        warmCache();
        return unwrap(await executeInCached(mine, prelude + source, symbol, backendId === 'pascal' ? 'p' : 'c'));
      };
    },
  };
}

/** The synchronous candidate compiler alone — the shape every non-pooled caller wants. */
export function compileFromCommand(template: string, opts: CompileCommandOptions = {}): CandidateCompiler {
  return compilersFromCommand(template, opts).compile;
}
