// The site asserts that the data it SHIPS is fully described by the vocabulary it renders.
// apps/benchmark runs the same closure check against its own freshly-merged results; this one reads
// the COMMITTED snapshot, the file the picker and the definition drawer actually render — so a
// results.json regenerated by a checkout whose vocabulary had drifted cannot ship a tag with no
// definition behind it.
import { FEATURES, FEATURE_BY_ID, GROUP_ORDER, KNOWN_FEATURES } from '@asmlift/bench-schema';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { expect, test } from 'vitest';

const results = JSON.parse(
  readFileSync(join(import.meta.dirname, '../src/pages/benchmark/data/results.json'), 'utf8'),
) as { results: { id: string; features: string[] }[] };

const rows = results.results;

test('every tag in the published dataset has a definition', () => {
  const undocumented = new Set<string>();
  for (const r of rows) {
    for (const f of r.features) {
      if (!KNOWN_FEATURES.has(f)) {
        undocumented.add(`${f} (e.g. ${r.id})`);
      }
    }
  }
  expect([...undocumented].sort()).toEqual([]);
});

test('every definition is carried by at least one published row', () => {
  const published = new Set(rows.flatMap((r) => r.features));
  expect(
    FEATURES.filter((f) => !f.deprecated && !published.has(f.id))
      .map((f) => f.id)
      .sort(),
  ).toEqual([]);
});

test('every row carries at least one tag, so no row is invisible to the feature filter', () => {
  expect(rows.filter((r) => r.features.length === 0).map((r) => r.id)).toEqual([]);
});

test('the vocabulary renders: every entry has a label, a summary and a known group', () => {
  const broken = FEATURES.filter((f) => !f.label.trim() || !f.summary.trim() || !GROUP_ORDER.includes(f.group)).map(
    (f) => f.id,
  );
  expect(broken).toEqual([]);
  expect(FEATURE_BY_ID.size).toBe(FEATURES.length);
});
