// The playground footer's numbers (summary.json) and the Benchmark view's dataset (results.json)
// are both regenerated by merge.ts — this pins that the committed copies agree, so a partial
// regeneration or hand edit can't desynchronize the app's two views of the same run.
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { expect, test } from 'vitest';

import summary from '../src/data/summary.json';

const results = JSON.parse(readFileSync(join(import.meta.dirname, '../src/pages/benchmark/data/results.json'), 'utf8'));

test('summary.json matches results.json (totals, match counts, provenance)', () => {
  const rows = results.results;
  expect(summary.total).toBe(rows.length);
  expect(summary.match.asmlift).toBe(
    rows.filter((r: { asmlift: { outcome: string } }) => r.asmlift.outcome === 'match').length,
  );
  expect(summary.match.m2c).toBe(rows.filter((r: { m2c: { outcome: string } }) => r.m2c.outcome === 'match').length);
  expect(summary.commit).toBe(results.meta.asmlift?.commit ?? null);
});

test('the committed numbers carry CLEAN provenance (dirty runs must not be published)', () => {
  expect(results.meta.asmlift?.dirty).toBe(false);
  expect(summary.dirty).toBe(false);
});
