// Regenerate the committed switch-vs-ladder spelling fixtures read by
// `packages/core/test/switch-arms.test.ts`.
//
// WHY A SCRIPT AND NOT A NOTE. `switchRequiresFrontLoadedTests` (target.ts) is a COMPILER claim
// about two SOURCE spellings — that a `switch` and the if/else-if ladder over the same values are
// different objects, and which way each lays its tests out — so the repo's rule is to compile both
// and commit the objects rather than describe them. Committing the disassembly made the claim
// re-readable; this makes it re-MEASURABLE, the same standard `scripts/regen-declrank-probes.ts`
// already sets for the declaration-rank probes: without a regen path, reproducing a pair means
// reconstructing its source by reading the disassembly.
//
// The flags are load-bearing and differ between the three toolchains here, so they are taken from
// `@asmlift/toolchains` rather than retyped — a flag change shows up as a diff in the regenerated
// fixtures.
//
//   ASMLIFT_AGBCC=… ASMLIFT_KMC_DIR=… ASMLIFT_GCC272_DIR=… npx tsx scripts/regen-switch-spelling-probes.ts
//
// Needs Docker for the two GCC 2.7.2 toolchains (both ship Linux/i386 binaries). Rewrites the
// `agbcc-sw*.s` and `gcc272{,kmc}-sw*.asm` fixtures in place, each with a provenance header naming
// the compiler as an `ASMLIFT_*` env name (never a machine path), its flags, and — for the MIPS
// lane, which commits a DISASSEMBLY rather than the compiler's own text — the objdump command.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import {
  TOOLCHAIN as AGBCC_TOOLCHAIN,
  GCC272_TOOLCHAIN,
  GCC_KMC_TOOLCHAIN,
  compileMipsGcc272Target,
  compileMipsGccTarget,
  compileTargetAsm,
} from '../packages/toolchains/src/index';

const CORPUS = join(import.meta.dirname, '..', 'packages', 'core', 'test', 'corpus');

const READ_BY = 'packages/core/test/switch-arms.test.ts';

/** The MIPS lane: one two-case body written each way, disassembled. `swpick` is the symbol the
 *  recovery test lifts. */
const MIPS_LANE = [
  {
    slug: 'gcc272kmc',
    envVar: 'ASMLIFT_KMC_DIR',
    description: "MIPS_GCC (gcc2.7.2kmc — Snowboard Kids 2's Kyoto build, -O2)",
    flags: GCC_KMC_TOOLCHAIN.ccFlags,
    objdump: `${GCC_KMC_TOOLCHAIN.objdump} ${GCC_KMC_TOOLCHAIN.objdumpFlags.join(' ')}`,
    compile: compileMipsGccTarget,
  },
  {
    slug: 'gcc272',
    envVar: 'ASMLIFT_GCC272_DIR',
    description: "MIPS_GCC (gcc2.7.2 — Mario Party 3's build, -O1)",
    flags: GCC272_TOOLCHAIN.ccFlags,
    objdump: `${GCC272_TOOLCHAIN.objdump} ${GCC272_TOOLCHAIN.objdumpFlags.join(' ')}`,
    compile: compileMipsGcc272Target,
  },
] as const;

const MIPS_VARIANTS = [
  { suffix: 'swfrontload', src: 'probe-swfrontload.c' },
  { suffix: 'swladder', src: 'probe-swladder.c' },
] as const;

for (const t of MIPS_LANE) {
  for (const v of MIPS_VARIANTS) {
    const c = readFileSync(join(CORPUS, v.src), 'utf8');
    const { asm } = t.compile(c, 'swpick');
    // objdump prints the object's PATH, and the compile runs in a per-content temp dir — a machine
    // path in a committed fixture would make every regeneration a diff and would leak a local
    // directory into the repo. Normalised to `corpus.o`.
    const body = asm.replace(/^\S*ref\.o:(\s+file format)/m, 'corpus.o:$1');
    const header =
      `# GENERATED by scripts/regen-switch-spelling-probes.ts — do not hand-edit.\n` +
      `# source    : packages/core/test/corpus/${v.src}\n` +
      `# toolchain : ${t.description}, binary from $${t.envVar}\n` +
      `# cc flags  : ${t.flags.join(' ')}\n` +
      `# objdump   : ${t.objdump}\n` +
      `# read by   : ${READ_BY}\n`;
    const out = join(CORPUS, `${t.slug}-${v.suffix}.asm`);
    writeFileSync(out, header + body);
    console.log(`wrote ${out}`);
  }
}

/** The agbcc lane: agbcc emits TEXT, so what is committed is the compiler's own `.s` — no objdump
 *  step and nothing to normalise. Three fixtures, not two: the pair the declaration rests on, plus
 *  the NESTED tree that pins what PRE5's decline actually produces when the tree it declines holds
 *  a sub-tree that re-recovers (switch-recover.ts PRE5, "WHAT THE DECLINE PRODUCES"). */
const AGBCC_VARIANTS = [
  { out: 'agbcc-swfrontload.s', src: 'probe-agbcc-swfrontload.c' },
  { out: 'agbcc-swladder.s', src: 'probe-agbcc-swladder.c' },
  { out: 'agbcc-swnested.s', src: 'probe-agbcc-swnested.c' },
] as const;

for (const v of AGBCC_VARIANTS) {
  const c = readFileSync(join(CORPUS, v.src), 'utf8');
  const header =
    `@ GENERATED by scripts/regen-switch-spelling-probes.ts — do not hand-edit.\n` +
    `@ source    : packages/core/test/corpus/${v.src}\n` +
    `@ toolchain : ARMV4T_AGBCC (gcc 2.9-arm, Thumb), binary from $ASMLIFT_AGBCC\n` +
    `@ cc flags  : ${AGBCC_TOOLCHAIN.agbccFlags.join(' ')}\n` +
    `@ read by   : ${READ_BY}\n`;
  const out = join(CORPUS, v.out);
  writeFileSync(out, header + compileTargetAsm(c));
  console.log(`wrote ${out}`);
}
