// Regenerate the committed merge-variable-vs-early-return spelling fixtures read by
// `packages/core/test/select-spelling.test.ts`.
//
// WHY A SCRIPT AND NOT A NOTE. `SELECT_GATES` (raise/retsink.ts) is a COMPILER claim about two
// SOURCE spellings of one function — that for a BARE constant-arm select agbcc hoists the constant
// above the compare and loses the diamond, so only the early-return spelling can reproduce a target
// that keeps one, and that giving either arm a BODY takes the hoist away and puts both spellings
// back on the same shape. The repo's rule for a claim of that kind is to compile both and commit
// the objects rather than describe them: RE-READABLE IS NOT RE-MEASURABLE, the standard
// `scripts/regen-switch-spelling-probes.ts` and `scripts/regen-declrank-probes.ts` already set.
//
//   ASMLIFT_AGBCC=… npx tsx scripts/regen-select-spelling-probes.ts
//
// agbcc emits TEXT, so what is committed is the compiler's own `.s` — no objdump step and nothing
// to normalise. The flags are taken from `@asmlift/toolchains` rather than retyped, so a flag
// change shows up as a diff in the regenerated fixtures.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { TOOLCHAIN as AGBCC_TOOLCHAIN, compileTargetAsm } from '../packages/toolchains/src/index';

const CORPUS = join(import.meta.dirname, '..', 'packages', 'core', 'test', 'corpus');

const READ_BY = 'packages/core/test/select-spelling.test.ts';

const VARIANTS = [
  { out: 'agbcc-select-merge.s', src: 'probe-agbcc-select-merge.c' },
  { out: 'agbcc-select-early.s', src: 'probe-agbcc-select-early.c' },
] as const;

for (const v of VARIANTS) {
  const c = readFileSync(join(CORPUS, v.src), 'utf8');
  const header =
    `@ GENERATED by scripts/regen-select-spelling-probes.ts — do not hand-edit.\n` +
    `@ source    : packages/core/test/corpus/${v.src}\n` +
    `@ toolchain : ARMV4T_AGBCC (gcc 2.9-arm, Thumb), binary from $ASMLIFT_AGBCC\n` +
    `@ cc flags  : ${AGBCC_TOOLCHAIN.agbccFlags.join(' ')}\n` +
    `@ read by   : ${READ_BY}\n`;
  const out = join(CORPUS, v.out);
  writeFileSync(out, header + compileTargetAsm(c));
  console.log(`wrote ${out}`);
}
