// Regenerate the committed declaration-rank probe objects read by
// `packages/core/test/spill-slot-order.test.ts`.
//
// WHY A SCRIPT AND NOT A NOTE. The three `'unknown'` frame directions in `target.ts` each record a
// measurement that was deliberately NOT shipped, and a measurement nobody can re-run is a claim.
// Committing the objdump text made it re-readable; this makes it re-MEASURABLE. The flags are
// load-bearing and differ between the two toolchains that share `MIPS_GCC` (Snowboard Kids 2's
// Kyoto build at -O2 and Mario Party 3's at -O1), so they are taken from `@asmlift/toolchains`
// rather than retyped — a flag change shows up here as a diff in the regenerated fixtures.
//
//   ASMLIFT_IDO_CC=… ASMLIFT_KMC_DIR=… ASMLIFT_GCC272_DIR=… npx tsx scripts/regen-declrank-probes.ts
//
// Needs Docker for the two GCC 2.7.2 toolchains (both ship Linux/i386 binaries). Rewrites the six
// `*-declrank*.txt` fixtures in place, each with a provenance header naming the compiler as an
// `ASMLIFT_*` env name (never a machine path), its flags, and the objdump command.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import {
  GCC272_TOOLCHAIN,
  GCC_KMC_TOOLCHAIN,
  IDO_TOOLCHAIN,
  compileMipsGcc272Target,
  compileMipsGccTarget,
  compileMipsTarget,
} from '../packages/toolchains/src/index';

const CORPUS = join(import.meta.dirname, '..', 'packages', 'core', 'test', 'corpus');

const TOOLCHAINS = [
  {
    slug: 'ido71',
    envVar: 'ASMLIFT_IDO_CC',
    description: 'MIPS_IDO (ido7.1)',
    flags: IDO_TOOLCHAIN.ccFlags,
    objdump: `${IDO_TOOLCHAIN.objdump} ${IDO_TOOLCHAIN.objdumpFlags.join(' ')}`,
    compile: compileMipsTarget,
  },
  {
    slug: 'gcc272kmc',
    envVar: 'ASMLIFT_KMC_DIR',
    description: "MIPS_GCC (gcc2.7.2kmc — Snowboard Kids 2's Kyoto build, -O2)",
    flags: GCC_KMC_TOOLCHAIN.ccFlags,
    objdump: `${GCC_KMC_TOOLCHAIN.objdump} ${GCC_KMC_TOOLCHAIN.objdumpFlags.join(' ')}`,
    compile: compileMipsGccTarget,
  },
  {
    slug: 'gcc272',
    envVar: 'ASMLIFT_GCC272_DIR',
    description: "MIPS_GCC (gcc2.7.2 — Mario Party 3's build, -O1)",
    flags: GCC272_TOOLCHAIN.ccFlags,
    objdump: `${GCC272_TOOLCHAIN.objdump} ${GCC272_TOOLCHAIN.objdumpFlags.join(' ')}`,
    compile: compileMipsGcc272Target,
  },
] as const;

const VARIANTS = [
  { suffix: '', src: 'probe-declrank.c' },
  { suffix: '-rev', src: 'probe-declrank-rev.c' },
] as const;

for (const t of TOOLCHAINS) {
  for (const v of VARIANTS) {
    const c = readFileSync(join(CORPUS, v.src), 'utf8');
    const { asm } = t.compile(c, 'probe');
    // objdump prints the object's PATH, and the compile runs in a per-content temp dir — a
    // machine path in a committed fixture would make every regeneration a diff and would leak a
    // local directory into the repo. Normalised to the name the object has in this probe.
    const body = asm.replace(/^\S*ref\.o:(\s+file format)/m, 'probe.o:$1');
    const header =
      `# GENERATED by scripts/regen-declrank-probes.ts — do not hand-edit.\n` +
      `# source    : packages/core/test/corpus/${v.src}\n` +
      `# toolchain : ${t.description}, binary from $${t.envVar}\n` +
      `# cc flags  : ${t.flags.join(' ')}\n` +
      `# objdump   : ${t.objdump}\n` +
      `# read by   : packages/core/test/spill-slot-order.test.ts (declRank/directionOf)\n`;
    const out = join(CORPUS, `${t.slug}-declrank${v.suffix}.txt`);
    writeFileSync(out, header + body);
    console.log(`wrote ${out}`);
  }
}
