// Regenerate the committed agbcc probe the placement of a 64-bit call argument rests on, read by
// `packages/core/test/double-args.test.ts`: a `double` and a `long long` in two argument registers,
// split across r3 and [sp,#0], and in the outgoing block, and the literals a `double` is staged from.
//
//   ASMLIFT_AGBCC=… npx tsx scripts/regen-double-arg-probes.ts
//
// agbcc emits TEXT, so what is committed is the compiler's own `.s`, at agbcc's canonical flags.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { TOOLCHAIN_TARGETS } from '../packages/core/src/target';
import { TOOLCHAIN, compileTargetAsm } from '../packages/toolchains/src/index';

const CORPUS = join(import.meta.dirname, '..', 'packages', 'core', 'test', 'corpus');
const SOURCE = 'probe-agbcc-double-args.c';
const OUT = 'agbcc-double-args.s';

const flags = TOOLCHAIN_TARGETS.agbcc.canonicalFlags;
const header =
  `@ GENERATED by scripts/regen-double-arg-probes.ts — do not hand-edit.\n` +
  `@ source    : packages/core/test/corpus/${SOURCE}\n` +
  `@ toolchain : ARMV4T_AGBCC (gcc 2.9-arm, Thumb), binary from $ASMLIFT_AGBCC\n` +
  `@ cc flags  : ${[...TOOLCHAIN.harnessFlags, ...flags].join(' ')}\n` +
  `@ read by   : packages/core/test/double-args.test.ts\n`;
const out = join(CORPUS, OUT);
writeFileSync(out, header + compileTargetAsm(readFileSync(join(CORPUS, SOURCE), 'utf8'), flags));
console.log(`wrote ${out}`);
