// Regenerate the committed agbcc probe pairs that compile one source at two flag sets, each read by
// the test its entry names.
//
// WHY A SCRIPT AND NOT A NOTE. A claim that a flag does or does not change what agbcc emits for a
// source is a COMPILER claim, and a declaration or a frontend rule that rests on one owes the
// objects: RE-READABLE IS NOT RE-MEASURABLE, the standard `scripts/regen-switch-spelling-probes.ts`
// sets.
//
//   ASMLIFT_AGBCC=… npx tsx scripts/regen-flag-pair-probes.ts
//
// agbcc emits TEXT, so what is committed is the compiler's own `.s`. The sources need no
// preprocessing, and each pair compiles at agbcc's canonical flags and at those flags with one change.
// The source is read from stdin in `/`, so a `-g` build's debug rows name `stdin` and `/` rather than
// a path on the machine that ran this.
import { spawnSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { TOOLCHAIN_TARGETS } from '../packages/core/src/target';
import { TOOLCHAIN } from '../packages/toolchains/src/index';

const CORPUS = join(import.meta.dirname, '..', 'packages', 'core', 'test', 'corpus');

const canonical = TOOLCHAIN_TARGETS.agbcc.canonicalFlags;

const PAIRS = [
  {
    // `readsStayWhereWritten` (target.ts) at -Os, where gcse.c's code hoister runs and at -O2 it
    // does not: the hoister moves the pool ADDRESS load above the branch and leaves each arm's
    // dereference in the arm that spelled it.
    source: 'probe-agbcc-hoist.c',
    readBy: 'packages/core/test/hoist-level-probes.test.ts',
    fixtures: [
      { out: 'agbcc-hoist-O2.s', flags: canonical },
      { out: 'agbcc-hoist-Os.s', flags: canonical.map((w) => (w === '-O2' ? '-Os' : w)) },
    ],
  },
  {
    // The Thumb frontend's debug skip (frontend/thumb.ts): `-g` leaves `.text` byte-identical and adds
    // `.debug_*` sections after the functions and marker labels inside them.
    source: 'probe-agbcc-debug.c',
    readBy: 'packages/core/test/debug-sections.test.ts',
    fixtures: [
      { out: 'agbcc-debug.s', flags: canonical },
      { out: 'agbcc-debug-g.s', flags: [...canonical, '-g'] },
    ],
  },
] as const;

const dir = mkdtempSync(join(tmpdir(), 'asmlift-flag-pairs-'));

for (const pair of PAIRS) {
  const source = readFileSync(join(CORPUS, pair.source), 'utf8');
  for (const fixture of pair.fixtures) {
    const argv = [...TOOLCHAIN.harnessFlags, ...fixture.flags];
    const sPath = join(dir, fixture.out);
    const cc = spawnSync(TOOLCHAIN.agbcc, ['-o', sPath, ...argv], { cwd: '/', input: source, encoding: 'utf8' });
    if (cc.status !== 0) {
      throw new Error(`agbcc failed on ${pair.source}: ${cc.error?.message ?? cc.stderr}`);
    }
    const header =
      `@ GENERATED by scripts/regen-flag-pair-probes.ts — do not hand-edit.\n` +
      `@ source    : packages/core/test/corpus/${pair.source}\n` +
      `@ toolchain : ARMV4T_AGBCC (gcc 2.9-arm, Thumb), binary from $ASMLIFT_AGBCC\n` +
      `@ cc flags  : ${argv.join(' ')}\n` +
      `@ read by   : ${pair.readBy}\n`;
    const out = join(CORPUS, fixture.out);
    writeFileSync(out, header + readFileSync(sPath, 'utf8'));
    console.log(`wrote ${out}`);
  }
}
