// Regenerate the committed agbcc probe the Thumb frontend's survivor bound rests on, read by
// `packages/core/test/outgoing-area-probes.test.ts`.
//
// WHY A SCRIPT AND NOT A NOTE. `survivorBound` (frontend/stackargs.ts) reads a compiler behavior
// BACKWARDS — agbcc never reads its outgoing area back after a call, so a word loaded after a call is
// a local — and being wrong costs an ANSWER, an argument dropped from a call. A backward reading owes
// the compiled objects it rests on, re-measurable and not only re-readable
// (`docs/level-tower.md`, RE-READABLE IS NOT RE-MEASURABLE). The probe holds both sides: `twice`
// re-stages an unchanged argument before its second call, and `owns` assigns to its own incoming
// stack parameter, which is its caller's outgoing word.
//
//   ASMLIFT_AGBCC=… npx tsx scripts/regen-outgoing-area-probes.ts
//
// agbcc emits TEXT, so what is committed is the compiler's own `.s`, at agbcc's canonical flags.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { TOOLCHAIN_TARGETS } from '../packages/core/src/target';
import { TOOLCHAIN, compileTargetAsm } from '../packages/toolchains/src/index';

const CORPUS = join(import.meta.dirname, '..', 'packages', 'core', 'test', 'corpus');
const SOURCE = 'probe-agbcc-restage.c';
const OUT = 'agbcc-restage.s';

const flags = TOOLCHAIN_TARGETS.agbcc.canonicalFlags;
const header =
  `@ GENERATED by scripts/regen-outgoing-area-probes.ts — do not hand-edit.\n` +
  `@ source    : packages/core/test/corpus/${SOURCE}\n` +
  `@ toolchain : ARMV4T_AGBCC (gcc 2.9-arm, Thumb), binary from $ASMLIFT_AGBCC\n` +
  `@ cc flags  : ${[...TOOLCHAIN.harnessFlags, ...flags].join(' ')}\n` +
  `@ read by   : packages/core/test/outgoing-area-probes.test.ts\n`;
const out = join(CORPUS, OUT);
writeFileSync(out, header + compileTargetAsm(readFileSync(join(CORPUS, SOURCE), 'utf8'), flags));
console.log(`wrote ${out}`);
