// One-click examples: real captured toolchain output from @asmlift/core's offline corpus
// (imported at build time via Vite ?raw — the same fixtures corpus-offline.test.ts pins).
import agbccClamp0 from '../../../../../packages/core/test/corpus/agbcc-clamp0.s?raw';
import agbccDeref from '../../../../../packages/core/test/corpus/agbcc-deref.s?raw';
import gccAget from '../../../../../packages/core/test/corpus/gcc-aget.asm?raw';
import gccClamp0 from '../../../../../packages/core/test/corpus/gcc-clamp0.asm?raw';
import idoClamp0 from '../../../../../packages/core/test/corpus/ido-clamp0.asm?raw';
import idoCountdown from '../../../../../packages/core/test/corpus/ido-countdown.asm?raw';
import idoMaxab from '../../../../../packages/core/test/corpus/ido-maxab.asm?raw';
import ppcDeref from '../../../../../packages/core/test/corpus/ppc-deref.asm?raw';
import ppcMaxab from '../../../../../packages/core/test/corpus/ppc-maxab.asm?raw';

export interface Example {
  label: string;
  target: string; // toolchain id (App's TARGETS key)
  backend?: string; // App BACKENDS key; default "c"
  spec?: string; // C++ signature JSON (backend "cpp")
  symbols?: string; // symbol-map JSON for the Symbols pane; absent ⇒ the pane loads empty
  asm: string;
}

// Real committed mwcceppc disassembly of `int Vec::dot(Vec*)` — the same fixture
// packages/cli/test/matching/ppc-cpp.test.ts pins offline.
const VEC_DOT_ASM = `00000000 <dot__3VecFP3Vec>:
   0:\tlwz     r6,0(r3)
   4:\tlwz     r5,0(r4)
   8:\tlwz     r3,4(r3)
   c:\tlwz     r0,4(r4)
  10:\tmullw   r4,r6,r5
  14:\tmullw   r0,r3,r0
  18:\tadd     r3,r4,r0
  1c:\tblr
`;

const VEC_DOT_SPEC = JSON.stringify({
  method: 'dot',
  cls: 'Vec',
  retType: { base: 'int', ptr: 0 },
  params: [{ name: 'o', type: { base: 'Vec', ptr: 1 } }],
  classes: {
    Vec: {
      fields: [
        { name: 'x', type: { base: 'int', ptr: 0 } },
        { name: 'y', type: { base: 'int', ptr: 0 } },
      ],
    },
  },
});

// agbcc's canonical Thumb lowering of `x / 2` (sign-correct pow2 division) — the shape the
// SDIV_POW2_2 idiom pattern folds, so the lifted and folded IR dumps differ on it (the Pipeline tab shows the rewrite).
const AGBCC_HALF_ASM = `\t.code\t16
\t.globl\thalf
\t.thumb_func
half:
\tlsr\tr1, r0, #31
\tadd\tr0, r0, r1
\tasr\tr0, r0, #1
\tbx\tlr
`;

// A symbol-map showcase: REAL agbcc -O2 output (byte-exact under ranking) for a function that
// touches every map shape. The pool words are symbolic, as in any decomp's compiled `.s` — so
// the names are already in the asm; what the MAP adds is the declaration shapes. With it:
//   gState.timer = gCounter + gState.timer + gBlendModeTable[a0];   (struct field via layout,
//   array indexing via elemSize, scalar signedness)
// Without it the same asm still decompiles, and only the STRUCT layout goes:
//   ((s32 *)&gState)[1] = gCounter + ((s32 *)&gState)[1] + gBlendModeTable[a0];
// The array subscript survives map-less because raise/globalshape.ts DERIVES that shape from the
// asm's own stride evidence (the pool `ldr` precedes the `lsl #0x1`, which is agbcc's
// array-subscript order) and reaches exactly the `elemSize: 2, elemSigned: false` the map below
// states — so map-less it is an ASSUMPTION the run publishes (`[assumed]`, and the Assumed
// declarations panel), map-ful it is the caller's own declaration and nothing is assumed. A
// struct layout has no such stride evidence, which is why `gState.timer` needs the map.
// The map only ever ADDS spellings, it never blocks a run.
export const SYMBOL_MAP_ASM = `@ Generated by gcc 2.9-arm-000512 for Thumb/elf
\t.code\t16
.gcc2_compiled.:
.text
\t.align\t2, 0
\t.globl\tUpdateTimer
\t.type\t UpdateTimer,function
\t.thumb_func
UpdateTimer:
\tpush\t{r4, lr}
\tldr\tr4, .L3
\tldr\tr1, .L3+0x4
\tldr\tr1, [r1]
\tldr\tr3, [r4, #0x4]
\tldr\tr2, .L3+0x8
\tlsl\tr0, r0, #0x1
\tadd\tr0, r0, r2
\tadd\tr1, r1, r3
\tldrh\tr0, [r0]
\tadd\tr1, r1, r0
\tstr\tr1, [r4, #0x4]
\tldr\tr0, .L3+0xc
\tpop\t{r4}
\tpop\t{r1}
\tbx\tr1
.L4:
\t.align\t2, 0
.L3:
\t.word\tgState
\t.word\tgCounter
\t.word\tgBlendModeTable
\t.word\tDoThing
.Lfe1:
\t.size\t UpdateTimer,.Lfe1-UpdateTimer
`;

// The vendored-map format (symbolMapToJson): hex address → SymbolInfo[]. The asm's pool words
// are symbolic, so the join here is by NAME; the addresses are what a real map carries anyway.
// Declaration facts ride each entry — signedness and element size are exactly the facts an
// offset alone cannot supply.
export const SYMBOL_MAP_JSON = `{
  "0x03001234": [{ "name": "gCounter", "kind": "data", "shape": "scalar", "size": 4, "signed": true }],
  "0x03002000": [
    {
      "name": "gState",
      "kind": "data",
      "shape": "struct",
      "size": 24,
      "structName": "GameState",
      "layout": [
        { "name": "frames", "offset": 0, "size": 4, "signed": true },
        { "name": "timer", "offset": 4, "size": 4, "signed": true }
      ]
    }
  ],
  "0x08057b4c": [
    { "name": "gBlendModeTable", "kind": "data", "shape": "array", "elemSize": 2, "elemSigned": false }
  ],
  "0x08012344": [{ "name": "DoThing", "kind": "code" }]
}
`;

export const EXAMPLES: Example[] = [
  { label: 'GBA / agbcc — clamp to zero (if-assign)', target: 'agbcc', asm: agbccClamp0 },
  { label: 'GBA / agbcc — pointer deref', target: 'agbcc', asm: agbccDeref },
  { label: 'GBA / agbcc — x / 2 (idiom folding: watch the Pipeline tab)', target: 'agbcc', asm: AGBCC_HALF_ASM },
  {
    label: 'GBA / agbcc — symbol map (named globals, struct fields, arrays)',
    target: 'agbcc',
    symbols: SYMBOL_MAP_JSON,
    asm: SYMBOL_MAP_ASM,
  },
  { label: 'N64 / IDO — countdown loop (while + coalesced induction var)', target: 'ido7.1', asm: idoCountdown },
  { label: 'N64 / IDO — clamp to zero (divergent if)', target: 'ido7.1', asm: idoClamp0 },
  { label: 'N64 / IDO — max(a, b)', target: 'ido7.1', asm: idoMaxab },
  { label: 'N64 / KMC GCC — branchless clamp (sign trick)', target: 'gcc2.7.2kmc', asm: gccClamp0 },
  { label: 'N64 / KMC GCC — array indexing a[i]', target: 'gcc2.7.2kmc', asm: gccAget },
  { label: 'GC / mwcc — max(a, b) (conditional return)', target: 'mwcc_242_81', asm: ppcMaxab },
  { label: 'GC / mwcc — pointer deref', target: 'mwcc_242_81', asm: ppcDeref },
  {
    label: 'GC / mwcc — Vec::dot (C++ member function, demangled)',
    target: 'mwcc_242_81',
    backend: 'cpp',
    spec: VEC_DOT_SPEC,
    asm: VEC_DOT_ASM,
  },
];
